export const queryKeys = {
  admin: {
    dashboardOverview: () => ["admin", "dashboard", "overview"] as const,
    dashboardEventChart: () => ["admin", "dashboard", "event-chart"] as const,
    health: () => ["admin", "health"] as const,
    users: (params?: Record<string, unknown>) => ["admin", "users", params ?? {}] as const,
    user: (id: string) => ["admin", "users", id] as const,
    userRoles: (id: string) => ["admin", "users", id, "roles"] as const,
    sellerApplications: (params?: Record<string, unknown>) => ["admin", "seller-applications", params ?? {}] as const,
    orders: (params?: Record<string, unknown>) => ["admin", "orders", params ?? {}] as const,
    order: (id: string) => ["admin", "orders", id] as const,
    orderStatusHistory: (id: string) => ["admin", "orders", id, "status-history"] as const,
    orderPayments: (id: string) => ["admin", "orders", id, "payments"] as const,
    orderShipments: (id: string) => ["admin", "orders", id, "shipments"] as const,
    wavePending: () => ["admin", "payments", "wave-pending"] as const,
    shippingProviders: () => ["admin", "shipping-providers"] as const,
    categories: () => ["admin", "categories"] as const,
    brands: () => ["admin", "brands"] as const,
    products: (params?: Record<string, unknown>) => ["admin", "products", params ?? {}] as const,
    product: (id: string) => ["admin", "products", id] as const,
    shipments: (params?: Record<string, unknown>) => ["admin", "shipments", params ?? {}] as const,
    shipment: (id: string) => ["admin", "shipments", id] as const,
    shipmentTracking: (id: string) => ["admin", "shipments", id, "tracking"] as const,
    webhookEvents: (params?: Record<string, unknown>) => ["admin", "payments", "webhooks", params ?? {}] as const,
    webhookEvent: (id: string) => ["admin", "payments", "webhooks", id] as const,
    vouchers: () => ["admin", "vouchers"] as const,
    reviewReports: () => ["admin", "review-reports"] as const,
    moderationReports: (params?: Record<string, unknown>) => ["admin", "moderation-reports", params ?? {}] as const,
    moderationCases: (params?: Record<string, unknown>) => ["admin", "moderation-cases", params ?? {}] as const,
    cmsPages: () => ["admin", "cms", "pages"] as const,
    cmsBanners: () => ["admin", "cms", "banners"] as const,
    cmsFaqs: () => ["admin", "cms", "faqs"] as const,
    cmsAnnouncements: () => ["admin", "cms", "announcements"] as const,
    roles: () => ["admin", "rbac", "roles"] as const,
    permissions: () => ["admin", "rbac", "permissions"] as const,
    platformSettings: () => ["admin", "settings", "platform"] as const,
    featureFlags: () => ["admin", "settings", "feature-flags"] as const,
    auditLogs: (params?: Record<string, unknown>) => ["admin", "logs", "audit", params ?? {}] as const,
    activityLogs: (params?: Record<string, unknown>) => ["admin", "logs", "activity", params ?? {}] as const,
    notifications: (params?: Record<string, unknown>) => ["admin", "notifications", params ?? {}] as const,
    notificationsUnread: () => ["admin", "notifications", "unread"] as const,
  },
  seller: {
    application: () => ["seller", "application"] as const,
    me: () => ["seller", "me"] as const,
    dashboard: () => ["seller", "dashboard"] as const,
    products: (params?: Record<string, unknown>) => ["seller", "products", params ?? {}] as const,
    product: (id: string) => ["seller", "products", id] as const,
    productImages: (id: string) => ["seller", "products", id, "images"] as const,
    variants: (id: string) => ["seller", "products", id, "variants"] as const,
    options: (id: string) => ["seller", "products", id, "options"] as const,
    inventory: (params?: Record<string, unknown>) => ["seller", "inventory", params ?? {}] as const,
    inventoryLowStock: () => ["seller", "inventory", "low-stock"] as const,
    inventoryItem: (id: string) => ["seller", "inventory", id] as const,
    inventoryMovements: (id: string, params?: Record<string, unknown>) =>
      ["seller", "inventory", id, "movements", params ?? {}] as const,
    orders: (params?: Record<string, unknown>) => ["seller", "orders", params ?? {}] as const,
    order: (id: string) => ["seller", "orders", id] as const,
    orderItems: (id: string) => ["seller", "orders", id, "items"] as const,
    orderShipments: (id: string) => ["seller", "orders", id, "shipments"] as const,
    vouchers: () => ["seller", "vouchers"] as const,
    wallet: () => ["seller", "wallet"] as const,
    walletTransactions: (params?: Record<string, unknown>) => ["seller", "wallet", "transactions", params ?? {}] as const,
    bankAccounts: () => ["seller", "bank-accounts"] as const,
    shippingSettings: () => ["seller", "shipping-settings"] as const,
    payouts: (params?: Record<string, unknown>) => ["seller", "payouts", params ?? {}] as const,
    chatConversations: (params?: Record<string, unknown>) => ["seller", "chat", "conversations", params ?? {}] as const,
    chatMessages: (conversationId: string, params?: Record<string, unknown>) =>
      ["seller", "chat", "conversations", conversationId, "messages", params ?? {}] as const,
    notifications: (params?: Record<string, unknown>) => ["seller", "notifications", params ?? {}] as const,
    notificationsUnread: () => ["seller", "notifications", "unread"] as const,
  },
  buyer: {
    cart: () => ["buyer", "cart"] as const,
    checkoutSession: (id: string) => ["buyer", "checkout", "session", id] as const,
    orders: (params?: Record<string, unknown>) => ["buyer", "orders", params ?? {}] as const,
    order: (id: string) => ["buyer", "orders", id] as const,
    orderItems: (id: string) => ["buyer", "orders", id, "items"] as const,
    orderStatusHistory: (id: string) => ["buyer", "orders", id, "status-history"] as const,
    orderTracking: (id: string) => ["buyer", "orders", id, "tracking"] as const,
    orderInvoice: (id: string) => ["buyer", "orders", id, "invoice"] as const,
    paymentMethods: () => ["buyer", "payment-methods"] as const,
    payment: (id: string) => ["buyer", "payments", id] as const,
    wishlist: () => ["buyer", "wishlist"] as const,
    localReviews: () => ["buyer", "reviews", "local"] as const,
    notifications: () => ["buyer", "notifications"] as const,
    notificationsUnread: () => ["buyer", "notifications", "unread"] as const,
    chatConversations: (params?: Record<string, unknown>) => ["buyer", "chat", "conversations", params ?? {}] as const,
    chatMessages: (conversationId: string, params?: Record<string, unknown>) =>
      ["buyer", "chat", "conversations", conversationId, "messages", params ?? {}] as const,
  },
  public: {
    home: () => ["public", "home"] as const,
    homeSections: () => ["public", "home", "sections"] as const,
    banners: (placement?: string) => ["public", "banners", { placement }] as const,
    categories: () => ["public", "categories"] as const,
    category: (id: string) => ["public", "categories", id] as const,
    brands: (params?: Record<string, unknown>) => ["public", "brands", params ?? {}] as const,
    brand: (id: string) => ["public", "brands", id] as const,
    seller: (id: string) => ["public", "sellers", id] as const,
    product: (id: string) => ["public", "products", id] as const,
    productSlug: (slug: string) => ["public", "products", "slug", slug] as const,
    productVariants: (id: string) => ["public", "products", id, "variants"] as const,
    productReviews: (id: string) => ["public", "products", id, "reviews"] as const,
    productRelated: (id: string) => ["public", "products", id, "related"] as const,
    listProducts: (params: Record<string, unknown>) => ["public", "products", params] as const,
    listCategoryProducts: (categoryId: string, params: Record<string, unknown>) =>
      ["public", "categories", categoryId, "products", params] as const,
    listBrandProducts: (brandId: string, params: Record<string, unknown>) =>
      ["public", "brands", brandId, "products", params] as const,
    listSellerProducts: (sellerId: string, params: Record<string, unknown>) =>
      ["public", "sellers", sellerId, "products", params] as const,
    listSellerReviews: (sellerId: string) => ["public", "sellers", sellerId, "reviews"] as const,
  },
} as const

