export const routes = {
  storefront: {
    home: "/",
    categories: "/categories",
    category: (id: string) => `/categories/${id}`,
    brands: "/brands",
    brand: (id: string) => `/brands/${id}`,
    products: "/products",
    product: (id: string) => `/products/${id}`,
    productSlug: (slug: string) => `/p/${slug}`,
    seller: (id: string) => `/sellers/${id}`,
    sellerSlug: (slug: string) => `/shop/${slug}`,
    search: "/search",
    cart: "/cart",
    wishlist: "/wishlist",
    checkout: "/checkout",
    checkoutPayment: "/checkout/payment",
    checkoutPending: "/checkout/pending",
    checkoutSuccess: (orderId: string) => `/checkout/success/${orderId}`,
    pages: (slug: string) => `/p/page/${slug}`,
  },
  auth: {
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    verifyEmail: "/verify-email",
    verifyPhone: "/verify-phone",
    oauthCallback: (provider: string) => `/auth/callback/${provider}`,
  },
  account: {
    overview: "/account",
    profile: "/account/profile",
    addresses: "/account/addresses",
    orders: "/account/orders",
    order: (id: string) => `/account/orders/${id}`,
    chat: "/account/chat",
    notifications: "/account/notifications",
    reviews: "/account/reviews",
    sessions: "/account/sessions",
    devices: "/account/devices",
    security: "/account/security",
    preferences: "/account/preferences",
    delete: "/account/delete",
  },
  seller: {
    apply: "/seller/apply",
    application: "/seller/application",
    dashboard: "/seller",
    profile: "/seller/profile",
    settings: "/seller/settings",
    products: "/seller/products",
    productNew: "/seller/products/new",
    product: (id: string) => `/seller/products/${id}`,
    inventory: "/seller/inventory",
    orders: "/seller/orders",
    order: (id: string) => `/seller/orders/${id}`,
    chat: "/seller/chat",
    shipping: "/seller/shipping",
    shipments: "/seller/shipments",
    promotions: "/seller/promotions",
    vouchers: "/seller/vouchers",
    reviews: "/seller/reviews",
    wallet: "/seller/wallet",
    payouts: "/seller/payouts",
    analytics: "/seller/analytics",
  },
  admin: {
    dashboard: "/admin",
    users: "/admin/users",
    user: (id: string) => `/admin/users/${id}`,
    sellers: "/admin/sellers",
    seller: (id: string) => `/admin/sellers/${id}`,
    products: "/admin/products",
    product: (id: string) => `/admin/products/${id}`,
    categories: "/admin/categories",
    brands: "/admin/brands",
    orders: "/admin/orders",
    order: (id: string) => `/admin/orders/${id}`,
    payments: "/admin/payments",
    waveApprovals: "/admin/payments/wave",
    shipments: "/admin/shipments",
    promotions: "/admin/promotions",
    moderation: "/admin/moderation",
    reports: "/admin/moderation/reports",
    cmsPages: "/admin/cms/pages",
    cmsBanners: "/admin/cms/banners",
    cmsFaqs: "/admin/cms/faqs",
    cmsAnnouncements: "/admin/cms/announcements",
    rbac: "/admin/rbac",
    settings: "/admin/settings",
    featureFlags: "/admin/settings/feature-flags",
    auditLogs: "/admin/audit-logs",
    activityLogs: "/admin/activity-logs",
    health: "/admin/system/health",
  },
  styleGuide: "/style-guide",
} as const
