// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :one
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, email, token_hash, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerificationToken, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET consumed_at = now()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, email, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, email, token_hash, expires_at, consumed_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken,
		arg.UserID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, consumed_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPhoneOTPAttempt = `-- name: CreatePhoneOTPAttempt :one
INSERT INTO phone_otp_attempts (user_id, phone, otp_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, phone, otp_hash, purpose, attempts, max_attempts, expires_at, verified_at, created_at
`

type CreatePhoneOTPAttemptParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Phone     string             `db:"phone" json:"phone"`
	OtpHash   string             `db:"otp_hash" json:"otp_hash"`
	Purpose   string             `db:"purpose" json:"purpose"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreatePhoneOTPAttempt(ctx context.Context, arg CreatePhoneOTPAttemptParams) (PhoneOtpAttempt, error) {
	row := q.db.QueryRow(ctx, createPhoneOTPAttempt,
		arg.UserID,
		arg.Phone,
		arg.OtpHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i PhoneOtpAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.OtpHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at, session_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at, session_id
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SessionID pgtype.UUID        `db:"session_id" json:"session_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.SessionID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.SessionID,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (user_id, device_id, user_agent, ip_address, platform, push_token)
VALUES (
  $1,
  $2,
  $3,
  CASE
    WHEN $6::text = '' THEN NULL
    ELSE CAST($6::text AS inet)
  END,
  $4,
  $5
)
RETURNING id, user_id, device_id, user_agent, ip_address, platform, push_token, last_seen_at, revoked_at, created_at, updated_at
`

type CreateUserSessionParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID  pgtype.Text `db:"device_id" json:"device_id"`
	UserAgent pgtype.Text `db:"user_agent" json:"user_agent"`
	Platform  pgtype.Text `db:"platform" json:"platform"`
	PushToken pgtype.Text `db:"push_token" json:"push_token"`
	IpText    pgtype.Text `db:"ip_text" json:"ip_text"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.DeviceID,
		arg.UserAgent,
		arg.Platform,
		arg.PushToken,
		arg.IpText,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.UserAgent,
		&i.IpAddress,
		&i.Platform,
		&i.PushToken,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPendingPhoneOTPForUser = `-- name: GetLatestPendingPhoneOTPForUser :one
SELECT id, user_id, phone, otp_hash, purpose, attempts, max_attempts, expires_at, verified_at, created_at
FROM phone_otp_attempts
WHERE user_id = $1
  AND purpose = $2
  AND verified_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestPendingPhoneOTPForUserParams struct {
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Purpose string      `db:"purpose" json:"purpose"`
}

func (q *Queries) GetLatestPendingPhoneOTPForUser(ctx context.Context, arg GetLatestPendingPhoneOTPForUserParams) (PhoneOtpAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestPendingPhoneOTPForUser, arg.UserID, arg.Purpose)
	var i PhoneOtpAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.OtpHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPhoneOTPAttemptByID = `-- name: GetPhoneOTPAttemptByID :one
SELECT id, user_id, phone, otp_hash, purpose, attempts, max_attempts, expires_at, verified_at, created_at
FROM phone_otp_attempts
WHERE id = $1
`

func (q *Queries) GetPhoneOTPAttemptByID(ctx context.Context, id pgtype.UUID) (PhoneOtpAttempt, error) {
	row := q.db.QueryRow(ctx, getPhoneOTPAttemptByID, id)
	var i PhoneOtpAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.OtpHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at, session_id
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.SessionID,
	)
	return i, err
}

const getUserSessionByID = `-- name: GetUserSessionByID :one
SELECT id, user_id, device_id, user_agent, ip_address, platform, push_token, last_seen_at, revoked_at, created_at, updated_at
FROM user_sessions
WHERE id = $1
  AND user_id = $2
`

type GetUserSessionByIDParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserSessionByID(ctx context.Context, arg GetUserSessionByIDParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByID, arg.ID, arg.UserID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.UserAgent,
		&i.IpAddress,
		&i.Platform,
		&i.PushToken,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionByIDForUser = `-- name: GetUserSessionByIDForUser :one
SELECT id, user_id, device_id, user_agent, ip_address, platform, push_token, last_seen_at, revoked_at, created_at, updated_at
FROM user_sessions
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type GetUserSessionByIDForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserSessionByIDForUser(ctx context.Context, arg GetUserSessionByIDForUserParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByIDForUser, arg.ID, arg.UserID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.UserAgent,
		&i.IpAddress,
		&i.Platform,
		&i.PushToken,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementPhoneOTPAttempts = `-- name: IncrementPhoneOTPAttempts :exec
UPDATE phone_otp_attempts
SET attempts = attempts + 1
WHERE id = $1
  AND verified_at IS NULL
`

func (q *Queries) IncrementPhoneOTPAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementPhoneOTPAttempts, id)
	return err
}

const listUserSessionsForUser = `-- name: ListUserSessionsForUser :many
SELECT id, user_id, device_id, user_agent, ip_address, platform, push_token, last_seen_at, revoked_at, created_at, updated_at
FROM user_sessions
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessionsForUser(ctx context.Context, userID pgtype.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listUserSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.UserAgent,
			&i.IpAddress,
			&i.Platform,
			&i.PushToken,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeRefreshTokensForSession = `-- name: RevokeRefreshTokensForSession :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE session_id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeRefreshTokensForSessionParams struct {
	SessionID pgtype.UUID `db:"session_id" json:"session_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeRefreshTokensForSession(ctx context.Context, arg RevokeRefreshTokensForSessionParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensForSession, arg.SessionID, arg.UserID)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
UPDATE user_sessions
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeUserSessionParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) error {
	_, err := q.db.Exec(ctx, revokeUserSession, arg.ID, arg.UserID)
	return err
}

const touchUserSession = `-- name: TouchUserSession :exec
UPDATE user_sessions
SET last_seen_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type TouchUserSessionParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) TouchUserSession(ctx context.Context, arg TouchUserSessionParams) error {
	_, err := q.db.Exec(ctx, touchUserSession, arg.ID, arg.UserID)
	return err
}

const upsertOAuthIdentity = `-- name: UpsertOAuthIdentity :one
INSERT INTO oauth_identities (user_id, provider, provider_user_id, email, raw_profile)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, provider_user_id) DO UPDATE
SET email = EXCLUDED.email,
    raw_profile = EXCLUDED.raw_profile
RETURNING id, user_id, provider, provider_user_id, email, raw_profile, created_at, updated_at
`

type UpsertOAuthIdentityParams struct {
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
	Provider       string      `db:"provider" json:"provider"`
	ProviderUserID string      `db:"provider_user_id" json:"provider_user_id"`
	Email          pgtype.Text `db:"email" json:"email"`
	RawProfile     []byte      `db:"raw_profile" json:"raw_profile"`
}

func (q *Queries) UpsertOAuthIdentity(ctx context.Context, arg UpsertOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, upsertOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.RawProfile,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.RawProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyPhoneOTPAttempt = `-- name: VerifyPhoneOTPAttempt :one
UPDATE phone_otp_attempts
SET verified_at = now()
WHERE id = $1
  AND verified_at IS NULL
  AND expires_at > now()
  AND attempts < max_attempts
RETURNING id, user_id, phone, otp_hash, purpose, attempts, max_attempts, expires_at, verified_at, created_at
`

func (q *Queries) VerifyPhoneOTPAttempt(ctx context.Context, id pgtype.UUID) (PhoneOtpAttempt, error) {
	row := q.db.QueryRow(ctx, verifyPhoneOTPAttempt, id)
	var i PhoneOtpAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.OtpHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
