// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConsumeEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	ConsumePasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreatePhoneOTPAttempt(ctx context.Context, arg CreatePhoneOTPAttemptParams) (PhoneOtpAttempt, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	GetLatestPendingPhoneOTPForUser(ctx context.Context, arg GetLatestPendingPhoneOTPForUserParams) (PhoneOtpAttempt, error)
	GetPhoneOTPAttemptByID(ctx context.Context, id pgtype.UUID) (PhoneOtpAttempt, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserSessionByID(ctx context.Context, arg GetUserSessionByIDParams) (UserSession, error)
	GetUserSessionByIDForUser(ctx context.Context, arg GetUserSessionByIDForUserParams) (UserSession, error)
	IncrementPhoneOTPAttempts(ctx context.Context, id pgtype.UUID) error
	ListUserSessionsForUser(ctx context.Context, userID pgtype.UUID) ([]UserSession, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	RevokeRefreshTokensForSession(ctx context.Context, arg RevokeRefreshTokensForSessionParams) error
	RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) error
	TouchUserSession(ctx context.Context, arg TouchUserSessionParams) error
	UpsertOAuthIdentity(ctx context.Context, arg UpsertOAuthIdentityParams) (OauthIdentity, error)
	VerifyPhoneOTPAttempt(ctx context.Context, id pgtype.UUID) (PhoneOtpAttempt, error)
}

var _ Querier = (*Queries)(nil)
