// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package orderstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyCartVoucher = `-- name: ApplyCartVoucher :one
UPDATE carts SET voucher_id = $2
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, session_id, created_at, updated_at, voucher_id
`

type ApplyCartVoucherParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	VoucherID pgtype.UUID `db:"voucher_id" json:"voucher_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ApplyCartVoucher(ctx context.Context, arg ApplyCartVoucherParams) (Cart, error) {
	row := q.db.QueryRow(ctx, applyCartVoucher, arg.ID, arg.VoucherID, arg.UserID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const applyCheckoutVoucher = `-- name: ApplyCheckoutVoucher :one
UPDATE checkout_sessions
SET voucher_id = $1,
    discount_cents = $2,
    total_cents = GREATEST(subtotal_cents - $2 + shipping_cents + tax_cents, 0)
WHERE id = $3 AND user_id = $4 AND status = 'open'
RETURNING id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
`

type ApplyCheckoutVoucherParams struct {
	VoucherID     pgtype.UUID `db:"voucher_id" json:"voucher_id"`
	DiscountCents int64       `db:"discount_cents" json:"discount_cents"`
	ID            pgtype.UUID `db:"id" json:"id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ApplyCheckoutVoucher(ctx context.Context, arg ApplyCheckoutVoucherParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, applyCheckoutVoucher,
		arg.VoucherID,
		arg.DiscountCents,
		arg.ID,
		arg.UserID,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const attachReservationToOrder = `-- name: AttachReservationToOrder :one
UPDATE inventory_reservations
SET order_id = $2
WHERE id = $1 AND released_at IS NULL
RETURNING id, inventory_item_id, user_id, checkout_session_id, order_id, quantity, expires_at, released_at, created_at
`

type AttachReservationToOrderParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	OrderID pgtype.UUID `db:"order_id" json:"order_id"`
}

func (q *Queries) AttachReservationToOrder(ctx context.Context, arg AttachReservationToOrderParams) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, attachReservationToOrder, arg.ID, arg.OrderID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.Quantity,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const clearDefaultAddress = `-- name: ClearDefaultAddress :exec
UPDATE user_addresses SET is_default = FALSE
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ClearDefaultAddress(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultAddress, userID)
	return err
}

const completeCheckoutSession = `-- name: CompleteCheckoutSession :one
UPDATE checkout_sessions
SET status = 'completed', completed_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'open'
RETURNING id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
`

type CompleteCheckoutSessionParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CompleteCheckoutSession(ctx context.Context, arg CompleteCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, completeCheckoutSession, arg.ID, arg.UserID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const consumeInventoryReservation = `-- name: ConsumeInventoryReservation :one
UPDATE inventory_items
SET quantity_available = quantity_available - $1,
    quantity_reserved = quantity_reserved - $1
WHERE id = $2
  AND quantity_available - $1 >= 0
  AND quantity_reserved - $1 >= 0
  AND quantity_reserved - $1 <= quantity_available - $1
RETURNING id, product_id, variant_id, quantity_available, quantity_reserved, low_stock_threshold, created_at, updated_at
`

type ConsumeInventoryReservationParams struct {
	Quantity int32       `db:"quantity" json:"quantity"`
	ID       pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ConsumeInventoryReservation(ctx context.Context, arg ConsumeInventoryReservationParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, consumeInventoryReservation, arg.Quantity, arg.ID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.QuantityAvailable,
		&i.QuantityReserved,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countDeliveredShipmentsForOrderSeller = `-- name: CountDeliveredShipmentsForOrderSeller :one
SELECT COUNT(1)::bigint
FROM shipments
WHERE order_id = $1 AND seller_id = $2 AND status = 'delivered'
`

type CountDeliveredShipmentsForOrderSellerParams struct {
	OrderID  pgtype.UUID `db:"order_id" json:"order_id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) CountDeliveredShipmentsForOrderSeller(ctx context.Context, arg CountDeliveredShipmentsForOrderSellerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveredShipmentsForOrderSeller, arg.OrderID, arg.SellerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCheckoutSession = `-- name: CreateCheckoutSession :one
INSERT INTO checkout_sessions (user_id, cart_id, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, voucher_id)
VALUES ($1, $2, COALESCE($3::text, 'USD'), $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
`

type CreateCheckoutSessionParams struct {
	UserID                 pgtype.UUID        `db:"user_id" json:"user_id"`
	CartID                 pgtype.UUID        `db:"cart_id" json:"cart_id"`
	Currency               pgtype.Text        `db:"currency" json:"currency"`
	SubtotalCents          int64              `db:"subtotal_cents" json:"subtotal_cents"`
	DiscountCents          int64              `db:"discount_cents" json:"discount_cents"`
	ShippingCents          int64              `db:"shipping_cents" json:"shipping_cents"`
	TaxCents               int64              `db:"tax_cents" json:"tax_cents"`
	TotalCents             int64              `db:"total_cents" json:"total_cents"`
	ShippingAddress        []byte             `db:"shipping_address" json:"shipping_address"`
	BillingAddress         []byte             `db:"billing_address" json:"billing_address"`
	PaymentMethod          pgtype.Text        `db:"payment_method" json:"payment_method"`
	SelectedShippingOption []byte             `db:"selected_shipping_option" json:"selected_shipping_option"`
	ExpiresAt              pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	VoucherID              pgtype.UUID        `db:"voucher_id" json:"voucher_id"`
}

func (q *Queries) CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, createCheckoutSession,
		arg.UserID,
		arg.CartID,
		arg.Currency,
		arg.SubtotalCents,
		arg.DiscountCents,
		arg.ShippingCents,
		arg.TaxCents,
		arg.TotalCents,
		arg.ShippingAddress,
		arg.BillingAddress,
		arg.PaymentMethod,
		arg.SelectedShippingOption,
		arg.ExpiresAt,
		arg.VoucherID,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const createCheckoutSessionItem = `-- name: CreateCheckoutSessionItem :one
INSERT INTO checkout_session_items (checkout_session_id, seller_id, product_id, variant_id, quantity, unit_price_cents, total_price_cents, currency, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, checkout_session_id, seller_id, product_id, variant_id, quantity, unit_price_cents, total_price_cents, currency, metadata, created_at
`

type CreateCheckoutSessionItemParams struct {
	CheckoutSessionID pgtype.UUID `db:"checkout_session_id" json:"checkout_session_id"`
	SellerID          pgtype.UUID `db:"seller_id" json:"seller_id"`
	ProductID         pgtype.UUID `db:"product_id" json:"product_id"`
	VariantID         pgtype.UUID `db:"variant_id" json:"variant_id"`
	Quantity          int32       `db:"quantity" json:"quantity"`
	UnitPriceCents    int64       `db:"unit_price_cents" json:"unit_price_cents"`
	TotalPriceCents   int64       `db:"total_price_cents" json:"total_price_cents"`
	Currency          string      `db:"currency" json:"currency"`
	Metadata          []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateCheckoutSessionItem(ctx context.Context, arg CreateCheckoutSessionItemParams) (CheckoutSessionItem, error) {
	row := q.db.QueryRow(ctx, createCheckoutSessionItem,
		arg.CheckoutSessionID,
		arg.SellerID,
		arg.ProductID,
		arg.VariantID,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.TotalPriceCents,
		arg.Currency,
		arg.Metadata,
	)
	var i CheckoutSessionItem
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.SellerID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.TotalPriceCents,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements (inventory_item_id, movement_type, quantity, reason, reference_type, reference_id, actor_user_id, before_available, after_available, before_reserved, after_reserved)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, inventory_item_id, movement_type, quantity, reason, reference_type, reference_id, created_at, actor_user_id, before_available, after_available, before_reserved, after_reserved
`

type CreateInventoryMovementParams struct {
	InventoryItemID pgtype.UUID `db:"inventory_item_id" json:"inventory_item_id"`
	MovementType    interface{} `db:"movement_type" json:"movement_type"`
	Quantity        int32       `db:"quantity" json:"quantity"`
	Reason          pgtype.Text `db:"reason" json:"reason"`
	ReferenceType   pgtype.Text `db:"reference_type" json:"reference_type"`
	ReferenceID     pgtype.UUID `db:"reference_id" json:"reference_id"`
	ActorUserID     pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	BeforeAvailable pgtype.Int4 `db:"before_available" json:"before_available"`
	AfterAvailable  pgtype.Int4 `db:"after_available" json:"after_available"`
	BeforeReserved  pgtype.Int4 `db:"before_reserved" json:"before_reserved"`
	AfterReserved   pgtype.Int4 `db:"after_reserved" json:"after_reserved"`
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, createInventoryMovement,
		arg.InventoryItemID,
		arg.MovementType,
		arg.Quantity,
		arg.Reason,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ActorUserID,
		arg.BeforeAvailable,
		arg.AfterAvailable,
		arg.BeforeReserved,
		arg.AfterReserved,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.MovementType,
		&i.Quantity,
		&i.Reason,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.ActorUserID,
		&i.BeforeAvailable,
		&i.AfterAvailable,
		&i.BeforeReserved,
		&i.AfterReserved,
	)
	return i, err
}

const createInventoryReservation = `-- name: CreateInventoryReservation :one
INSERT INTO inventory_reservations (inventory_item_id, user_id, checkout_session_id, quantity, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, inventory_item_id, user_id, checkout_session_id, order_id, quantity, expires_at, released_at, created_at
`

type CreateInventoryReservationParams struct {
	InventoryItemID   pgtype.UUID        `db:"inventory_item_id" json:"inventory_item_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	CheckoutSessionID pgtype.UUID        `db:"checkout_session_id" json:"checkout_session_id"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateInventoryReservation(ctx context.Context, arg CreateInventoryReservationParams) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, createInventoryReservation,
		arg.InventoryItemID,
		arg.UserID,
		arg.CheckoutSessionID,
		arg.Quantity,
		arg.ExpiresAt,
	)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.Quantity,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOrGetOrderInvoice = `-- name: CreateOrGetOrderInvoice :one
INSERT INTO order_invoices (order_id, invoice_number, payload)
VALUES ($1, $2, $3)
ON CONFLICT (order_id) DO UPDATE SET payload = order_invoices.payload
RETURNING id, order_id, invoice_number, status, payload, generated_at, created_at
`

type CreateOrGetOrderInvoiceParams struct {
	OrderID       pgtype.UUID `db:"order_id" json:"order_id"`
	InvoiceNumber string      `db:"invoice_number" json:"invoice_number"`
	Payload       []byte      `db:"payload" json:"payload"`
}

func (q *Queries) CreateOrGetOrderInvoice(ctx context.Context, arg CreateOrGetOrderInvoiceParams) (OrderInvoice, error) {
	row := q.db.QueryRow(ctx, createOrGetOrderInvoice, arg.OrderID, arg.InvoiceNumber, arg.Payload)
	var i OrderInvoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Payload,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (order_number, user_id, checkout_session_id, status, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, shipping_address, billing_address)
VALUES ($1, $2, $3, COALESCE($4::order_status, 'pending_payment'), $5, $6, $7, $8, $9, COALESCE($10::text, 'USD'), $11, $12)
RETURNING id, order_number, user_id, checkout_session_id, status, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, shipping_address, billing_address, placed_at, paid_at, cancelled_at, completed_at, created_at, updated_at
`

type CreateOrderParams struct {
	OrderNumber       string      `db:"order_number" json:"order_number"`
	UserID            pgtype.UUID `db:"user_id" json:"user_id"`
	CheckoutSessionID pgtype.UUID `db:"checkout_session_id" json:"checkout_session_id"`
	Status            interface{} `db:"status" json:"status"`
	SubtotalCents     int64       `db:"subtotal_cents" json:"subtotal_cents"`
	DiscountCents     int64       `db:"discount_cents" json:"discount_cents"`
	ShippingCents     int64       `db:"shipping_cents" json:"shipping_cents"`
	TaxCents          int64       `db:"tax_cents" json:"tax_cents"`
	TotalCents        int64       `db:"total_cents" json:"total_cents"`
	Currency          pgtype.Text `db:"currency" json:"currency"`
	ShippingAddress   []byte      `db:"shipping_address" json:"shipping_address"`
	BillingAddress    []byte      `db:"billing_address" json:"billing_address"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.UserID,
		arg.CheckoutSessionID,
		arg.Status,
		arg.SubtotalCents,
		arg.DiscountCents,
		arg.ShippingCents,
		arg.TaxCents,
		arg.TotalCents,
		arg.Currency,
		arg.ShippingAddress,
		arg.BillingAddress,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Currency,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItemFromCheckoutItem = `-- name: CreateOrderItemFromCheckoutItem :one
INSERT INTO order_items (order_id, seller_id, product_id, variant_id, product_name, variant_name, sku, image_url, quantity, unit_price_cents, total_price_cents, currency, status)
SELECT $1, csi.seller_id, csi.product_id, csi.variant_id,
       COALESCE(csi.metadata->>'product_name', 'Product') AS product_name,
       csi.metadata->>'variant_name' AS variant_name,
       csi.metadata->>'sku' AS sku,
       csi.metadata->>'image_url' AS image_url,
       csi.quantity, csi.unit_price_cents, csi.total_price_cents, csi.currency, 'pending_payment'::order_status
FROM checkout_session_items csi
WHERE csi.id = $2
RETURNING id, order_id, seller_id, product_id, variant_id, product_name, variant_name, sku, image_url, quantity, unit_price_cents, total_price_cents, currency, status, created_at
`

type CreateOrderItemFromCheckoutItemParams struct {
	OrderID        pgtype.UUID `db:"order_id" json:"order_id"`
	CheckoutItemID pgtype.UUID `db:"checkout_item_id" json:"checkout_item_id"`
}

func (q *Queries) CreateOrderItemFromCheckoutItem(ctx context.Context, arg CreateOrderItemFromCheckoutItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItemFromCheckoutItem, arg.OrderID, arg.CheckoutItemID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.ProductID,
		&i.VariantID,
		&i.ProductName,
		&i.VariantName,
		&i.Sku,
		&i.ImageUrl,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.TotalPriceCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createRefundRequest = `-- name: CreateRefundRequest :one
INSERT INTO refunds (order_id, requested_by, reason, amount_cents, currency, metadata)
SELECT o.id, $1, $2, o.total_cents, o.currency, COALESCE($3::jsonb, '{}'::jsonb)
FROM orders o
WHERE o.id = $4 AND o.user_id = $1
RETURNING id, order_id, payment_id, requested_by, status, reason, amount_cents, currency, reviewed_by, reviewed_at, processed_at, metadata, created_at, updated_at
`

type CreateRefundRequestParams struct {
	RequestedBy pgtype.UUID `db:"requested_by" json:"requested_by"`
	Reason      pgtype.Text `db:"reason" json:"reason"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
	OrderID     pgtype.UUID `db:"order_id" json:"order_id"`
}

func (q *Queries) CreateRefundRequest(ctx context.Context, arg CreateRefundRequestParams) (Refund, error) {
	row := q.db.QueryRow(ctx, createRefundRequest,
		arg.RequestedBy,
		arg.Reason,
		arg.Metadata,
		arg.OrderID,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.AmountCents,
		&i.Currency,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ProcessedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReturnRequest = `-- name: CreateReturnRequest :one
INSERT INTO return_requests (order_id, order_item_id, requested_by, reason, quantity, metadata)
SELECT oi.order_id, oi.id, $1, $2, LEAST($3::int, oi.quantity), COALESCE($4::jsonb, '{}'::jsonb)
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.id = $5 AND o.user_id = $1
RETURNING id, order_id, order_item_id, requested_by, status, reason, quantity, reviewed_by, reviewed_at, received_at, metadata, created_at, updated_at
`

type CreateReturnRequestParams struct {
	RequestedBy pgtype.UUID `db:"requested_by" json:"requested_by"`
	Reason      pgtype.Text `db:"reason" json:"reason"`
	Quantity    int32       `db:"quantity" json:"quantity"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
	OrderItemID pgtype.UUID `db:"order_item_id" json:"order_item_id"`
}

func (q *Queries) CreateReturnRequest(ctx context.Context, arg CreateReturnRequestParams) (ReturnRequest, error) {
	row := q.db.QueryRow(ctx, createReturnRequest,
		arg.RequestedBy,
		arg.Reason,
		arg.Quantity,
		arg.Metadata,
		arg.OrderItemID,
	)
	var i ReturnRequest
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrderItemID,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.Quantity,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReceivedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShipmentsForOrderSellers = `-- name: CreateShipmentsForOrderSellers :many
INSERT INTO shipments (order_id, seller_id)
SELECT DISTINCT oi.order_id, oi.seller_id
FROM order_items oi
WHERE oi.order_id = $1
RETURNING id, order_id, seller_id, provider_id, tracking_number, label_url, provider_metadata, status, shipped_at, delivered_at, created_at, updated_at
`

func (q *Queries) CreateShipmentsForOrderSellers(ctx context.Context, orderID pgtype.UUID) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, createShipmentsForOrderSellers, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipment
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.ProviderID,
			&i.TrackingNumber,
			&i.LabelUrl,
			&i.ProviderMetadata,
			&i.Status,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUserAddress = `-- name: CreateUserAddress :one
INSERT INTO user_addresses (user_id, full_name, phone, country, state, city, district, postal_code, address_line1, address_line2, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, full_name, phone, country, state, city, district, postal_code, address_line1, address_line2, latitude, longitude, is_default, deleted_at, created_at, updated_at
`

type CreateUserAddressParams struct {
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	FullName     string      `db:"full_name" json:"full_name"`
	Phone        string      `db:"phone" json:"phone"`
	Country      string      `db:"country" json:"country"`
	State        pgtype.Text `db:"state" json:"state"`
	City         pgtype.Text `db:"city" json:"city"`
	District     pgtype.Text `db:"district" json:"district"`
	PostalCode   pgtype.Text `db:"postal_code" json:"postal_code"`
	AddressLine1 string      `db:"address_line1" json:"address_line1"`
	AddressLine2 pgtype.Text `db:"address_line2" json:"address_line2"`
	IsDefault    bool        `db:"is_default" json:"is_default"`
}

func (q *Queries) CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, createUserAddress,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.Country,
		arg.State,
		arg.City,
		arg.District,
		arg.PostalCode,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.IsDefault,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Country,
		&i.State,
		&i.City,
		&i.District,
		&i.PostalCode,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoucherRedemption = `-- name: CreateVoucherRedemption :one
INSERT INTO voucher_redemptions (voucher_id, user_id, order_id, discount_cents)
VALUES ($1, $2, $3, $4)
RETURNING id, voucher_id, user_id, order_id, discount_cents, redeemed_at
`

type CreateVoucherRedemptionParams struct {
	VoucherID     pgtype.UUID `db:"voucher_id" json:"voucher_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
	OrderID       pgtype.UUID `db:"order_id" json:"order_id"`
	DiscountCents int64       `db:"discount_cents" json:"discount_cents"`
}

func (q *Queries) CreateVoucherRedemption(ctx context.Context, arg CreateVoucherRedemptionParams) (VoucherRedemption, error) {
	row := q.db.QueryRow(ctx, createVoucherRedemption,
		arg.VoucherID,
		arg.UserID,
		arg.OrderID,
		arg.DiscountCents,
	)
	var i VoucherRedemption
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.UserID,
		&i.OrderID,
		&i.DiscountCents,
		&i.RedeemedAt,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items ci
USING carts c
WHERE ci.cart_id = c.id
  AND ci.id = $1
  AND c.user_id = $2
`

type DeleteCartItemParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.UserID)
	return err
}

const deleteUserAddress = `-- name: DeleteUserAddress :exec
UPDATE user_addresses SET deleted_at = now(), is_default = FALSE
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type DeleteUserAddressParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) error {
	_, err := q.db.Exec(ctx, deleteUserAddress, arg.ID, arg.UserID)
	return err
}

const getActiveVariantForCart = `-- name: GetActiveVariantForCart :one
SELECT p.id AS product_id, p.seller_id, p.name AS product_name, p.slug AS product_slug,
       pv.id AS variant_id, pv.sku, pv.name AS variant_name, pv.price_cents, pv.currency,
       img.url AS image_url,
       COALESCE(inv.quantity_available - inv.quantity_reserved, 0)::int AS purchasable_quantity
FROM product_variants pv
JOIN products p ON p.id = pv.product_id
JOIN sellers s ON s.id = p.seller_id
LEFT JOIN inventory_items inv ON inv.variant_id = pv.id
LEFT JOIN LATERAL (
  SELECT url FROM product_images
  WHERE product_id = p.id
  ORDER BY is_primary DESC, sort_order ASC, created_at ASC
  LIMIT 1
) img ON TRUE
WHERE pv.id = $1
  AND pv.deleted_at IS NULL
  AND pv.is_active = TRUE
  AND p.deleted_at IS NULL
  AND p.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
`

type GetActiveVariantForCartRow struct {
	ProductID           pgtype.UUID `db:"product_id" json:"product_id"`
	SellerID            pgtype.UUID `db:"seller_id" json:"seller_id"`
	ProductName         string      `db:"product_name" json:"product_name"`
	ProductSlug         string      `db:"product_slug" json:"product_slug"`
	VariantID           pgtype.UUID `db:"variant_id" json:"variant_id"`
	Sku                 string      `db:"sku" json:"sku"`
	VariantName         pgtype.Text `db:"variant_name" json:"variant_name"`
	PriceCents          int64       `db:"price_cents" json:"price_cents"`
	Currency            string      `db:"currency" json:"currency"`
	ImageUrl            string      `db:"image_url" json:"image_url"`
	PurchasableQuantity int32       `db:"purchasable_quantity" json:"purchasable_quantity"`
}

func (q *Queries) GetActiveVariantForCart(ctx context.Context, id pgtype.UUID) (GetActiveVariantForCartRow, error) {
	row := q.db.QueryRow(ctx, getActiveVariantForCart, id)
	var i GetActiveVariantForCartRow
	err := row.Scan(
		&i.ProductID,
		&i.SellerID,
		&i.ProductName,
		&i.ProductSlug,
		&i.VariantID,
		&i.Sku,
		&i.VariantName,
		&i.PriceCents,
		&i.Currency,
		&i.ImageUrl,
		&i.PurchasableQuantity,
	)
	return i, err
}

const getActiveVoucherByCode = `-- name: GetActiveVoucherByCode :one
SELECT id, code, title, description, discount_type, discount_value, min_order_cents, max_discount_cents, usage_limit, usage_count, starts_at, ends_at, is_active, created_at, seller_id
FROM vouchers
WHERE upper(code) = upper($1)
  AND is_active = TRUE
  AND starts_at <= now()
  AND ends_at > now()
  AND (usage_limit IS NULL OR usage_count < usage_limit)
`

func (q *Queries) GetActiveVoucherByCode(ctx context.Context, upper interface{}) (Voucher, error) {
	row := q.db.QueryRow(ctx, getActiveVoucherByCode, upper)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinOrderCents,
		&i.MaxDiscountCents,
		&i.UsageLimit,
		&i.UsageCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.SellerID,
	)
	return i, err
}

const getCartForUser = `-- name: GetCartForUser :one
SELECT id, user_id, session_id, created_at, updated_at, voucher_id
FROM carts
WHERE user_id = $1
`

func (q *Queries) GetCartForUser(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartForUser, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const getCartItemForUser = `-- name: GetCartItemForUser :one
SELECT ci.id, ci.cart_id, ci.product_id, ci.variant_id, ci.quantity, ci.created_at, ci.updated_at, ci.selected
FROM cart_items ci
JOIN carts c ON c.id = ci.cart_id
WHERE ci.id = $1 AND c.user_id = $2
`

type GetCartItemForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetCartItemForUser(ctx context.Context, arg GetCartItemForUserParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemForUser, arg.ID, arg.UserID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Selected,
	)
	return i, err
}

const getCheckoutSession = `-- name: GetCheckoutSession :one
SELECT id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
FROM checkout_sessions
WHERE id = $1
`

func (q *Queries) GetCheckoutSession(ctx context.Context, id pgtype.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSession, id)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const getCheckoutSessionForUser = `-- name: GetCheckoutSessionForUser :one
SELECT id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
FROM checkout_sessions
WHERE id = $1 AND user_id = $2
`

type GetCheckoutSessionForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetCheckoutSessionForUser(ctx context.Context, arg GetCheckoutSessionForUserParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionForUser, arg.ID, arg.UserID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const getOrCreateCart = `-- name: GetOrCreateCart :one
INSERT INTO carts (user_id, session_id)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET updated_at = now()
RETURNING id, user_id, session_id, created_at, updated_at, voucher_id
`

type GetOrCreateCartParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	SessionID pgtype.Text `db:"session_id" json:"session_id"`
}

func (q *Queries) GetOrCreateCart(ctx context.Context, arg GetOrCreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getOrCreateCart, arg.UserID, arg.SessionID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const getOrderAndSellerForOrderItemForUser = `-- name: GetOrderAndSellerForOrderItemForUser :one
SELECT oi.order_id, oi.seller_id
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.id = $1 AND o.user_id = $2
`

type GetOrderAndSellerForOrderItemForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type GetOrderAndSellerForOrderItemForUserRow struct {
	OrderID  pgtype.UUID `db:"order_id" json:"order_id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) GetOrderAndSellerForOrderItemForUser(ctx context.Context, arg GetOrderAndSellerForOrderItemForUserParams) (GetOrderAndSellerForOrderItemForUserRow, error) {
	row := q.db.QueryRow(ctx, getOrderAndSellerForOrderItemForUser, arg.ID, arg.UserID)
	var i GetOrderAndSellerForOrderItemForUserRow
	err := row.Scan(&i.OrderID, &i.SellerID)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_number, user_id, checkout_session_id, status, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, shipping_address, billing_address, placed_at, paid_at, cancelled_at, completed_at, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Currency,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUser = `-- name: GetOrderForUser :one
SELECT id, order_number, user_id, checkout_session_id, status, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, shipping_address, billing_address, placed_at, paid_at, cancelled_at, completed_at, created_at, updated_at
FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetOrderForUser(ctx context.Context, arg GetOrderForUserParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Currency,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderIDForOrderItemForUser = `-- name: GetOrderIDForOrderItemForUser :one
SELECT oi.order_id
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.id = $1 AND o.user_id = $2
`

type GetOrderIDForOrderItemForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetOrderIDForOrderItemForUser(ctx context.Context, arg GetOrderIDForOrderItemForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrderIDForOrderItemForUser, arg.ID, arg.UserID)
	var order_id pgtype.UUID
	err := row.Scan(&order_id)
	return order_id, err
}

const getOrderInvoiceForUser = `-- name: GetOrderInvoiceForUser :one
SELECT oi.id, oi.order_id, oi.invoice_number, oi.status, oi.payload, oi.generated_at, oi.created_at
FROM order_invoices oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.order_id = $1 AND o.user_id = $2
`

type GetOrderInvoiceForUserParams struct {
	OrderID pgtype.UUID `db:"order_id" json:"order_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetOrderInvoiceForUser(ctx context.Context, arg GetOrderInvoiceForUserParams) (OrderInvoice, error) {
	row := q.db.QueryRow(ctx, getOrderInvoiceForUser, arg.OrderID, arg.UserID)
	var i OrderInvoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Payload,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSellerByUserID = `-- name: GetSellerByUserID :one
SELECT id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at, settings
FROM sellers
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSellerByUserID(ctx context.Context, userID pgtype.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByUserID, userID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const getSellerOrder = `-- name: GetSellerOrder :one
SELECT DISTINCT o.id, o.order_number, o.user_id, o.checkout_session_id, o.status, o.subtotal_cents, o.discount_cents, o.shipping_cents, o.tax_cents, o.total_cents, o.currency, o.shipping_address, o.billing_address, o.placed_at, o.paid_at, o.cancelled_at, o.completed_at, o.created_at, o.updated_at
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
WHERE o.id = $1 AND oi.seller_id = $2
`

type GetSellerOrderParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) GetSellerOrder(ctx context.Context, arg GetSellerOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getSellerOrder, arg.ID, arg.SellerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Currency,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAddress = `-- name: GetUserAddress :one
SELECT id, user_id, full_name, phone, country, state, city, district, postal_code, address_line1, address_line2, latitude, longitude, is_default, deleted_at, created_at, updated_at
FROM user_addresses
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetUserAddressParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserAddress(ctx context.Context, arg GetUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getUserAddress, arg.ID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Country,
		&i.State,
		&i.City,
		&i.District,
		&i.PostalCode,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoucherByID = `-- name: GetVoucherByID :one
SELECT id, code, title, description, discount_type, discount_value, min_order_cents, max_discount_cents, usage_limit, usage_count, starts_at, ends_at, is_active, created_at, seller_id
FROM vouchers
WHERE id = $1
  AND is_active = TRUE
  AND starts_at <= now()
  AND ends_at > now()
  AND (usage_limit IS NULL OR usage_count < usage_limit)
`

func (q *Queries) GetVoucherByID(ctx context.Context, id pgtype.UUID) (Voucher, error) {
	row := q.db.QueryRow(ctx, getVoucherByID, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinOrderCents,
		&i.MaxDiscountCents,
		&i.UsageLimit,
		&i.UsageCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.SellerID,
	)
	return i, err
}

const incrementVoucherUsage = `-- name: IncrementVoucherUsage :exec
UPDATE vouchers SET usage_count = usage_count + 1 WHERE id = $1
`

func (q *Queries) IncrementVoucherUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementVoucherUsage, id)
	return err
}

const insertOrderStatusHistory = `-- name: InsertOrderStatusHistory :one
INSERT INTO order_status_history (order_id, old_status, new_status, note, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, old_status, new_status, note, created_by, created_at
`

type InsertOrderStatusHistoryParams struct {
	OrderID   pgtype.UUID `db:"order_id" json:"order_id"`
	OldStatus interface{} `db:"old_status" json:"old_status"`
	NewStatus interface{} `db:"new_status" json:"new_status"`
	Note      pgtype.Text `db:"note" json:"note"`
	CreatedBy pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) InsertOrderStatusHistory(ctx context.Context, arg InsertOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertOrderStatusHistory,
		arg.OrderID,
		arg.OldStatus,
		arg.NewStatus,
		arg.Note,
		arg.CreatedBy,
	)
	var i OrderStatusHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OldStatus,
		&i.NewStatus,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminOrders = `-- name: ListAdminOrders :many
SELECT id, order_number, user_id, checkout_session_id, status, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, shipping_address, billing_address, placed_at, paid_at, cancelled_at, completed_at, created_at, updated_at
FROM orders
WHERE ($1::order_status IS NULL OR status = $1::order_status)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAdminOrdersParams struct {
	Status interface{} `db:"status" json:"status"`
	Offset int32       `db:"offset" json:"offset"`
	Limit  int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListAdminOrders(ctx context.Context, arg ListAdminOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listAdminOrders, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.CheckoutSessionID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Currency,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartItemsDetailed = `-- name: ListCartItemsDetailed :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.variant_id, ci.quantity, ci.selected, ci.created_at, ci.updated_at,
       p.name AS product_name, p.slug AS product_slug, p.seller_id, pv.sku, pv.name AS variant_name,
       pv.price_cents, pv.currency, img.url AS image_url,
       COALESCE(inv.quantity_available - inv.quantity_reserved, 0)::int AS purchasable_quantity
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
JOIN sellers s ON s.id = p.seller_id
JOIN product_variants pv ON pv.id = ci.variant_id
LEFT JOIN inventory_items inv ON inv.variant_id = pv.id
LEFT JOIN LATERAL (
  SELECT url FROM product_images
  WHERE product_id = p.id
  ORDER BY is_primary DESC, sort_order ASC, created_at ASC
  LIMIT 1
) img ON TRUE
WHERE ci.cart_id = $1
  AND p.deleted_at IS NULL
  AND p.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
  AND pv.deleted_at IS NULL
  AND pv.is_active = TRUE
ORDER BY ci.created_at DESC
`

type ListCartItemsDetailedRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	CartID              pgtype.UUID        `db:"cart_id" json:"cart_id"`
	ProductID           pgtype.UUID        `db:"product_id" json:"product_id"`
	VariantID           pgtype.UUID        `db:"variant_id" json:"variant_id"`
	Quantity            int32              `db:"quantity" json:"quantity"`
	Selected            bool               `db:"selected" json:"selected"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductName         string             `db:"product_name" json:"product_name"`
	ProductSlug         string             `db:"product_slug" json:"product_slug"`
	SellerID            pgtype.UUID        `db:"seller_id" json:"seller_id"`
	Sku                 string             `db:"sku" json:"sku"`
	VariantName         pgtype.Text        `db:"variant_name" json:"variant_name"`
	PriceCents          int64              `db:"price_cents" json:"price_cents"`
	Currency            string             `db:"currency" json:"currency"`
	ImageUrl            string             `db:"image_url" json:"image_url"`
	PurchasableQuantity int32              `db:"purchasable_quantity" json:"purchasable_quantity"`
}

func (q *Queries) ListCartItemsDetailed(ctx context.Context, cartID pgtype.UUID) ([]ListCartItemsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listCartItemsDetailed, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsDetailedRow
	for rows.Next() {
		var i ListCartItemsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.VariantID,
			&i.Quantity,
			&i.Selected,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ProductSlug,
			&i.SellerID,
			&i.Sku,
			&i.VariantName,
			&i.PriceCents,
			&i.Currency,
			&i.ImageUrl,
			&i.PurchasableQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckoutSessionItems = `-- name: ListCheckoutSessionItems :many
SELECT id, checkout_session_id, seller_id, product_id, variant_id, quantity, unit_price_cents, total_price_cents, currency, metadata, created_at
FROM checkout_session_items
WHERE checkout_session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCheckoutSessionItems(ctx context.Context, checkoutSessionID pgtype.UUID) ([]CheckoutSessionItem, error) {
	rows, err := q.db.Query(ctx, listCheckoutSessionItems, checkoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckoutSessionItem
	for rows.Next() {
		var i CheckoutSessionItem
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutSessionID,
			&i.SellerID,
			&i.ProductID,
			&i.VariantID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.TotalPriceCents,
			&i.Currency,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredReservations = `-- name: ListExpiredReservations :many
SELECT id, inventory_item_id, user_id, checkout_session_id, order_id, quantity, expires_at, released_at, created_at
FROM inventory_reservations
WHERE released_at IS NULL AND order_id IS NULL AND expires_at <= now()
ORDER BY expires_at ASC
LIMIT $1
`

func (q *Queries) ListExpiredReservations(ctx context.Context, limit int32) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, listExpiredReservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryReservation
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.UserID,
			&i.CheckoutSessionID,
			&i.OrderID,
			&i.Quantity,
			&i.ExpiresAt,
			&i.ReleasedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderCreditsBySeller = `-- name: ListOrderCreditsBySeller :many
SELECT seller_id, SUM(total_price_cents)::bigint AS amount_cents
FROM order_items
WHERE order_id = $1
GROUP BY seller_id
ORDER BY seller_id
`

type ListOrderCreditsBySellerRow struct {
	SellerID    pgtype.UUID `db:"seller_id" json:"seller_id"`
	AmountCents int64       `db:"amount_cents" json:"amount_cents"`
}

func (q *Queries) ListOrderCreditsBySeller(ctx context.Context, orderID pgtype.UUID) ([]ListOrderCreditsBySellerRow, error) {
	rows, err := q.db.Query(ctx, listOrderCreditsBySeller, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderCreditsBySellerRow
	for rows.Next() {
		var i ListOrderCreditsBySellerRow
		if err := rows.Scan(&i.SellerID, &i.AmountCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, seller_id, product_id, variant_id, product_name, variant_name, sku, image_url, quantity, unit_price_cents, total_price_cents, currency, status, created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.ProductID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Sku,
			&i.ImageUrl,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.TotalPriceCents,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderStatusHistory = `-- name: ListOrderStatusHistory :many
SELECT id, order_id, old_status, new_status, note, created_by, created_at
FROM order_status_history
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderStatusHistory(ctx context.Context, orderID pgtype.UUID) ([]OrderStatusHistory, error) {
	rows, err := q.db.Query(ctx, listOrderStatusHistory, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderStatusHistory
	for rows.Next() {
		var i OrderStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.OldStatus,
			&i.NewStatus,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForOrder = `-- name: ListPaymentsForOrder :many
SELECT id, order_id, payment_method_id, provider, provider_payment_id, status, amount_cents, currency, idempotency_key, metadata, paid_at, failed_at, created_at, updated_at
FROM payments
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPaymentsForOrder(ctx context.Context, orderID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentMethodID,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.PaidAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsForCheckout = `-- name: ListReservationsForCheckout :many
SELECT id, inventory_item_id, user_id, checkout_session_id, order_id, quantity, expires_at, released_at, created_at
FROM inventory_reservations
WHERE checkout_session_id = $1 AND released_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListReservationsForCheckout(ctx context.Context, checkoutSessionID pgtype.UUID) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, listReservationsForCheckout, checkoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryReservation
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.UserID,
			&i.CheckoutSessionID,
			&i.OrderID,
			&i.Quantity,
			&i.ExpiresAt,
			&i.ReleasedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsForOrder = `-- name: ListReservationsForOrder :many
SELECT id, inventory_item_id, user_id, checkout_session_id, order_id, quantity, expires_at, released_at, created_at
FROM inventory_reservations
WHERE order_id = $1 AND released_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListReservationsForOrder(ctx context.Context, orderID pgtype.UUID) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, listReservationsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryReservation
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.UserID,
			&i.CheckoutSessionID,
			&i.OrderID,
			&i.Quantity,
			&i.ExpiresAt,
			&i.ReleasedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerOrderItems = `-- name: ListSellerOrderItems :many
SELECT id, order_id, seller_id, product_id, variant_id, product_name, variant_name, sku, image_url, quantity, unit_price_cents, total_price_cents, currency, status, created_at
FROM order_items
WHERE order_id = $1 AND seller_id = $2
ORDER BY created_at ASC
`

type ListSellerOrderItemsParams struct {
	OrderID  pgtype.UUID `db:"order_id" json:"order_id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) ListSellerOrderItems(ctx context.Context, arg ListSellerOrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listSellerOrderItems, arg.OrderID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.ProductID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Sku,
			&i.ImageUrl,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.TotalPriceCents,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerOrders = `-- name: ListSellerOrders :many
SELECT DISTINCT o.id, o.order_number, o.user_id, o.checkout_session_id, o.status, o.subtotal_cents, o.discount_cents, o.shipping_cents, o.tax_cents, o.total_cents, o.currency, o.shipping_address, o.billing_address, o.placed_at, o.paid_at, o.cancelled_at, o.completed_at, o.created_at, o.updated_at
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
WHERE oi.seller_id = $1
  AND ($2::order_status IS NULL OR o.status = $2::order_status)
ORDER BY o.created_at DESC
LIMIT $4 OFFSET $3
`

type ListSellerOrdersParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Status   interface{} `db:"status" json:"status"`
	Offset   int32       `db:"offset" json:"offset"`
	Limit    int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListSellerOrders(ctx context.Context, arg ListSellerOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listSellerOrders,
		arg.SellerID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.CheckoutSessionID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Currency,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentsForOrder = `-- name: ListShipmentsForOrder :many
SELECT id, order_id, seller_id, provider_id, tracking_number, label_url, provider_metadata, status, shipped_at, delivered_at, created_at, updated_at
FROM shipments
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListShipmentsForOrder(ctx context.Context, orderID pgtype.UUID) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, listShipmentsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipment
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.ProviderID,
			&i.TrackingNumber,
			&i.LabelUrl,
			&i.ProviderMetadata,
			&i.Status,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleUnpaidOrders = `-- name: ListStaleUnpaidOrders :many
SELECT id, order_number, user_id, checkout_session_id, status, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, shipping_address, billing_address, placed_at, paid_at, cancelled_at, completed_at, created_at, updated_at
FROM orders
WHERE status = 'pending_payment'
  AND cancelled_at IS NULL
  AND paid_at IS NULL
  AND placed_at <= now() - ($1::int || ' minutes')::interval
ORDER BY placed_at ASC
LIMIT $2
`

type ListStaleUnpaidOrdersParams struct {
	OlderThanMinutes int32 `db:"older_than_minutes" json:"older_than_minutes"`
	Limit            int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListStaleUnpaidOrders(ctx context.Context, arg ListStaleUnpaidOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listStaleUnpaidOrders, arg.OlderThanMinutes, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.CheckoutSessionID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Currency,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingEventsForOrder = `-- name: ListTrackingEventsForOrder :many
SELECT ste.id, ste.shipment_id, ste.status, ste.location, ste.message, ste.event_time, ste.created_at
FROM shipment_tracking_events ste
JOIN shipments s ON s.id = ste.shipment_id
WHERE s.order_id = $1
ORDER BY ste.event_time ASC
`

func (q *Queries) ListTrackingEventsForOrder(ctx context.Context, orderID pgtype.UUID) ([]ShipmentTrackingEvent, error) {
	rows, err := q.db.Query(ctx, listTrackingEventsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentTrackingEvent
	for rows.Next() {
		var i ShipmentTrackingEvent
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.Status,
			&i.Location,
			&i.Message,
			&i.EventTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAddresses = `-- name: ListUserAddresses :many
SELECT id, user_id, full_name, phone, country, state, city, district, postal_code, address_line1, address_line2, latitude, longitude, is_default, deleted_at, created_at, updated_at
FROM user_addresses
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListUserAddresses(ctx context.Context, userID pgtype.UUID) ([]UserAddress, error) {
	rows, err := q.db.Query(ctx, listUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAddress
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Phone,
			&i.Country,
			&i.State,
			&i.City,
			&i.District,
			&i.PostalCode,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Latitude,
			&i.Longitude,
			&i.IsDefault,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT id, order_number, user_id, checkout_session_id, status, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, shipping_address, billing_address, placed_at, paid_at, cancelled_at, completed_at, created_at, updated_at
FROM orders
WHERE user_id = $1
  AND ($2::order_status IS NULL OR status = $2::order_status)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListUserOrdersParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Status interface{} `db:"status" json:"status"`
	Offset int32       `db:"offset" json:"offset"`
	Limit  int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUserOrders,
		arg.UserID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.CheckoutSessionID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Currency,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCheckoutSessionForUser = `-- name: LockCheckoutSessionForUser :one
SELECT id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
FROM checkout_sessions
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type LockCheckoutSessionForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) LockCheckoutSessionForUser(ctx context.Context, arg LockCheckoutSessionForUserParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, lockCheckoutSessionForUser, arg.ID, arg.UserID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const lockInventoryByID = `-- name: LockInventoryByID :one
SELECT id, product_id, variant_id, quantity_available, quantity_reserved, low_stock_threshold, created_at, updated_at
FROM inventory_items
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockInventoryByID(ctx context.Context, id pgtype.UUID) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, lockInventoryByID, id)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.QuantityAvailable,
		&i.QuantityReserved,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockInventoryByVariant = `-- name: LockInventoryByVariant :one
SELECT id, product_id, variant_id, quantity_available, quantity_reserved, low_stock_threshold, created_at, updated_at
FROM inventory_items
WHERE variant_id = $1
FOR UPDATE
`

func (q *Queries) LockInventoryByVariant(ctx context.Context, variantID pgtype.UUID) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, lockInventoryByVariant, variantID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.QuantityAvailable,
		&i.QuantityReserved,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReservationReleased = `-- name: MarkReservationReleased :one
UPDATE inventory_reservations
SET released_at = now()
WHERE id = $1 AND released_at IS NULL
RETURNING id, inventory_item_id, user_id, checkout_session_id, order_id, quantity, expires_at, released_at, created_at
`

func (q *Queries) MarkReservationReleased(ctx context.Context, id pgtype.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, markReservationReleased, id)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.Quantity,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markReturnReceivedForSeller = `-- name: MarkReturnReceivedForSeller :one
UPDATE return_requests rr
SET status = 'received',
    received_at = COALESCE(received_at, now()),
    updated_at = now()
FROM order_items oi
WHERE rr.order_item_id = oi.id
  AND rr.order_id = $1
  AND oi.seller_id = $2
  AND rr.status = 'approved'
RETURNING rr.id, rr.order_id, rr.order_item_id, rr.requested_by, rr.status, rr.reason, rr.quantity, rr.reviewed_by, rr.reviewed_at, rr.received_at, rr.metadata, rr.created_at, rr.updated_at
`

type MarkReturnReceivedForSellerParams struct {
	OrderID  pgtype.UUID `db:"order_id" json:"order_id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) MarkReturnReceivedForSeller(ctx context.Context, arg MarkReturnReceivedForSellerParams) (ReturnRequest, error) {
	row := q.db.QueryRow(ctx, markReturnReceivedForSeller, arg.OrderID, arg.SellerID)
	var i ReturnRequest
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrderItemID,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.Quantity,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReceivedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeCartVoucher = `-- name: RemoveCartVoucher :one
UPDATE carts SET voucher_id = NULL
WHERE id = $1 AND user_id = $2 AND voucher_id = $3
RETURNING id, user_id, session_id, created_at, updated_at, voucher_id
`

type RemoveCartVoucherParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	VoucherID pgtype.UUID `db:"voucher_id" json:"voucher_id"`
}

func (q *Queries) RemoveCartVoucher(ctx context.Context, arg RemoveCartVoucherParams) (Cart, error) {
	row := q.db.QueryRow(ctx, removeCartVoucher, arg.ID, arg.UserID, arg.VoucherID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const removeCheckoutVoucher = `-- name: RemoveCheckoutVoucher :one
UPDATE checkout_sessions
SET voucher_id = NULL,
    discount_cents = 0,
    total_cents = subtotal_cents + shipping_cents + tax_cents
WHERE id = $1 AND user_id = $2 AND voucher_id = $3 AND status = 'open'
RETURNING id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
`

type RemoveCheckoutVoucherParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	VoucherID pgtype.UUID `db:"voucher_id" json:"voucher_id"`
}

func (q *Queries) RemoveCheckoutVoucher(ctx context.Context, arg RemoveCheckoutVoucherParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, removeCheckoutVoucher, arg.ID, arg.UserID, arg.VoucherID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const reviewReturnForSeller = `-- name: ReviewReturnForSeller :one
UPDATE return_requests rr
SET status = $1,
    reviewed_by = $2,
    reviewed_at = now()
FROM order_items oi
WHERE rr.order_item_id = oi.id
  AND rr.order_id = $3
  AND oi.seller_id = $4
RETURNING rr.id, rr.order_id, rr.order_item_id, rr.requested_by, rr.status, rr.reason, rr.quantity, rr.reviewed_by, rr.reviewed_at, rr.received_at, rr.metadata, rr.created_at, rr.updated_at
`

type ReviewReturnForSellerParams struct {
	Status     interface{} `db:"status" json:"status"`
	ReviewedBy pgtype.UUID `db:"reviewed_by" json:"reviewed_by"`
	OrderID    pgtype.UUID `db:"order_id" json:"order_id"`
	SellerID   pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) ReviewReturnForSeller(ctx context.Context, arg ReviewReturnForSellerParams) (ReturnRequest, error) {
	row := q.db.QueryRow(ctx, reviewReturnForSeller,
		arg.Status,
		arg.ReviewedBy,
		arg.OrderID,
		arg.SellerID,
	)
	var i ReturnRequest
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrderItemID,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.Quantity,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReceivedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectCartItems = `-- name: SelectCartItems :exec
UPDATE cart_items SET selected = TRUE
WHERE cart_id = $1 AND id = ANY($2::uuid[])
`

type SelectCartItemsParams struct {
	CartID  pgtype.UUID   `db:"cart_id" json:"cart_id"`
	Column2 []pgtype.UUID `db:"column_2" json:"column_2"`
}

func (q *Queries) SelectCartItems(ctx context.Context, arg SelectCartItemsParams) error {
	_, err := q.db.Exec(ctx, selectCartItems, arg.CartID, arg.Column2)
	return err
}

const setAllCartItemsSelected = `-- name: SetAllCartItemsSelected :exec
UPDATE cart_items SET selected = $2
WHERE cart_id = $1
`

type SetAllCartItemsSelectedParams struct {
	CartID   pgtype.UUID `db:"cart_id" json:"cart_id"`
	Selected bool        `db:"selected" json:"selected"`
}

func (q *Queries) SetAllCartItemsSelected(ctx context.Context, arg SetAllCartItemsSelectedParams) error {
	_, err := q.db.Exec(ctx, setAllCartItemsSelected, arg.CartID, arg.Selected)
	return err
}

const setDefaultAddress = `-- name: SetDefaultAddress :one
UPDATE user_addresses SET is_default = TRUE
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, full_name, phone, country, state, city, district, postal_code, address_line1, address_line2, latitude, longitude, is_default, deleted_at, created_at, updated_at
`

type SetDefaultAddressParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, setDefaultAddress, arg.ID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Country,
		&i.State,
		&i.City,
		&i.District,
		&i.PostalCode,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items ci
SET quantity = $1
FROM carts c
WHERE ci.cart_id = c.id
  AND ci.id = $2
  AND c.user_id = $3
RETURNING ci.id, ci.cart_id, ci.product_id, ci.variant_id, ci.quantity, ci.created_at, ci.updated_at, ci.selected
`

type UpdateCartItemQuantityParams struct {
	Quantity int32       `db:"quantity" json:"quantity"`
	ID       pgtype.UUID `db:"id" json:"id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.Quantity, arg.ID, arg.UserID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Selected,
	)
	return i, err
}

const updateCheckoutAddress = `-- name: UpdateCheckoutAddress :one
UPDATE checkout_sessions
SET shipping_address = COALESCE($1::jsonb, shipping_address),
    billing_address = COALESCE($2::jsonb, billing_address)
WHERE id = $3 AND user_id = $4 AND status = 'open'
RETURNING id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
`

type UpdateCheckoutAddressParams struct {
	ShippingAddress []byte      `db:"shipping_address" json:"shipping_address"`
	BillingAddress  []byte      `db:"billing_address" json:"billing_address"`
	ID              pgtype.UUID `db:"id" json:"id"`
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateCheckoutAddress(ctx context.Context, arg UpdateCheckoutAddressParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, updateCheckoutAddress,
		arg.ShippingAddress,
		arg.BillingAddress,
		arg.ID,
		arg.UserID,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const updateCheckoutPaymentMethod = `-- name: UpdateCheckoutPaymentMethod :one
UPDATE checkout_sessions
SET payment_method = $1
WHERE id = $2 AND user_id = $3 AND status = 'open'
RETURNING id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
`

type UpdateCheckoutPaymentMethodParams struct {
	PaymentMethod pgtype.Text `db:"payment_method" json:"payment_method"`
	ID            pgtype.UUID `db:"id" json:"id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateCheckoutPaymentMethod(ctx context.Context, arg UpdateCheckoutPaymentMethodParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, updateCheckoutPaymentMethod, arg.PaymentMethod, arg.ID, arg.UserID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const updateCheckoutShipping = `-- name: UpdateCheckoutShipping :one
UPDATE checkout_sessions
SET selected_shipping_option = $1,
    shipping_cents = $2,
    total_cents = GREATEST(subtotal_cents - discount_cents + $2 + tax_cents, 0)
WHERE id = $3 AND user_id = $4 AND status = 'open'
RETURNING id, user_id, cart_id, status, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, shipping_address, billing_address, payment_method, selected_shipping_option, expires_at, completed_at, created_at, updated_at, voucher_id
`

type UpdateCheckoutShippingParams struct {
	SelectedShippingOption []byte      `db:"selected_shipping_option" json:"selected_shipping_option"`
	ShippingCents          int64       `db:"shipping_cents" json:"shipping_cents"`
	ID                     pgtype.UUID `db:"id" json:"id"`
	UserID                 pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateCheckoutShipping(ctx context.Context, arg UpdateCheckoutShippingParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, updateCheckoutShipping,
		arg.SelectedShippingOption,
		arg.ShippingCents,
		arg.ID,
		arg.UserID,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PaymentMethod,
		&i.SelectedShippingOption,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoucherID,
	)
	return i, err
}

const updateInventoryReserved = `-- name: UpdateInventoryReserved :one
UPDATE inventory_items
SET quantity_reserved = quantity_reserved + $1
WHERE id = $2
  AND quantity_reserved + $1 >= 0
  AND quantity_reserved + $1 <= quantity_available
RETURNING id, product_id, variant_id, quantity_available, quantity_reserved, low_stock_threshold, created_at, updated_at
`

type UpdateInventoryReservedParams struct {
	DeltaReserved int32       `db:"delta_reserved" json:"delta_reserved"`
	ID            pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateInventoryReserved(ctx context.Context, arg UpdateInventoryReservedParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, updateInventoryReserved, arg.DeltaReserved, arg.ID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.QuantityAvailable,
		&i.QuantityReserved,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1,
    paid_at = CASE WHEN $1 = 'paid' THEN COALESCE(paid_at, now()) ELSE paid_at END,
    cancelled_at = CASE WHEN $1 = 'cancelled' THEN COALESCE(cancelled_at, now()) ELSE cancelled_at END,
    completed_at = CASE WHEN $1 = 'completed' THEN COALESCE(completed_at, now()) ELSE completed_at END
WHERE id = $2
RETURNING id, order_number, user_id, checkout_session_id, status, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, currency, shipping_address, billing_address, placed_at, paid_at, cancelled_at, completed_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	Status interface{} `db:"status" json:"status"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.CheckoutSessionID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Currency,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSellerOrderItemsStatus = `-- name: UpdateSellerOrderItemsStatus :exec
UPDATE order_items SET status = $3
WHERE order_id = $1 AND seller_id = $2
`

type UpdateSellerOrderItemsStatusParams struct {
	OrderID  pgtype.UUID `db:"order_id" json:"order_id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Status   interface{} `db:"status" json:"status"`
}

func (q *Queries) UpdateSellerOrderItemsStatus(ctx context.Context, arg UpdateSellerOrderItemsStatusParams) error {
	_, err := q.db.Exec(ctx, updateSellerOrderItemsStatus, arg.OrderID, arg.SellerID, arg.Status)
	return err
}

const updateShipmentForSeller = `-- name: UpdateShipmentForSeller :one
UPDATE shipments
SET status = $1,
    tracking_number = COALESCE($2::text, tracking_number),
    shipped_at = CASE WHEN $1 IN ('shipped', 'in_transit') THEN COALESCE(shipped_at, now()) ELSE shipped_at END,
    delivered_at = CASE WHEN $1 = 'delivered' THEN COALESCE(delivered_at, now()) ELSE delivered_at END
WHERE order_id = $3 AND seller_id = $4
RETURNING id, order_id, seller_id, provider_id, tracking_number, label_url, provider_metadata, status, shipped_at, delivered_at, created_at, updated_at
`

type UpdateShipmentForSellerParams struct {
	Status         interface{} `db:"status" json:"status"`
	TrackingNumber pgtype.Text `db:"tracking_number" json:"tracking_number"`
	OrderID        pgtype.UUID `db:"order_id" json:"order_id"`
	SellerID       pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) UpdateShipmentForSeller(ctx context.Context, arg UpdateShipmentForSellerParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, updateShipmentForSeller,
		arg.Status,
		arg.TrackingNumber,
		arg.OrderID,
		arg.SellerID,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.ProviderID,
		&i.TrackingNumber,
		&i.LabelUrl,
		&i.ProviderMetadata,
		&i.Status,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAddress = `-- name: UpdateUserAddress :one
UPDATE user_addresses
SET full_name = COALESCE($1::text, full_name),
    phone = COALESCE($2::text, phone),
    country = COALESCE($3::text, country),
    state = COALESCE($4::text, state),
    city = COALESCE($5::text, city),
    district = COALESCE($6::text, district),
    postal_code = COALESCE($7::text, postal_code),
    address_line1 = COALESCE($8::text, address_line1),
    address_line2 = COALESCE($9::text, address_line2)
WHERE id = $10 AND user_id = $11 AND deleted_at IS NULL
RETURNING id, user_id, full_name, phone, country, state, city, district, postal_code, address_line1, address_line2, latitude, longitude, is_default, deleted_at, created_at, updated_at
`

type UpdateUserAddressParams struct {
	FullName     pgtype.Text `db:"full_name" json:"full_name"`
	Phone        pgtype.Text `db:"phone" json:"phone"`
	Country      pgtype.Text `db:"country" json:"country"`
	State        pgtype.Text `db:"state" json:"state"`
	City         pgtype.Text `db:"city" json:"city"`
	District     pgtype.Text `db:"district" json:"district"`
	PostalCode   pgtype.Text `db:"postal_code" json:"postal_code"`
	AddressLine1 pgtype.Text `db:"address_line1" json:"address_line1"`
	AddressLine2 pgtype.Text `db:"address_line2" json:"address_line2"`
	ID           pgtype.UUID `db:"id" json:"id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, updateUserAddress,
		arg.FullName,
		arg.Phone,
		arg.Country,
		arg.State,
		arg.City,
		arg.District,
		arg.PostalCode,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.ID,
		arg.UserID,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Country,
		&i.State,
		&i.City,
		&i.District,
		&i.PostalCode,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (cart_id, product_id, variant_id, quantity, selected)
VALUES ($1, $2, $3, $4, TRUE)
ON CONFLICT (cart_id, variant_id) DO UPDATE
SET quantity = cart_items.quantity + EXCLUDED.quantity,
    selected = TRUE
RETURNING id, cart_id, product_id, variant_id, quantity, created_at, updated_at, selected
`

type UpsertCartItemParams struct {
	CartID    pgtype.UUID `db:"cart_id" json:"cart_id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	VariantID pgtype.UUID `db:"variant_id" json:"variant_id"`
	Quantity  int32       `db:"quantity" json:"quantity"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartID,
		arg.ProductID,
		arg.VariantID,
		arg.Quantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Selected,
	)
	return i, err
}
