// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package orderstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApplyCartVoucher(ctx context.Context, arg ApplyCartVoucherParams) (Cart, error)
	ApplyCheckoutVoucher(ctx context.Context, arg ApplyCheckoutVoucherParams) (CheckoutSession, error)
	AttachReservationToOrder(ctx context.Context, arg AttachReservationToOrderParams) (InventoryReservation, error)
	ClearCart(ctx context.Context, cartID pgtype.UUID) error
	ClearDefaultAddress(ctx context.Context, userID pgtype.UUID) error
	CompleteCheckoutSession(ctx context.Context, arg CompleteCheckoutSessionParams) (CheckoutSession, error)
	ConsumeInventoryReservation(ctx context.Context, arg ConsumeInventoryReservationParams) (InventoryItem, error)
	CountDeliveredShipmentsForOrderSeller(ctx context.Context, arg CountDeliveredShipmentsForOrderSellerParams) (int64, error)
	CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error)
	CreateCheckoutSessionItem(ctx context.Context, arg CreateCheckoutSessionItemParams) (CheckoutSessionItem, error)
	CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error)
	CreateInventoryReservation(ctx context.Context, arg CreateInventoryReservationParams) (InventoryReservation, error)
	CreateOrGetOrderInvoice(ctx context.Context, arg CreateOrGetOrderInvoiceParams) (OrderInvoice, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItemFromCheckoutItem(ctx context.Context, arg CreateOrderItemFromCheckoutItemParams) (OrderItem, error)
	CreateRefundRequest(ctx context.Context, arg CreateRefundRequestParams) (Refund, error)
	CreateReturnRequest(ctx context.Context, arg CreateReturnRequestParams) (ReturnRequest, error)
	CreateShipmentsForOrderSellers(ctx context.Context, orderID pgtype.UUID) ([]Shipment, error)
	CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error)
	CreateVoucherRedemption(ctx context.Context, arg CreateVoucherRedemptionParams) (VoucherRedemption, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) error
	GetActiveVariantForCart(ctx context.Context, id pgtype.UUID) (GetActiveVariantForCartRow, error)
	GetActiveVoucherByCode(ctx context.Context, upper interface{}) (Voucher, error)
	GetCartForUser(ctx context.Context, userID pgtype.UUID) (Cart, error)
	GetCartItemForUser(ctx context.Context, arg GetCartItemForUserParams) (CartItem, error)
	GetCheckoutSession(ctx context.Context, id pgtype.UUID) (CheckoutSession, error)
	GetCheckoutSessionForUser(ctx context.Context, arg GetCheckoutSessionForUserParams) (CheckoutSession, error)
	GetOrCreateCart(ctx context.Context, arg GetOrCreateCartParams) (Cart, error)
	GetOrderAndSellerForOrderItemForUser(ctx context.Context, arg GetOrderAndSellerForOrderItemForUserParams) (GetOrderAndSellerForOrderItemForUserRow, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderForUser(ctx context.Context, arg GetOrderForUserParams) (Order, error)
	GetOrderIDForOrderItemForUser(ctx context.Context, arg GetOrderIDForOrderItemForUserParams) (pgtype.UUID, error)
	GetOrderInvoiceForUser(ctx context.Context, arg GetOrderInvoiceForUserParams) (OrderInvoice, error)
	GetSellerByUserID(ctx context.Context, userID pgtype.UUID) (Seller, error)
	GetSellerOrder(ctx context.Context, arg GetSellerOrderParams) (Order, error)
	GetUserAddress(ctx context.Context, arg GetUserAddressParams) (UserAddress, error)
	GetVoucherByID(ctx context.Context, id pgtype.UUID) (Voucher, error)
	IncrementVoucherUsage(ctx context.Context, id pgtype.UUID) error
	InsertOrderStatusHistory(ctx context.Context, arg InsertOrderStatusHistoryParams) (OrderStatusHistory, error)
	ListAdminOrders(ctx context.Context, arg ListAdminOrdersParams) ([]Order, error)
	ListCartItemsDetailed(ctx context.Context, cartID pgtype.UUID) ([]ListCartItemsDetailedRow, error)
	ListCheckoutSessionItems(ctx context.Context, checkoutSessionID pgtype.UUID) ([]CheckoutSessionItem, error)
	ListExpiredReservations(ctx context.Context, limit int32) ([]InventoryReservation, error)
	ListOrderCreditsBySeller(ctx context.Context, orderID pgtype.UUID) ([]ListOrderCreditsBySellerRow, error)
	ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error)
	ListOrderStatusHistory(ctx context.Context, orderID pgtype.UUID) ([]OrderStatusHistory, error)
	ListPaymentsForOrder(ctx context.Context, orderID pgtype.UUID) ([]Payment, error)
	ListReservationsForCheckout(ctx context.Context, checkoutSessionID pgtype.UUID) ([]InventoryReservation, error)
	ListReservationsForOrder(ctx context.Context, orderID pgtype.UUID) ([]InventoryReservation, error)
	ListSellerOrderItems(ctx context.Context, arg ListSellerOrderItemsParams) ([]OrderItem, error)
	ListSellerOrders(ctx context.Context, arg ListSellerOrdersParams) ([]Order, error)
	ListShipmentsForOrder(ctx context.Context, orderID pgtype.UUID) ([]Shipment, error)
	ListStaleUnpaidOrders(ctx context.Context, arg ListStaleUnpaidOrdersParams) ([]Order, error)
	ListTrackingEventsForOrder(ctx context.Context, orderID pgtype.UUID) ([]ShipmentTrackingEvent, error)
	ListUserAddresses(ctx context.Context, userID pgtype.UUID) ([]UserAddress, error)
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error)
	LockCheckoutSessionForUser(ctx context.Context, arg LockCheckoutSessionForUserParams) (CheckoutSession, error)
	LockInventoryByID(ctx context.Context, id pgtype.UUID) (InventoryItem, error)
	LockInventoryByVariant(ctx context.Context, variantID pgtype.UUID) (InventoryItem, error)
	MarkReservationReleased(ctx context.Context, id pgtype.UUID) (InventoryReservation, error)
	MarkReturnReceivedForSeller(ctx context.Context, arg MarkReturnReceivedForSellerParams) (ReturnRequest, error)
	RemoveCartVoucher(ctx context.Context, arg RemoveCartVoucherParams) (Cart, error)
	RemoveCheckoutVoucher(ctx context.Context, arg RemoveCheckoutVoucherParams) (CheckoutSession, error)
	ReviewReturnForSeller(ctx context.Context, arg ReviewReturnForSellerParams) (ReturnRequest, error)
	SelectCartItems(ctx context.Context, arg SelectCartItemsParams) error
	SetAllCartItemsSelected(ctx context.Context, arg SetAllCartItemsSelectedParams) error
	SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (UserAddress, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateCheckoutAddress(ctx context.Context, arg UpdateCheckoutAddressParams) (CheckoutSession, error)
	UpdateCheckoutPaymentMethod(ctx context.Context, arg UpdateCheckoutPaymentMethodParams) (CheckoutSession, error)
	UpdateCheckoutShipping(ctx context.Context, arg UpdateCheckoutShippingParams) (CheckoutSession, error)
	UpdateInventoryReserved(ctx context.Context, arg UpdateInventoryReservedParams) (InventoryItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateSellerOrderItemsStatus(ctx context.Context, arg UpdateSellerOrderItemsStatusParams) error
	UpdateShipmentForSeller(ctx context.Context, arg UpdateShipmentForSellerParams) (Shipment, error)
	UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error)
	UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error)
}

var _ Querier = (*Queries)(nil)
