// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package chatstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBuyerConversations = `-- name: CountBuyerConversations :one
SELECT count(*)::bigint FROM chat_conversations WHERE buyer_id = $1
`

func (q *Queries) CountBuyerConversations(ctx context.Context, buyerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBuyerConversations, buyerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSellerConversations = `-- name: CountSellerConversations :one
SELECT count(*)::bigint FROM chat_conversations WHERE seller_id = $1
`

func (q *Queries) CountSellerConversations(ctx context.Context, sellerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerConversations, sellerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_messages (conversation_id, sender_user_id, message, attachment_url)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_user_id, message, attachment_url, read_at, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `db:"conversation_id" json:"conversation_id"`
	SenderUserID   pgtype.UUID `db:"sender_user_id" json:"sender_user_id"`
	Message        pgtype.Text `db:"message" json:"message"`
	AttachmentUrl  pgtype.Text `db:"attachment_url" json:"attachment_url"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderUserID,
		arg.Message,
		arg.AttachmentUrl,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.Message,
		&i.AttachmentUrl,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversationForUser = `-- name: DeleteConversationForUser :execrows
DELETE FROM chat_conversations
WHERE chat_conversations.id = $1
  AND chat_conversations.id IN (
    SELECT c.id
    FROM chat_conversations c
    JOIN sellers s ON s.id = c.seller_id
    WHERE c.id = $1
      AND (c.buyer_id = $2 OR s.user_id = $2)
  )
`

type DeleteConversationForUserParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	BuyerID pgtype.UUID `db:"buyer_id" json:"buyer_id"`
}

func (q *Queries) DeleteConversationForUser(ctx context.Context, arg DeleteConversationForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversationForUser, arg.ID, arg.BuyerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMessageForUser = `-- name: DeleteMessageForUser :execrows
DELETE FROM chat_messages
WHERE chat_messages.id = $1
  AND conversation_id IN (
    SELECT c.id
    FROM chat_conversations c
    JOIN sellers s ON s.id = c.seller_id
    WHERE c.id = $2
      AND (c.buyer_id = $3 OR s.user_id = $3)
  )
`

type DeleteMessageForUserParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	ID_2    pgtype.UUID `db:"id_2" json:"id_2"`
	BuyerID pgtype.UUID `db:"buyer_id" json:"buyer_id"`
}

func (q *Queries) DeleteMessageForUser(ctx context.Context, arg DeleteMessageForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessageForUser, arg.ID, arg.ID_2, arg.BuyerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversationForUser = `-- name: GetConversationForUser :one
SELECT c.id, c.buyer_id, c.seller_id, s.user_id AS seller_user_id
FROM chat_conversations c
JOIN sellers s ON s.id = c.seller_id
WHERE c.id = $1
  AND (c.buyer_id = $2 OR s.user_id = $2)
`

type GetConversationForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type GetConversationForUserRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	BuyerID      pgtype.UUID `db:"buyer_id" json:"buyer_id"`
	SellerID     pgtype.UUID `db:"seller_id" json:"seller_id"`
	SellerUserID pgtype.UUID `db:"seller_user_id" json:"seller_user_id"`
}

func (q *Queries) GetConversationForUser(ctx context.Context, arg GetConversationForUserParams) (GetConversationForUserRow, error) {
	row := q.db.QueryRow(ctx, getConversationForUser, arg.ID, arg.UserID)
	var i GetConversationForUserRow
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.SellerUserID,
	)
	return i, err
}

const getConversationWithSellerUser = `-- name: GetConversationWithSellerUser :one
SELECT c.id, c.buyer_id, c.seller_id, s.user_id AS seller_user_id
FROM chat_conversations c
JOIN sellers s ON s.id = c.seller_id
WHERE c.id = $1
`

type GetConversationWithSellerUserRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	BuyerID      pgtype.UUID `db:"buyer_id" json:"buyer_id"`
	SellerID     pgtype.UUID `db:"seller_id" json:"seller_id"`
	SellerUserID pgtype.UUID `db:"seller_user_id" json:"seller_user_id"`
}

func (q *Queries) GetConversationWithSellerUser(ctx context.Context, id pgtype.UUID) (GetConversationWithSellerUserRow, error) {
	row := q.db.QueryRow(ctx, getConversationWithSellerUser, id)
	var i GetConversationWithSellerUserRow
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.SellerUserID,
	)
	return i, err
}

const getOrCreateConversation = `-- name: GetOrCreateConversation :one
INSERT INTO chat_conversations (buyer_id, seller_id)
VALUES ($1, $2)
ON CONFLICT (buyer_id, seller_id)
DO UPDATE SET buyer_id = EXCLUDED.buyer_id
RETURNING id, buyer_id, seller_id, last_message_at, created_at
`

type GetOrCreateConversationParams struct {
	BuyerID  pgtype.UUID `db:"buyer_id" json:"buyer_id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) GetOrCreateConversation(ctx context.Context, arg GetOrCreateConversationParams) (ChatConversation, error) {
	row := q.db.QueryRow(ctx, getOrCreateConversation, arg.BuyerID, arg.SellerID)
	var i ChatConversation
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.LastMessageAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBuyerConversations = `-- name: ListBuyerConversations :many
SELECT c.id, c.buyer_id, c.seller_id, c.last_message_at, c.created_at,
       s.shop_name, s.slug, s.logo_url,
       (
         SELECT count(*)::bigint
         FROM chat_messages m
         JOIN sellers s2 ON s2.id = c.seller_id
         WHERE m.conversation_id = c.id
           AND m.sender_user_id = s2.user_id
           AND m.read_at IS NULL
       ) AS unread_count
FROM chat_conversations c
JOIN sellers s ON s.id = c.seller_id
WHERE c.buyer_id = $1
ORDER BY COALESCE(c.last_message_at, c.created_at) DESC
LIMIT $2 OFFSET $3
`

type ListBuyerConversationsParams struct {
	BuyerID pgtype.UUID `db:"buyer_id" json:"buyer_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListBuyerConversationsRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	BuyerID       pgtype.UUID        `db:"buyer_id" json:"buyer_id"`
	SellerID      pgtype.UUID        `db:"seller_id" json:"seller_id"`
	LastMessageAt pgtype.Timestamptz `db:"last_message_at" json:"last_message_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ShopName      string             `db:"shop_name" json:"shop_name"`
	Slug          string             `db:"slug" json:"slug"`
	LogoUrl       pgtype.Text        `db:"logo_url" json:"logo_url"`
	UnreadCount   int64              `db:"unread_count" json:"unread_count"`
}

func (q *Queries) ListBuyerConversations(ctx context.Context, arg ListBuyerConversationsParams) ([]ListBuyerConversationsRow, error) {
	rows, err := q.db.Query(ctx, listBuyerConversations, arg.BuyerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuyerConversationsRow
	for rows.Next() {
		var i ListBuyerConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.ShopName,
			&i.Slug,
			&i.LogoUrl,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_user_id, message, attachment_url, read_at, created_at
FROM chat_messages
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID `db:"conversation_id" json:"conversation_id"`
	Limit          int32       `db:"limit" json:"limit"`
	Offset         int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderUserID,
			&i.Message,
			&i.AttachmentUrl,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerConversations = `-- name: ListSellerConversations :many
SELECT c.id, c.buyer_id, c.seller_id, c.last_message_at, c.created_at,
       COALESCE(up.display_name, '') AS buyer_name, u.email AS buyer_email,
       (
         SELECT count(*)::bigint
         FROM chat_messages m
         WHERE m.conversation_id = c.id
           AND m.sender_user_id = c.buyer_id
           AND m.read_at IS NULL
       ) AS unread_count
FROM chat_conversations c
JOIN users u ON u.id = c.buyer_id
LEFT JOIN user_profiles up ON up.user_id = u.id
WHERE c.seller_id = $1
ORDER BY COALESCE(c.last_message_at, c.created_at) DESC
LIMIT $2 OFFSET $3
`

type ListSellerConversationsParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type ListSellerConversationsRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	BuyerID       pgtype.UUID        `db:"buyer_id" json:"buyer_id"`
	SellerID      pgtype.UUID        `db:"seller_id" json:"seller_id"`
	LastMessageAt pgtype.Timestamptz `db:"last_message_at" json:"last_message_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	BuyerName     string             `db:"buyer_name" json:"buyer_name"`
	BuyerEmail    pgtype.Text        `db:"buyer_email" json:"buyer_email"`
	UnreadCount   int64              `db:"unread_count" json:"unread_count"`
}

func (q *Queries) ListSellerConversations(ctx context.Context, arg ListSellerConversationsParams) ([]ListSellerConversationsRow, error) {
	rows, err := q.db.Query(ctx, listSellerConversations, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellerConversationsRow
	for rows.Next() {
		var i ListSellerConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.BuyerName,
			&i.BuyerEmail,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE chat_messages
SET read_at = now()
WHERE conversation_id = $1
  AND sender_user_id <> $2
  AND read_at IS NULL
`

type MarkConversationReadParams struct {
	ConversationID pgtype.UUID `db:"conversation_id" json:"conversation_id"`
	SenderUserID   pgtype.UUID `db:"sender_user_id" json:"sender_user_id"`
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.ConversationID, arg.SenderUserID)
	return err
}

const touchConversationLastMessageAt = `-- name: TouchConversationLastMessageAt :exec
UPDATE chat_conversations
SET last_message_at = now()
WHERE id = $1
`

func (q *Queries) TouchConversationLastMessageAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchConversationLastMessageAt, id)
	return err
}
