// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package chatstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountBuyerConversations(ctx context.Context, buyerID pgtype.UUID) (int64, error)
	CountSellerConversations(ctx context.Context, sellerID pgtype.UUID) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error)
	DeleteConversationForUser(ctx context.Context, arg DeleteConversationForUserParams) (int64, error)
	DeleteMessageForUser(ctx context.Context, arg DeleteMessageForUserParams) (int64, error)
	GetConversationForUser(ctx context.Context, arg GetConversationForUserParams) (GetConversationForUserRow, error)
	GetConversationWithSellerUser(ctx context.Context, id pgtype.UUID) (GetConversationWithSellerUserRow, error)
	GetOrCreateConversation(ctx context.Context, arg GetOrCreateConversationParams) (ChatConversation, error)
	ListBuyerConversations(ctx context.Context, arg ListBuyerConversationsParams) ([]ListBuyerConversationsRow, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ChatMessage, error)
	ListSellerConversations(ctx context.Context, arg ListSellerConversationsParams) ([]ListSellerConversationsRow, error)
	MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error
	TouchConversationLastMessageAt(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
