// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package systemstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminCountAdminActivityLogs(ctx context.Context, arg AdminCountAdminActivityLogsParams) (int64, error)
	AdminCountAuditLogs(ctx context.Context, arg AdminCountAuditLogsParams) (int64, error)
	AdminCountModerationCases(ctx context.Context, status interface{}) (int64, error)
	AdminCountModerationReports(ctx context.Context, arg AdminCountModerationReportsParams) (int64, error)
	AdminCreateModerationCase(ctx context.Context, arg AdminCreateModerationCaseParams) (ModerationCase, error)
	AdminDashboardOverview(ctx context.Context) (AdminDashboardOverviewRow, error)
	AdminGetModerationCaseByID(ctx context.Context, id pgtype.UUID) (ModerationCase, error)
	AdminGetModerationReportByID(ctx context.Context, id pgtype.UUID) (ModerationReport, error)
	AdminListAdminActivityLogs(ctx context.Context, arg AdminListAdminActivityLogsParams) ([]AdminActivityLog, error)
	AdminListAuditLogs(ctx context.Context, arg AdminListAuditLogsParams) ([]AuditLog, error)
	AdminListModerationCases(ctx context.Context, arg AdminListModerationCasesParams) ([]ModerationCase, error)
	AdminListModerationReports(ctx context.Context, arg AdminListModerationReportsParams) ([]ModerationReport, error)
	AdminUpdateModerationCase(ctx context.Context, arg AdminUpdateModerationCaseParams) (ModerationCase, error)
	AdminUpdateModerationReportStatus(ctx context.Context, arg AdminUpdateModerationReportStatusParams) (ModerationReport, error)
	AggregateEventLogDay(ctx context.Context, arg AggregateEventLogDayParams) (AggregateEventLogDayRow, error)
	CreateAdminActivityLog(ctx context.Context, arg CreateAdminActivityLogParams) (AdminActivityLog, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error)
	CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (ModerationReport, error)
	DequeueAnalyticsEvents(ctx context.Context, limit int32) ([]AnalyticsEventQueue, error)
	EnqueueAnalyticsEvent(ctx context.Context, eventLogID pgtype.UUID) error
	GetEventLogByID(ctx context.Context, id pgtype.UUID) (EventLog, error)
	GetPlatformSetting(ctx context.Context, key string) (PlatformSetting, error)
	ListAdminMetricsDaily(ctx context.Context, arg ListAdminMetricsDailyParams) ([]AdminMetricsDaily, error)
	ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error)
	ListPlatformSettings(ctx context.Context) ([]PlatformSetting, error)
	MarkAnalyticsEventFailed(ctx context.Context, arg MarkAnalyticsEventFailedParams) error
	MarkAnalyticsEventProcessed(ctx context.Context, id pgtype.UUID) error
	UpsertAdminMetricDaily(ctx context.Context, arg UpsertAdminMetricDailyParams) error
	UpsertFeatureFlag(ctx context.Context, arg UpsertFeatureFlagParams) (FeatureFlag, error)
	UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) (PlatformSetting, error)
}

var _ Querier = (*Queries)(nil)
