// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package systemstore

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountAdminActivityLogs = `-- name: AdminCountAdminActivityLogs :one
SELECT COUNT(1)::bigint
FROM admin_activity_logs aal
WHERE ($1::uuid IS NULL OR aal.admin_user_id = $1::uuid)
  AND ($2::text IS NULL OR aal.action = $2::text)
  AND ($3::text IS NULL OR aal.entity_type = $3::text)
  AND ($4::timestamptz IS NULL OR aal.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR aal.created_at <= $5::timestamptz)
`

type AdminCountAdminActivityLogsParams struct {
	AdminUserID pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	Action      pgtype.Text        `db:"action" json:"action"`
	EntityType  pgtype.Text        `db:"entity_type" json:"entity_type"`
	FromTime    pgtype.Timestamptz `db:"from_time" json:"from_time"`
	ToTime      pgtype.Timestamptz `db:"to_time" json:"to_time"`
}

func (q *Queries) AdminCountAdminActivityLogs(ctx context.Context, arg AdminCountAdminActivityLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAdminActivityLogs,
		arg.AdminUserID,
		arg.Action,
		arg.EntityType,
		arg.FromTime,
		arg.ToTime,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountAuditLogs = `-- name: AdminCountAuditLogs :one
SELECT COUNT(1)::bigint
FROM audit_logs al
WHERE ($1::uuid IS NULL OR al.actor_user_id = $1::uuid)
  AND ($2::text IS NULL OR al.action = $2::text)
  AND ($3::text IS NULL OR al.entity_type = $3::text)
  AND ($4::timestamptz IS NULL OR al.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR al.created_at <= $5::timestamptz)
`

type AdminCountAuditLogsParams struct {
	ActorUserID pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	Action      pgtype.Text        `db:"action" json:"action"`
	EntityType  pgtype.Text        `db:"entity_type" json:"entity_type"`
	FromTime    pgtype.Timestamptz `db:"from_time" json:"from_time"`
	ToTime      pgtype.Timestamptz `db:"to_time" json:"to_time"`
}

func (q *Queries) AdminCountAuditLogs(ctx context.Context, arg AdminCountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAuditLogs,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.FromTime,
		arg.ToTime,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountModerationCases = `-- name: AdminCountModerationCases :one
SELECT COUNT(1)::bigint
FROM moderation_cases mc
WHERE ($1::moderation_status IS NULL OR mc.status = $1::moderation_status)
`

func (q *Queries) AdminCountModerationCases(ctx context.Context, status interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountModerationCases, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountModerationReports = `-- name: AdminCountModerationReports :one
SELECT COUNT(1)::bigint
FROM moderation_reports mr
WHERE ($1::moderation_status IS NULL OR mr.status = $1::moderation_status)
  AND ($2::text IS NULL OR mr.target_type = $2::text)
`

type AdminCountModerationReportsParams struct {
	Status     interface{} `db:"status" json:"status"`
	TargetType pgtype.Text `db:"target_type" json:"target_type"`
}

func (q *Queries) AdminCountModerationReports(ctx context.Context, arg AdminCountModerationReportsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountModerationReports, arg.Status, arg.TargetType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCreateModerationCase = `-- name: AdminCreateModerationCase :one
INSERT INTO moderation_cases (report_id, assigned_to, status, resolution, resolved_at)
VALUES (
  $1,
  $2,
  COALESCE($3::moderation_status, 'under_review'::moderation_status),
  $4,
  $5
)
RETURNING id, report_id, assigned_to, status, resolution, resolved_at, created_at, updated_at
`

type AdminCreateModerationCaseParams struct {
	ReportID   pgtype.UUID        `db:"report_id" json:"report_id"`
	AssignedTo pgtype.UUID        `db:"assigned_to" json:"assigned_to"`
	Status     interface{}        `db:"status" json:"status"`
	Resolution pgtype.Text        `db:"resolution" json:"resolution"`
	ResolvedAt pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
}

func (q *Queries) AdminCreateModerationCase(ctx context.Context, arg AdminCreateModerationCaseParams) (ModerationCase, error) {
	row := q.db.QueryRow(ctx, adminCreateModerationCase,
		arg.ReportID,
		arg.AssignedTo,
		arg.Status,
		arg.Resolution,
		arg.ResolvedAt,
	)
	var i ModerationCase
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AssignedTo,
		&i.Status,
		&i.Resolution,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDashboardOverview = `-- name: AdminDashboardOverview :one
SELECT
  (SELECT COUNT(1)::bigint FROM users u WHERE u.deleted_at IS NULL) AS users_total,
  (SELECT COUNT(1)::bigint FROM sellers s WHERE s.deleted_at IS NULL) AS sellers_total,
  (SELECT COUNT(1)::bigint FROM products p WHERE p.deleted_at IS NULL) AS products_total,
  (SELECT COUNT(1)::bigint FROM orders) AS orders_total,
  (SELECT COUNT(1)::bigint FROM payments) AS payments_total,
  (SELECT COUNT(1)::bigint FROM shipments) AS shipments_total
`

type AdminDashboardOverviewRow struct {
	UsersTotal     int64 `db:"users_total" json:"users_total"`
	SellersTotal   int64 `db:"sellers_total" json:"sellers_total"`
	ProductsTotal  int64 `db:"products_total" json:"products_total"`
	OrdersTotal    int64 `db:"orders_total" json:"orders_total"`
	PaymentsTotal  int64 `db:"payments_total" json:"payments_total"`
	ShipmentsTotal int64 `db:"shipments_total" json:"shipments_total"`
}

func (q *Queries) AdminDashboardOverview(ctx context.Context) (AdminDashboardOverviewRow, error) {
	row := q.db.QueryRow(ctx, adminDashboardOverview)
	var i AdminDashboardOverviewRow
	err := row.Scan(
		&i.UsersTotal,
		&i.SellersTotal,
		&i.ProductsTotal,
		&i.OrdersTotal,
		&i.PaymentsTotal,
		&i.ShipmentsTotal,
	)
	return i, err
}

const adminGetModerationCaseByID = `-- name: AdminGetModerationCaseByID :one
SELECT id, report_id, assigned_to, status, resolution, resolved_at, created_at, updated_at
FROM moderation_cases
WHERE id = $1
`

func (q *Queries) AdminGetModerationCaseByID(ctx context.Context, id pgtype.UUID) (ModerationCase, error) {
	row := q.db.QueryRow(ctx, adminGetModerationCaseByID, id)
	var i ModerationCase
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AssignedTo,
		&i.Status,
		&i.Resolution,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetModerationReportByID = `-- name: AdminGetModerationReportByID :one
SELECT id, reporter_user_id, target_type, target_id, reason, status, created_at
FROM moderation_reports
WHERE id = $1
`

func (q *Queries) AdminGetModerationReportByID(ctx context.Context, id pgtype.UUID) (ModerationReport, error) {
	row := q.db.QueryRow(ctx, adminGetModerationReportByID, id)
	var i ModerationReport
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const adminListAdminActivityLogs = `-- name: AdminListAdminActivityLogs :many
SELECT id, admin_user_id, action, entity_type, entity_id, metadata, ip_address, user_agent, created_at
FROM admin_activity_logs aal
WHERE ($1::uuid IS NULL OR aal.admin_user_id = $1::uuid)
  AND ($2::text IS NULL OR aal.action = $2::text)
  AND ($3::text IS NULL OR aal.entity_type = $3::text)
  AND ($4::timestamptz IS NULL OR aal.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR aal.created_at <= $5::timestamptz)
ORDER BY aal.created_at DESC
LIMIT $7 OFFSET $6
`

type AdminListAdminActivityLogsParams struct {
	AdminUserID pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	Action      pgtype.Text        `db:"action" json:"action"`
	EntityType  pgtype.Text        `db:"entity_type" json:"entity_type"`
	FromTime    pgtype.Timestamptz `db:"from_time" json:"from_time"`
	ToTime      pgtype.Timestamptz `db:"to_time" json:"to_time"`
	Offset      int32              `db:"offset" json:"offset"`
	Limit       int32              `db:"limit" json:"limit"`
}

func (q *Queries) AdminListAdminActivityLogs(ctx context.Context, arg AdminListAdminActivityLogsParams) ([]AdminActivityLog, error) {
	rows, err := q.db.Query(ctx, adminListAdminActivityLogs,
		arg.AdminUserID,
		arg.Action,
		arg.EntityType,
		arg.FromTime,
		arg.ToTime,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminActivityLog
	for rows.Next() {
		var i AdminActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAuditLogs = `-- name: AdminListAuditLogs :many
SELECT id, actor_user_id, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent, created_at
FROM audit_logs al
WHERE ($1::uuid IS NULL OR al.actor_user_id = $1::uuid)
  AND ($2::text IS NULL OR al.action = $2::text)
  AND ($3::text IS NULL OR al.entity_type = $3::text)
  AND ($4::timestamptz IS NULL OR al.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR al.created_at <= $5::timestamptz)
ORDER BY al.created_at DESC
LIMIT $7 OFFSET $6
`

type AdminListAuditLogsParams struct {
	ActorUserID pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	Action      pgtype.Text        `db:"action" json:"action"`
	EntityType  pgtype.Text        `db:"entity_type" json:"entity_type"`
	FromTime    pgtype.Timestamptz `db:"from_time" json:"from_time"`
	ToTime      pgtype.Timestamptz `db:"to_time" json:"to_time"`
	Offset      int32              `db:"offset" json:"offset"`
	Limit       int32              `db:"limit" json:"limit"`
}

func (q *Queries) AdminListAuditLogs(ctx context.Context, arg AdminListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, adminListAuditLogs,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.FromTime,
		arg.ToTime,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListModerationCases = `-- name: AdminListModerationCases :many
SELECT id, report_id, assigned_to, status, resolution, resolved_at, created_at, updated_at
FROM moderation_cases mc
WHERE ($1::moderation_status IS NULL OR mc.status = $1::moderation_status)
ORDER BY mc.updated_at DESC
LIMIT $3 OFFSET $2
`

type AdminListModerationCasesParams struct {
	Status interface{} `db:"status" json:"status"`
	Offset int32       `db:"offset" json:"offset"`
	Limit  int32       `db:"limit" json:"limit"`
}

func (q *Queries) AdminListModerationCases(ctx context.Context, arg AdminListModerationCasesParams) ([]ModerationCase, error) {
	rows, err := q.db.Query(ctx, adminListModerationCases, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationCase
	for rows.Next() {
		var i ModerationCase
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.AssignedTo,
			&i.Status,
			&i.Resolution,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListModerationReports = `-- name: AdminListModerationReports :many
SELECT id, reporter_user_id, target_type, target_id, reason, status, created_at
FROM moderation_reports mr
WHERE ($1::moderation_status IS NULL OR mr.status = $1::moderation_status)
  AND ($2::text IS NULL OR mr.target_type = $2::text)
ORDER BY mr.created_at DESC
LIMIT $4 OFFSET $3
`

type AdminListModerationReportsParams struct {
	Status     interface{} `db:"status" json:"status"`
	TargetType pgtype.Text `db:"target_type" json:"target_type"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) AdminListModerationReports(ctx context.Context, arg AdminListModerationReportsParams) ([]ModerationReport, error) {
	rows, err := q.db.Query(ctx, adminListModerationReports,
		arg.Status,
		arg.TargetType,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationReport
	for rows.Next() {
		var i ModerationReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterUserID,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateModerationCase = `-- name: AdminUpdateModerationCase :one
UPDATE moderation_cases
SET assigned_to = COALESCE($1::uuid, assigned_to),
    status = COALESCE($2::moderation_status, status),
    resolution = COALESCE($3::text, resolution),
    resolved_at = CASE
      WHEN $4::timestamptz IS NOT NULL THEN $4::timestamptz
      WHEN $2::moderation_status IN ('resolved', 'dismissed') THEN now()
      ELSE resolved_at
    END
WHERE id = $5
RETURNING id, report_id, assigned_to, status, resolution, resolved_at, created_at, updated_at
`

type AdminUpdateModerationCaseParams struct {
	AssignedTo pgtype.UUID        `db:"assigned_to" json:"assigned_to"`
	Status     interface{}        `db:"status" json:"status"`
	Resolution pgtype.Text        `db:"resolution" json:"resolution"`
	ResolvedAt pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	ID         pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) AdminUpdateModerationCase(ctx context.Context, arg AdminUpdateModerationCaseParams) (ModerationCase, error) {
	row := q.db.QueryRow(ctx, adminUpdateModerationCase,
		arg.AssignedTo,
		arg.Status,
		arg.Resolution,
		arg.ResolvedAt,
		arg.ID,
	)
	var i ModerationCase
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AssignedTo,
		&i.Status,
		&i.Resolution,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpdateModerationReportStatus = `-- name: AdminUpdateModerationReportStatus :one
UPDATE moderation_reports
SET status = $1::moderation_status
WHERE id = $2
RETURNING id, reporter_user_id, target_type, target_id, reason, status, created_at
`

type AdminUpdateModerationReportStatusParams struct {
	Status interface{} `db:"status" json:"status"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) AdminUpdateModerationReportStatus(ctx context.Context, arg AdminUpdateModerationReportStatusParams) (ModerationReport, error) {
	row := q.db.QueryRow(ctx, adminUpdateModerationReportStatus, arg.Status, arg.ID)
	var i ModerationReport
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const aggregateEventLogDay = `-- name: AggregateEventLogDay :one
SELECT
  COUNT(1)::bigint AS total_count,
  COUNT(DISTINCT user_id)::bigint AS unique_users
FROM event_logs
WHERE event_name = $1
  AND created_at >= date_trunc('day', $2::timestamptz)
  AND created_at < date_trunc('day', $2::timestamptz) + interval '1 day'
`

type AggregateEventLogDayParams struct {
	EventName string             `db:"event_name" json:"event_name"`
	Day       pgtype.Timestamptz `db:"day" json:"day"`
}

type AggregateEventLogDayRow struct {
	TotalCount  int64 `db:"total_count" json:"total_count"`
	UniqueUsers int64 `db:"unique_users" json:"unique_users"`
}

func (q *Queries) AggregateEventLogDay(ctx context.Context, arg AggregateEventLogDayParams) (AggregateEventLogDayRow, error) {
	row := q.db.QueryRow(ctx, aggregateEventLogDay, arg.EventName, arg.Day)
	var i AggregateEventLogDayRow
	err := row.Scan(&i.TotalCount, &i.UniqueUsers)
	return i, err
}

const createAdminActivityLog = `-- name: CreateAdminActivityLog :one
INSERT INTO admin_activity_logs (admin_user_id, action, entity_type, entity_id, metadata, ip_address, user_agent)
VALUES ($1, $2, $3, $4, COALESCE($5::jsonb, '{}'::jsonb), $6, $7)
RETURNING id, admin_user_id, action, entity_type, entity_id, metadata, ip_address, user_agent, created_at
`

type CreateAdminActivityLogParams struct {
	AdminUserID pgtype.UUID `db:"admin_user_id" json:"admin_user_id"`
	Action      string      `db:"action" json:"action"`
	EntityType  pgtype.Text `db:"entity_type" json:"entity_type"`
	EntityID    pgtype.UUID `db:"entity_id" json:"entity_id"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
	IpAddress   *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent   pgtype.Text `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CreateAdminActivityLog(ctx context.Context, arg CreateAdminActivityLogParams) (AdminActivityLog, error) {
	row := q.db.QueryRow(ctx, createAdminActivityLog,
		arg.AdminUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AdminActivityLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_user_id, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, actor_user_id, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	ActorUserID pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	Action      string      `db:"action" json:"action"`
	EntityType  pgtype.Text `db:"entity_type" json:"entity_type"`
	EntityID    pgtype.UUID `db:"entity_id" json:"entity_id"`
	OldValues   []byte      `db:"old_values" json:"old_values"`
	NewValues   []byte      `db:"new_values" json:"new_values"`
	IpAddress   *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent   pgtype.Text `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.OldValues,
		&i.NewValues,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createEventLog = `-- name: CreateEventLog :one
INSERT INTO event_logs (user_id, event_name, entity_type, entity_id, metadata, ip_address)
VALUES (
  $1,
  $2,
  $3,
  $4,
  COALESCE($5::jsonb, '{}'::jsonb),
  $6
)
RETURNING id, user_id, event_name, entity_type, entity_id, metadata, ip_address, created_at
`

type CreateEventLogParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	EventName  string      `db:"event_name" json:"event_name"`
	EntityType pgtype.Text `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
	Metadata   []byte      `db:"metadata" json:"metadata"`
	IpAddress  *netip.Addr `db:"ip_address" json:"ip_address"`
}

func (q *Queries) CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, createEventLog,
		arg.UserID,
		arg.EventName,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
		arg.IpAddress,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventName,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const createModerationReport = `-- name: CreateModerationReport :one
INSERT INTO moderation_reports (reporter_user_id, target_type, target_id, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, reporter_user_id, target_type, target_id, reason, status, created_at
`

type CreateModerationReportParams struct {
	ReporterUserID pgtype.UUID `db:"reporter_user_id" json:"reporter_user_id"`
	TargetType     string      `db:"target_type" json:"target_type"`
	TargetID       pgtype.UUID `db:"target_id" json:"target_id"`
	Reason         string      `db:"reason" json:"reason"`
}

func (q *Queries) CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (ModerationReport, error) {
	row := q.db.QueryRow(ctx, createModerationReport,
		arg.ReporterUserID,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
	)
	var i ModerationReport
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const dequeueAnalyticsEvents = `-- name: DequeueAnalyticsEvents :many
WITH picked AS (
  SELECT q.id
  FROM analytics_event_queue q
  WHERE q.status = 'pending'
    AND q.available_at <= now()
  ORDER BY q.created_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE analytics_event_queue q
SET status = 'processing',
    attempts = q.attempts + 1,
    updated_at = now()
FROM picked
WHERE q.id = picked.id
RETURNING q.id, q.event_log_id, q.status, q.attempts, q.last_error, q.available_at, q.processed_at, q.created_at, q.updated_at
`

func (q *Queries) DequeueAnalyticsEvents(ctx context.Context, limit int32) ([]AnalyticsEventQueue, error) {
	rows, err := q.db.Query(ctx, dequeueAnalyticsEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsEventQueue
	for rows.Next() {
		var i AnalyticsEventQueue
		if err := rows.Scan(
			&i.ID,
			&i.EventLogID,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.AvailableAt,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueAnalyticsEvent = `-- name: EnqueueAnalyticsEvent :exec
INSERT INTO analytics_event_queue (event_log_id)
VALUES ($1)
ON CONFLICT (event_log_id) DO NOTHING
`

func (q *Queries) EnqueueAnalyticsEvent(ctx context.Context, eventLogID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, enqueueAnalyticsEvent, eventLogID)
	return err
}

const getEventLogByID = `-- name: GetEventLogByID :one
SELECT id, user_id, event_name, entity_type, entity_id, metadata, ip_address, created_at
FROM event_logs
WHERE id = $1
`

func (q *Queries) GetEventLogByID(ctx context.Context, id pgtype.UUID) (EventLog, error) {
	row := q.db.QueryRow(ctx, getEventLogByID, id)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventName,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformSetting = `-- name: GetPlatformSetting :one
SELECT key, value, description, is_public, created_at, updated_at
FROM platform_settings
WHERE key = $1
`

func (q *Queries) GetPlatformSetting(ctx context.Context, key string) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getPlatformSetting, key)
	var i PlatformSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminMetricsDaily = `-- name: ListAdminMetricsDaily :many
SELECT metric_date, event_name, total_count, unique_users, created_at, updated_at
FROM admin_metrics_daily
WHERE metric_date >= $1
  AND metric_date <= $2
ORDER BY metric_date ASC, event_name ASC
`

type ListAdminMetricsDailyParams struct {
	FromDate pgtype.Date `db:"from_date" json:"from_date"`
	ToDate   pgtype.Date `db:"to_date" json:"to_date"`
}

func (q *Queries) ListAdminMetricsDaily(ctx context.Context, arg ListAdminMetricsDailyParams) ([]AdminMetricsDaily, error) {
	rows, err := q.db.Query(ctx, listAdminMetricsDaily, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminMetricsDaily
	for rows.Next() {
		var i AdminMetricsDaily
		if err := rows.Scan(
			&i.MetricDate,
			&i.EventName,
			&i.TotalCount,
			&i.UniqueUsers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT key, description, enabled, rules, created_at, updated_at
FROM feature_flags
ORDER BY key ASC
`

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlag
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.Key,
			&i.Description,
			&i.Enabled,
			&i.Rules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformSettings = `-- name: ListPlatformSettings :many
SELECT key, value, description, is_public, created_at, updated_at
FROM platform_settings
ORDER BY key ASC
`

func (q *Queries) ListPlatformSettings(ctx context.Context) ([]PlatformSetting, error) {
	rows, err := q.db.Query(ctx, listPlatformSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformSetting
	for rows.Next() {
		var i PlatformSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnalyticsEventFailed = `-- name: MarkAnalyticsEventFailed :exec
UPDATE analytics_event_queue
SET status = 'pending',
    last_error = $1,
    available_at = now() + $2::interval,
    updated_at = now()
WHERE id = $3
`

type MarkAnalyticsEventFailedParams struct {
	LastError  pgtype.Text     `db:"last_error" json:"last_error"`
	RetryAfter pgtype.Interval `db:"retry_after" json:"retry_after"`
	ID         pgtype.UUID     `db:"id" json:"id"`
}

func (q *Queries) MarkAnalyticsEventFailed(ctx context.Context, arg MarkAnalyticsEventFailedParams) error {
	_, err := q.db.Exec(ctx, markAnalyticsEventFailed, arg.LastError, arg.RetryAfter, arg.ID)
	return err
}

const markAnalyticsEventProcessed = `-- name: MarkAnalyticsEventProcessed :exec
UPDATE analytics_event_queue
SET status = 'processed',
    processed_at = now(),
    updated_at = now(),
    last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkAnalyticsEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAnalyticsEventProcessed, id)
	return err
}

const upsertAdminMetricDaily = `-- name: UpsertAdminMetricDaily :exec
INSERT INTO admin_metrics_daily (metric_date, event_name, total_count, unique_users)
VALUES (
  $1,
  $2,
  $3,
  $4
)
ON CONFLICT (metric_date, event_name) DO UPDATE
SET total_count = EXCLUDED.total_count,
    unique_users = EXCLUDED.unique_users,
    updated_at = now()
`

type UpsertAdminMetricDailyParams struct {
	MetricDate  pgtype.Date `db:"metric_date" json:"metric_date"`
	EventName   string      `db:"event_name" json:"event_name"`
	TotalCount  int64       `db:"total_count" json:"total_count"`
	UniqueUsers int64       `db:"unique_users" json:"unique_users"`
}

func (q *Queries) UpsertAdminMetricDaily(ctx context.Context, arg UpsertAdminMetricDailyParams) error {
	_, err := q.db.Exec(ctx, upsertAdminMetricDaily,
		arg.MetricDate,
		arg.EventName,
		arg.TotalCount,
		arg.UniqueUsers,
	)
	return err
}

const upsertFeatureFlag = `-- name: UpsertFeatureFlag :one
INSERT INTO feature_flags (key, description, enabled, rules)
VALUES ($1, $2, $3, COALESCE($4::jsonb, '{}'::jsonb))
ON CONFLICT (key) DO UPDATE
SET description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    rules = EXCLUDED.rules
RETURNING key, description, enabled, rules, created_at, updated_at
`

type UpsertFeatureFlagParams struct {
	Key         string      `db:"key" json:"key"`
	Description pgtype.Text `db:"description" json:"description"`
	Enabled     bool        `db:"enabled" json:"enabled"`
	Rules       []byte      `db:"rules" json:"rules"`
}

func (q *Queries) UpsertFeatureFlag(ctx context.Context, arg UpsertFeatureFlagParams) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, upsertFeatureFlag,
		arg.Key,
		arg.Description,
		arg.Enabled,
		arg.Rules,
	)
	var i FeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.Rules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlatformSetting = `-- name: UpsertPlatformSetting :one
INSERT INTO platform_settings (key, value, description, is_public)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    description = EXCLUDED.description,
    is_public = EXCLUDED.is_public
RETURNING key, value, description, is_public, created_at, updated_at
`

type UpsertPlatformSettingParams struct {
	Key         string      `db:"key" json:"key"`
	Value       []byte      `db:"value" json:"value"`
	Description pgtype.Text `db:"description" json:"description"`
	IsPublic    bool        `db:"is_public" json:"is_public"`
}

func (q *Queries) UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, upsertPlatformSetting,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.IsPublic,
	)
	var i PlatformSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
