// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reviewstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddReviewImage(ctx context.Context, arg AddReviewImageParams) (ProductReviewImage, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (ProductReview, error)
	CreateReviewReport(ctx context.Context, arg CreateReviewReportParams) (ReviewReport, error)
	DeleteReviewImage(ctx context.Context, arg DeleteReviewImageParams) error
	DeleteReviewVote(ctx context.Context, arg DeleteReviewVoteParams) error
	GetOrderItemForReviewVerification(ctx context.Context, arg GetOrderItemForReviewVerificationParams) (GetOrderItemForReviewVerificationRow, error)
	GetReviewForUser(ctx context.Context, arg GetReviewForUserParams) (ProductReview, error)
	HideReviewAdmin(ctx context.Context, arg HideReviewAdminParams) (ProductReview, error)
	ListOpenReviewReports(ctx context.Context, arg ListOpenReviewReportsParams) ([]ReviewReport, error)
	ListReviewImages(ctx context.Context, reviewID pgtype.UUID) ([]ProductReviewImage, error)
	ResolveReviewReport(ctx context.Context, arg ResolveReviewReportParams) (ReviewReport, error)
	SetSellerReply(ctx context.Context, arg SetSellerReplyParams) (ProductReview, error)
	SoftDeleteReviewAdmin(ctx context.Context, id pgtype.UUID) error
	SoftDeleteReviewForUser(ctx context.Context, arg SoftDeleteReviewForUserParams) error
	UpdateReviewForUser(ctx context.Context, arg UpdateReviewForUserParams) (ProductReview, error)
	UpsertReviewVote(ctx context.Context, arg UpsertReviewVoteParams) (ReviewVote, error)
}

var _ Querier = (*Queries)(nil)
