// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package reviewstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReviewImage = `-- name: AddReviewImage :one
INSERT INTO product_review_images (review_id, url, sort_order)
VALUES ($1, $2, $3)
RETURNING id, review_id, url, sort_order
`

type AddReviewImageParams struct {
	ReviewID  pgtype.UUID `db:"review_id" json:"review_id"`
	Url       string      `db:"url" json:"url"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
}

func (q *Queries) AddReviewImage(ctx context.Context, arg AddReviewImageParams) (ProductReviewImage, error) {
	row := q.db.QueryRow(ctx, addReviewImage, arg.ReviewID, arg.Url, arg.SortOrder)
	var i ProductReviewImage
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.Url,
		&i.SortOrder,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO product_reviews (product_id, order_item_id, user_id, rating, title, body, is_verified_purchase)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, order_item_id, user_id, rating, title, body, is_verified_purchase, is_hidden, deleted_at, created_at, updated_at, seller_reply, seller_reply_at, seller_reply_by
`

type CreateReviewParams struct {
	ProductID          pgtype.UUID `db:"product_id" json:"product_id"`
	OrderItemID        pgtype.UUID `db:"order_item_id" json:"order_item_id"`
	UserID             pgtype.UUID `db:"user_id" json:"user_id"`
	Rating             int32       `db:"rating" json:"rating"`
	Title              pgtype.Text `db:"title" json:"title"`
	Body               pgtype.Text `db:"body" json:"body"`
	IsVerifiedPurchase bool        `db:"is_verified_purchase" json:"is_verified_purchase"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (ProductReview, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProductID,
		arg.OrderItemID,
		arg.UserID,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.IsVerifiedPurchase,
	)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrderItemID,
		&i.UserID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.IsVerifiedPurchase,
		&i.IsHidden,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerReply,
		&i.SellerReplyAt,
		&i.SellerReplyBy,
	)
	return i, err
}

const createReviewReport = `-- name: CreateReviewReport :one
INSERT INTO review_reports (review_id, reporter_user_id, reason)
VALUES ($1, $2, $3)
RETURNING id, review_id, reporter_user_id, reason, status, resolved_by, resolved_at, created_at
`

type CreateReviewReportParams struct {
	ReviewID       pgtype.UUID `db:"review_id" json:"review_id"`
	ReporterUserID pgtype.UUID `db:"reporter_user_id" json:"reporter_user_id"`
	Reason         string      `db:"reason" json:"reason"`
}

func (q *Queries) CreateReviewReport(ctx context.Context, arg CreateReviewReportParams) (ReviewReport, error) {
	row := q.db.QueryRow(ctx, createReviewReport, arg.ReviewID, arg.ReporterUserID, arg.Reason)
	var i ReviewReport
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.ReporterUserID,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReviewImage = `-- name: DeleteReviewImage :exec
DELETE FROM product_review_images
WHERE id = $1 AND review_id = $2
`

type DeleteReviewImageParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
}

func (q *Queries) DeleteReviewImage(ctx context.Context, arg DeleteReviewImageParams) error {
	_, err := q.db.Exec(ctx, deleteReviewImage, arg.ID, arg.ReviewID)
	return err
}

const deleteReviewVote = `-- name: DeleteReviewVote :exec
DELETE FROM review_votes WHERE review_id = $1 AND user_id = $2
`

type DeleteReviewVoteParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteReviewVote(ctx context.Context, arg DeleteReviewVoteParams) error {
	_, err := q.db.Exec(ctx, deleteReviewVote, arg.ReviewID, arg.UserID)
	return err
}

const getOrderItemForReviewVerification = `-- name: GetOrderItemForReviewVerification :one
SELECT oi.id, oi.order_id, oi.product_id
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.id = $1
  AND o.user_id = $2
`

type GetOrderItemForReviewVerificationParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type GetOrderItemForReviewVerificationRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	OrderID   pgtype.UUID `db:"order_id" json:"order_id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
}

func (q *Queries) GetOrderItemForReviewVerification(ctx context.Context, arg GetOrderItemForReviewVerificationParams) (GetOrderItemForReviewVerificationRow, error) {
	row := q.db.QueryRow(ctx, getOrderItemForReviewVerification, arg.ID, arg.UserID)
	var i GetOrderItemForReviewVerificationRow
	err := row.Scan(&i.ID, &i.OrderID, &i.ProductID)
	return i, err
}

const getReviewForUser = `-- name: GetReviewForUser :one
SELECT id, product_id, order_item_id, user_id, rating, title, body, is_verified_purchase, is_hidden, deleted_at, created_at, updated_at, seller_reply, seller_reply_at, seller_reply_by
FROM product_reviews
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetReviewForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetReviewForUser(ctx context.Context, arg GetReviewForUserParams) (ProductReview, error) {
	row := q.db.QueryRow(ctx, getReviewForUser, arg.ID, arg.UserID)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrderItemID,
		&i.UserID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.IsVerifiedPurchase,
		&i.IsHidden,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerReply,
		&i.SellerReplyAt,
		&i.SellerReplyBy,
	)
	return i, err
}

const hideReviewAdmin = `-- name: HideReviewAdmin :one
UPDATE product_reviews
SET is_hidden = $2
WHERE id = $1
RETURNING id, product_id, order_item_id, user_id, rating, title, body, is_verified_purchase, is_hidden, deleted_at, created_at, updated_at, seller_reply, seller_reply_at, seller_reply_by
`

type HideReviewAdminParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	IsHidden bool        `db:"is_hidden" json:"is_hidden"`
}

func (q *Queries) HideReviewAdmin(ctx context.Context, arg HideReviewAdminParams) (ProductReview, error) {
	row := q.db.QueryRow(ctx, hideReviewAdmin, arg.ID, arg.IsHidden)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrderItemID,
		&i.UserID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.IsVerifiedPurchase,
		&i.IsHidden,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerReply,
		&i.SellerReplyAt,
		&i.SellerReplyBy,
	)
	return i, err
}

const listOpenReviewReports = `-- name: ListOpenReviewReports :many
SELECT id, review_id, reporter_user_id, reason, status, resolved_by, resolved_at, created_at
FROM review_reports
WHERE status = 'open'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOpenReviewReportsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListOpenReviewReports(ctx context.Context, arg ListOpenReviewReportsParams) ([]ReviewReport, error) {
	rows, err := q.db.Query(ctx, listOpenReviewReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReport
	for rows.Next() {
		var i ReviewReport
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.ReporterUserID,
			&i.Reason,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewImages = `-- name: ListReviewImages :many
SELECT id, review_id, url, sort_order
FROM product_review_images
WHERE review_id = $1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListReviewImages(ctx context.Context, reviewID pgtype.UUID) ([]ProductReviewImage, error) {
	rows, err := q.db.Query(ctx, listReviewImages, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductReviewImage
	for rows.Next() {
		var i ProductReviewImage
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.Url,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReviewReport = `-- name: ResolveReviewReport :one
UPDATE review_reports
SET status = 'resolved',
    resolved_by = $2,
    resolved_at = now()
WHERE id = $1
RETURNING id, review_id, reporter_user_id, reason, status, resolved_by, resolved_at, created_at
`

type ResolveReviewReportParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	ResolvedBy pgtype.UUID `db:"resolved_by" json:"resolved_by"`
}

func (q *Queries) ResolveReviewReport(ctx context.Context, arg ResolveReviewReportParams) (ReviewReport, error) {
	row := q.db.QueryRow(ctx, resolveReviewReport, arg.ID, arg.ResolvedBy)
	var i ReviewReport
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.ReporterUserID,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setSellerReply = `-- name: SetSellerReply :one
UPDATE product_reviews pr
SET seller_reply = $2,
    seller_reply_at = now(),
    seller_reply_by = $3
FROM products p
WHERE pr.id = $1
  AND pr.product_id = p.id
  AND p.seller_id = $4
  AND pr.deleted_at IS NULL
RETURNING pr.id, pr.product_id, pr.order_item_id, pr.user_id, pr.rating, pr.title, pr.body, pr.is_verified_purchase, pr.is_hidden, pr.deleted_at, pr.created_at, pr.updated_at, pr.seller_reply, pr.seller_reply_at, pr.seller_reply_by
`

type SetSellerReplyParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	SellerReply   pgtype.Text `db:"seller_reply" json:"seller_reply"`
	SellerReplyBy pgtype.UUID `db:"seller_reply_by" json:"seller_reply_by"`
	SellerID      pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) SetSellerReply(ctx context.Context, arg SetSellerReplyParams) (ProductReview, error) {
	row := q.db.QueryRow(ctx, setSellerReply,
		arg.ID,
		arg.SellerReply,
		arg.SellerReplyBy,
		arg.SellerID,
	)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrderItemID,
		&i.UserID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.IsVerifiedPurchase,
		&i.IsHidden,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerReply,
		&i.SellerReplyAt,
		&i.SellerReplyBy,
	)
	return i, err
}

const softDeleteReviewAdmin = `-- name: SoftDeleteReviewAdmin :exec
UPDATE product_reviews
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteReviewAdmin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteReviewAdmin, id)
	return err
}

const softDeleteReviewForUser = `-- name: SoftDeleteReviewForUser :exec
UPDATE product_reviews
SET deleted_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteReviewForUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) SoftDeleteReviewForUser(ctx context.Context, arg SoftDeleteReviewForUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteReviewForUser, arg.ID, arg.UserID)
	return err
}

const updateReviewForUser = `-- name: UpdateReviewForUser :one
UPDATE product_reviews
SET rating = COALESCE($1::int, rating),
    title = COALESCE($2::text, title),
    body = COALESCE($3::text, body)
WHERE id = $4
  AND user_id = $5
  AND deleted_at IS NULL
RETURNING id, product_id, order_item_id, user_id, rating, title, body, is_verified_purchase, is_hidden, deleted_at, created_at, updated_at, seller_reply, seller_reply_at, seller_reply_by
`

type UpdateReviewForUserParams struct {
	Rating pgtype.Int4 `db:"rating" json:"rating"`
	Title  pgtype.Text `db:"title" json:"title"`
	Body   pgtype.Text `db:"body" json:"body"`
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateReviewForUser(ctx context.Context, arg UpdateReviewForUserParams) (ProductReview, error) {
	row := q.db.QueryRow(ctx, updateReviewForUser,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.ID,
		arg.UserID,
	)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrderItemID,
		&i.UserID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.IsVerifiedPurchase,
		&i.IsHidden,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerReply,
		&i.SellerReplyAt,
		&i.SellerReplyBy,
	)
	return i, err
}

const upsertReviewVote = `-- name: UpsertReviewVote :one
INSERT INTO review_votes (review_id, user_id, vote)
VALUES ($1, $2, $3)
ON CONFLICT (review_id, user_id)
DO UPDATE SET vote = EXCLUDED.vote
RETURNING review_id, user_id, vote, created_at
`

type UpsertReviewVoteParams struct {
	ReviewID pgtype.UUID `db:"review_id" json:"review_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Vote     int32       `db:"vote" json:"vote"`
}

func (q *Queries) UpsertReviewVote(ctx context.Context, arg UpsertReviewVoteParams) (ReviewVote, error) {
	row := q.db.QueryRow(ctx, upsertReviewVote, arg.ReviewID, arg.UserID, arg.Vote)
	var i ReviewVote
	err := row.Scan(
		&i.ReviewID,
		&i.UserID,
		&i.Vote,
		&i.CreatedAt,
	)
	return i, err
}
