// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package searchstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearRecentSearchQueriesForSession(ctx context.Context, sessionID pgtype.Text) error
	ClearRecentSearchQueriesForUser(ctx context.Context, userID pgtype.UUID) error
	ListIndexableProducts(ctx context.Context, arg ListIndexableProductsParams) ([]ListIndexableProductsRow, error)
	ListRecentSearchQueriesForSession(ctx context.Context, arg ListRecentSearchQueriesForSessionParams) ([]SearchRecentQuery, error)
	ListRecentSearchQueriesForUser(ctx context.Context, arg ListRecentSearchQueriesForUserParams) ([]SearchRecentQuery, error)
	ListTrendingSearchQueries(ctx context.Context, arg ListTrendingSearchQueriesParams) ([]ListTrendingSearchQueriesRow, error)
}

var _ Querier = (*Queries)(nil)
