// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package workerstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimWorkerJobRun(ctx context.Context, arg ClaimWorkerJobRunParams) (WorkerJobRun, error)
	CreateWorkerJobExecution(ctx context.Context, arg CreateWorkerJobExecutionParams) (WorkerJobExecution, error)
	GetWorkerJobRun(ctx context.Context, arg GetWorkerJobRunParams) (WorkerJobRun, error)
	MarkWorkerJobDone(ctx context.Context, id pgtype.UUID) error
	MarkWorkerJobExecutionDone(ctx context.Context, id pgtype.UUID) error
	MarkWorkerJobExecutionFailed(ctx context.Context, arg MarkWorkerJobExecutionFailedParams) error
	MarkWorkerJobFailed(ctx context.Context, arg MarkWorkerJobFailedParams) error
}

var _ Querier = (*Queries)(nil)
