// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package workerstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWorkerJobRun = `-- name: ClaimWorkerJobRun :one
INSERT INTO worker_job_runs (job_type, dedupe_key, status, payload, attempts)
VALUES (
  $1,
  $2,
  'processing',
  COALESCE($3::jsonb, '{}'::jsonb),
  1
)
ON CONFLICT (job_type, dedupe_key) DO UPDATE
SET attempts = worker_job_runs.attempts + 1,
    status = CASE
      WHEN worker_job_runs.status = 'done' THEN worker_job_runs.status
      ELSE 'processing'
    END,
    payload = COALESCE($3::jsonb, worker_job_runs.payload),
    updated_at = now()
RETURNING id, job_type, dedupe_key, status, attempts, last_error, payload, started_at, completed_at, created_at, updated_at
`

type ClaimWorkerJobRunParams struct {
	JobType   string `db:"job_type" json:"job_type"`
	DedupeKey string `db:"dedupe_key" json:"dedupe_key"`
	Payload   []byte `db:"payload" json:"payload"`
}

func (q *Queries) ClaimWorkerJobRun(ctx context.Context, arg ClaimWorkerJobRunParams) (WorkerJobRun, error) {
	row := q.db.QueryRow(ctx, claimWorkerJobRun, arg.JobType, arg.DedupeKey, arg.Payload)
	var i WorkerJobRun
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkerJobExecution = `-- name: CreateWorkerJobExecution :one
INSERT INTO worker_job_executions (job_run_id, message_id, attempt, status)
VALUES ($1, $2, $3, 'running')
ON CONFLICT (job_run_id, attempt) DO UPDATE
SET message_id = EXCLUDED.message_id,
    status = 'running',
    error = NULL,
    started_at = now(),
    finished_at = NULL
RETURNING id, job_run_id, message_id, attempt, status, error, started_at, finished_at, created_at
`

type CreateWorkerJobExecutionParams struct {
	JobRunID  pgtype.UUID `db:"job_run_id" json:"job_run_id"`
	MessageID string      `db:"message_id" json:"message_id"`
	Attempt   int32       `db:"attempt" json:"attempt"`
}

func (q *Queries) CreateWorkerJobExecution(ctx context.Context, arg CreateWorkerJobExecutionParams) (WorkerJobExecution, error) {
	row := q.db.QueryRow(ctx, createWorkerJobExecution, arg.JobRunID, arg.MessageID, arg.Attempt)
	var i WorkerJobExecution
	err := row.Scan(
		&i.ID,
		&i.JobRunID,
		&i.MessageID,
		&i.Attempt,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkerJobRun = `-- name: GetWorkerJobRun :one
SELECT id, job_type, dedupe_key, status, attempts, last_error, payload, started_at, completed_at, created_at, updated_at
FROM worker_job_runs
WHERE job_type = $1 AND dedupe_key = $2
`

type GetWorkerJobRunParams struct {
	JobType   string `db:"job_type" json:"job_type"`
	DedupeKey string `db:"dedupe_key" json:"dedupe_key"`
}

func (q *Queries) GetWorkerJobRun(ctx context.Context, arg GetWorkerJobRunParams) (WorkerJobRun, error) {
	row := q.db.QueryRow(ctx, getWorkerJobRun, arg.JobType, arg.DedupeKey)
	var i WorkerJobRun
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkerJobDone = `-- name: MarkWorkerJobDone :exec
UPDATE worker_job_runs
SET status = 'done',
    completed_at = now(),
    last_error = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkWorkerJobDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markWorkerJobDone, id)
	return err
}

const markWorkerJobExecutionDone = `-- name: MarkWorkerJobExecutionDone :exec
UPDATE worker_job_executions
SET status = 'done',
    error = NULL,
    finished_at = now()
WHERE id = $1
`

func (q *Queries) MarkWorkerJobExecutionDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markWorkerJobExecutionDone, id)
	return err
}

const markWorkerJobExecutionFailed = `-- name: MarkWorkerJobExecutionFailed :exec
UPDATE worker_job_executions
SET status = 'failed',
    error = $1,
    finished_at = now()
WHERE id = $2
`

type MarkWorkerJobExecutionFailedParams struct {
	Error pgtype.Text `db:"error" json:"error"`
	ID    pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkWorkerJobExecutionFailed(ctx context.Context, arg MarkWorkerJobExecutionFailedParams) error {
	_, err := q.db.Exec(ctx, markWorkerJobExecutionFailed, arg.Error, arg.ID)
	return err
}

const markWorkerJobFailed = `-- name: MarkWorkerJobFailed :exec
UPDATE worker_job_runs
SET status = 'failed',
    last_error = $1,
    updated_at = now()
WHERE id = $2
`

type MarkWorkerJobFailedParams struct {
	LastError pgtype.Text `db:"last_error" json:"last_error"`
	ID        pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkWorkerJobFailed(ctx context.Context, arg MarkWorkerJobFailedParams) error {
	_, err := q.db.Exec(ctx, markWorkerJobFailed, arg.LastError, arg.ID)
	return err
}
