// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotions.sql

package promostore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveVouchers = `-- name: CountActiveVouchers :one
SELECT count(*)::bigint
FROM vouchers
WHERE is_active = TRUE
  AND starts_at <= now()
  AND ends_at > now()
  AND (usage_limit IS NULL OR usage_count < usage_limit)
  AND ($1::uuid IS NULL OR seller_id = $1::uuid)
`

func (q *Queries) CountActiveVouchers(ctx context.Context, sellerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVouchers, sellerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAllVouchersAdmin = `-- name: CountAllVouchersAdmin :one
SELECT count(*)::bigint FROM vouchers
`

func (q *Queries) CountAllVouchersAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllVouchersAdmin)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSellerVouchers = `-- name: CountSellerVouchers :one
SELECT count(*)::bigint
FROM vouchers
WHERE seller_id = $1
`

func (q *Queries) CountSellerVouchers(ctx context.Context, sellerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerVouchers, sellerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO vouchers (code, title, description, discount_type, discount_value, min_order_cents, max_discount_cents, usage_limit, starts_at, ends_at, is_active, seller_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, code, title, description, discount_type, discount_value, min_order_cents, max_discount_cents, usage_limit, usage_count, starts_at, ends_at, is_active, created_at, seller_id
`

type CreateVoucherParams struct {
	Code             string             `db:"code" json:"code"`
	Title            string             `db:"title" json:"title"`
	Description      pgtype.Text        `db:"description" json:"description"`
	DiscountType     string             `db:"discount_type" json:"discount_type"`
	DiscountValue    int64              `db:"discount_value" json:"discount_value"`
	MinOrderCents    int64              `db:"min_order_cents" json:"min_order_cents"`
	MaxDiscountCents pgtype.Int8        `db:"max_discount_cents" json:"max_discount_cents"`
	UsageLimit       pgtype.Int4        `db:"usage_limit" json:"usage_limit"`
	StartsAt         pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt           pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, createVoucher,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.DiscountType,
		arg.DiscountValue,
		arg.MinOrderCents,
		arg.MaxDiscountCents,
		arg.UsageLimit,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsActive,
		arg.SellerID,
	)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinOrderCents,
		&i.MaxDiscountCents,
		&i.UsageLimit,
		&i.UsageCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.SellerID,
	)
	return i, err
}

const deleteVoucher = `-- name: DeleteVoucher :exec
DELETE FROM vouchers WHERE id = $1
`

func (q *Queries) DeleteVoucher(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVoucher, id)
	return err
}

const listActiveVouchers = `-- name: ListActiveVouchers :many
SELECT id, code, title, description, discount_type, discount_value, min_order_cents, max_discount_cents, usage_limit, usage_count, starts_at, ends_at, is_active, created_at, seller_id
FROM vouchers
WHERE is_active = TRUE
  AND starts_at <= now()
  AND ends_at > now()
  AND (usage_limit IS NULL OR usage_count < usage_limit)
  AND ($1::uuid IS NULL OR seller_id = $1::uuid)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListActiveVouchersParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Offset   int32       `db:"offset" json:"offset"`
	Limit    int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListActiveVouchers(ctx context.Context, arg ListActiveVouchersParams) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, listActiveVouchers, arg.SellerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.DiscountType,
			&i.DiscountValue,
			&i.MinOrderCents,
			&i.MaxDiscountCents,
			&i.UsageLimit,
			&i.UsageCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.SellerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVouchersAdmin = `-- name: ListAllVouchersAdmin :many
SELECT id, code, title, description, discount_type, discount_value, min_order_cents, max_discount_cents, usage_limit, usage_count, starts_at, ends_at, is_active, created_at, seller_id
FROM vouchers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllVouchersAdminParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAllVouchersAdmin(ctx context.Context, arg ListAllVouchersAdminParams) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, listAllVouchersAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.DiscountType,
			&i.DiscountValue,
			&i.MinOrderCents,
			&i.MaxDiscountCents,
			&i.UsageLimit,
			&i.UsageCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.SellerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerVouchers = `-- name: ListSellerVouchers :many
SELECT id, code, title, description, discount_type, discount_value, min_order_cents, max_discount_cents, usage_limit, usage_count, starts_at, ends_at, is_active, created_at, seller_id
FROM vouchers
WHERE seller_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSellerVouchersParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListSellerVouchers(ctx context.Context, arg ListSellerVouchersParams) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, listSellerVouchers, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.DiscountType,
			&i.DiscountValue,
			&i.MinOrderCents,
			&i.MaxDiscountCents,
			&i.UsageLimit,
			&i.UsageCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.SellerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoucher = `-- name: UpdateVoucher :one
UPDATE vouchers
SET title = COALESCE($1::text, title),
    description = COALESCE($2::text, description),
    discount_type = COALESCE($3::text, discount_type),
    discount_value = COALESCE($4::bigint, discount_value),
    min_order_cents = COALESCE($5::bigint, min_order_cents),
    max_discount_cents = COALESCE($6::bigint, max_discount_cents),
    usage_limit = COALESCE($7::int, usage_limit),
    starts_at = COALESCE($8::timestamptz, starts_at),
    ends_at = COALESCE($9::timestamptz, ends_at),
    is_active = COALESCE($10::bool, is_active)
WHERE id = $11
RETURNING id, code, title, description, discount_type, discount_value, min_order_cents, max_discount_cents, usage_limit, usage_count, starts_at, ends_at, is_active, created_at, seller_id
`

type UpdateVoucherParams struct {
	Title            pgtype.Text        `db:"title" json:"title"`
	Description      pgtype.Text        `db:"description" json:"description"`
	DiscountType     pgtype.Text        `db:"discount_type" json:"discount_type"`
	DiscountValue    pgtype.Int8        `db:"discount_value" json:"discount_value"`
	MinOrderCents    pgtype.Int8        `db:"min_order_cents" json:"min_order_cents"`
	MaxDiscountCents pgtype.Int8        `db:"max_discount_cents" json:"max_discount_cents"`
	UsageLimit       pgtype.Int4        `db:"usage_limit" json:"usage_limit"`
	StartsAt         pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt           pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	IsActive         pgtype.Bool        `db:"is_active" json:"is_active"`
	ID               pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdateVoucher(ctx context.Context, arg UpdateVoucherParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, updateVoucher,
		arg.Title,
		arg.Description,
		arg.DiscountType,
		arg.DiscountValue,
		arg.MinOrderCents,
		arg.MaxDiscountCents,
		arg.UsageLimit,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsActive,
		arg.ID,
	)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinOrderCents,
		&i.MaxDiscountCents,
		&i.UsageLimit,
		&i.UsageCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.SellerID,
	)
	return i, err
}
