// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package promostore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveVouchers(ctx context.Context, sellerID pgtype.UUID) (int64, error)
	CountAllVouchersAdmin(ctx context.Context) (int64, error)
	CountSellerVouchers(ctx context.Context, sellerID pgtype.UUID) (int64, error)
	CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error)
	DeleteVoucher(ctx context.Context, id pgtype.UUID) error
	ListActiveVouchers(ctx context.Context, arg ListActiveVouchersParams) ([]Voucher, error)
	ListAllVouchersAdmin(ctx context.Context, arg ListAllVouchersAdminParams) ([]Voucher, error)
	ListSellerVouchers(ctx context.Context, arg ListSellerVouchersParams) ([]Voucher, error)
	UpdateVoucher(ctx context.Context, arg UpdateVoucherParams) (Voucher, error)
}

var _ Querier = (*Queries)(nil)
