// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package paymentstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearDefaultPaymentMethods(ctx context.Context, userID pgtype.UUID) error
	CountDeliveredShipmentsForOrder(ctx context.Context, orderID pgtype.UUID) (int64, error)
	CountDeliveredShipmentsForOrderSeller(ctx context.Context, arg CountDeliveredShipmentsForOrderSellerParams) (int64, error)
	CreateManualWaveApproval(ctx context.Context, arg CreateManualWaveApprovalParams) (ManualWavePaymentApproval, error)
	CreateManualWaveRejection(ctx context.Context, arg CreateManualWaveRejectionParams) (ManualWavePaymentApproval, error)
	CreatePODCapture(ctx context.Context, arg CreatePODCaptureParams) (PodPaymentCapture, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error)
	CreatePayoutRequest(ctx context.Context, arg CreatePayoutRequestParams) (SellerPayout, error)
	CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error)
	CreateReturnRequest(ctx context.Context, arg CreateReturnRequestParams) (ReturnRequest, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (SellerWalletTransaction, error)
	DeletePaymentMethod(ctx context.Context, arg DeletePaymentMethodParams) error
	GetManualWaveDecisionForPayment(ctx context.Context, paymentID pgtype.UUID) (ManualWavePaymentApproval, error)
	GetOrCreateSellerWallet(ctx context.Context, arg GetOrCreateSellerWalletParams) (SellerWallet, error)
	GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentByOrderAndIdempotencyKey(ctx context.Context, arg GetPaymentByOrderAndIdempotencyKeyParams) (Payment, error)
	GetPaymentForUser(ctx context.Context, arg GetPaymentForUserParams) (Payment, error)
	GetPaymentMethodForUser(ctx context.Context, arg GetPaymentMethodForUserParams) (PaymentMethod, error)
	GetPayoutByID(ctx context.Context, id pgtype.UUID) (SellerPayout, error)
	GetRefundByID(ctx context.Context, id pgtype.UUID) (Refund, error)
	InsertPaymentWebhookEvent(ctx context.Context, arg InsertPaymentWebhookEventParams) (PaymentWebhookEvent, error)
	ListOrderCreditsPendingHoldRelease(ctx context.Context, arg ListOrderCreditsPendingHoldReleaseParams) ([]ListOrderCreditsPendingHoldReleaseRow, error)
	ListPaymentMethodsForUser(ctx context.Context, userID pgtype.UUID) ([]PaymentMethod, error)
	ListPayoutsForSeller(ctx context.Context, arg ListPayoutsForSellerParams) ([]SellerPayout, error)
	ListPendingWaveManualPayments(ctx context.Context, arg ListPendingWaveManualPaymentsParams) ([]Payment, error)
	ListRefundsForAdmin(ctx context.Context, arg ListRefundsForAdminParams) ([]Refund, error)
	ListUnsettledSellerOrderCredits(ctx context.Context, limit int32) ([]ListUnsettledSellerOrderCreditsRow, error)
	ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]SellerWalletTransaction, error)
	LockPayoutByID(ctx context.Context, id pgtype.UUID) (SellerPayout, error)
	LockSellerWallet(ctx context.Context, sellerID pgtype.UUID) (SellerWallet, error)
	MarkPaymentWebhookProcessed(ctx context.Context, id pgtype.UUID) (PaymentWebhookEvent, error)
	MarkRefundProcessed(ctx context.Context, id pgtype.UUID) (Refund, error)
	ReviewRefund(ctx context.Context, arg ReviewRefundParams) (Refund, error)
	SetDefaultPaymentMethod(ctx context.Context, arg SetDefaultPaymentMethodParams) (PaymentMethod, error)
	UpdatePaymentMetadataMerge(ctx context.Context, arg UpdatePaymentMetadataMergeParams) (Payment, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) (SellerPayout, error)
	UpdateWalletBalances(ctx context.Context, arg UpdateWalletBalancesParams) (SellerWallet, error)
}

var _ Querier = (*Queries)(nil)
