// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cms.sql

package cmsstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCreateAnnouncement = `-- name: AdminCreateAnnouncement :one
INSERT INTO cms_announcements (title, body, audience, status, starts_at, ends_at)
VALUES (
  $1,
  $2,
  COALESCE($3::text, 'all'),
  COALESCE($4::cms_status, 'draft'),
  $5::timestamptz,
  $6::timestamptz
)
RETURNING id, title, body, audience, status, starts_at, ends_at, created_at, updated_at
`

type AdminCreateAnnouncementParams struct {
	Title    string             `db:"title" json:"title"`
	Body     string             `db:"body" json:"body"`
	Audience pgtype.Text        `db:"audience" json:"audience"`
	Status   interface{}        `db:"status" json:"status"`
	StartsAt pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt   pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
}

func (q *Queries) AdminCreateAnnouncement(ctx context.Context, arg AdminCreateAnnouncementParams) (CmsAnnouncement, error) {
	row := q.db.QueryRow(ctx, adminCreateAnnouncement,
		arg.Title,
		arg.Body,
		arg.Audience,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i CmsAnnouncement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Audience,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminCreateBanner = `-- name: AdminCreateBanner :one
INSERT INTO cms_banners (title, image_url, link_url, placement, sort_order, status, starts_at, ends_at)
VALUES (
  $1,
  $2,
  $3::text,
  COALESCE($4::text, 'home'),
  COALESCE($5::int, 0),
  COALESCE($6::cms_status, 'draft'),
  $7::timestamptz,
  $8::timestamptz
)
RETURNING id, title, image_url, link_url, placement, sort_order, status, starts_at, ends_at, created_at, updated_at
`

type AdminCreateBannerParams struct {
	Title     string             `db:"title" json:"title"`
	ImageUrl  string             `db:"image_url" json:"image_url"`
	LinkUrl   pgtype.Text        `db:"link_url" json:"link_url"`
	Placement pgtype.Text        `db:"placement" json:"placement"`
	SortOrder pgtype.Int4        `db:"sort_order" json:"sort_order"`
	Status    interface{}        `db:"status" json:"status"`
	StartsAt  pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt    pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
}

func (q *Queries) AdminCreateBanner(ctx context.Context, arg AdminCreateBannerParams) (CmsBanner, error) {
	row := q.db.QueryRow(ctx, adminCreateBanner,
		arg.Title,
		arg.ImageUrl,
		arg.LinkUrl,
		arg.Placement,
		arg.SortOrder,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i CmsBanner
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.Placement,
		&i.SortOrder,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminCreateFaq = `-- name: AdminCreateFaq :one
INSERT INTO cms_faqs (question, answer, category, sort_order, status)
VALUES (
  $1,
  $2,
  $3::text,
  COALESCE($4::int, 0),
  COALESCE($5::cms_status, 'draft')
)
RETURNING id, question, answer, category, sort_order, status, created_at, updated_at
`

type AdminCreateFaqParams struct {
	Question  string      `db:"question" json:"question"`
	Answer    string      `db:"answer" json:"answer"`
	Category  pgtype.Text `db:"category" json:"category"`
	SortOrder pgtype.Int4 `db:"sort_order" json:"sort_order"`
	Status    interface{} `db:"status" json:"status"`
}

func (q *Queries) AdminCreateFaq(ctx context.Context, arg AdminCreateFaqParams) (CmsFaq, error) {
	row := q.db.QueryRow(ctx, adminCreateFaq,
		arg.Question,
		arg.Answer,
		arg.Category,
		arg.SortOrder,
		arg.Status,
	)
	var i CmsFaq
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.Category,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminCreatePage = `-- name: AdminCreatePage :one
INSERT INTO cms_pages (slug, title, body, status, published_at, created_by, updated_by)
VALUES (
  $1,
  $2,
  $3,
  COALESCE($4::cms_status, 'draft'),
  $5::timestamptz,
  $6::uuid,
  $6::uuid
)
RETURNING id, slug, title, body, status, published_at, created_by, updated_by, created_at, updated_at
`

type AdminCreatePageParams struct {
	Slug        string             `db:"slug" json:"slug"`
	Title       string             `db:"title" json:"title"`
	Body        string             `db:"body" json:"body"`
	Status      interface{}        `db:"status" json:"status"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	ActorUserID pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
}

func (q *Queries) AdminCreatePage(ctx context.Context, arg AdminCreatePageParams) (CmsPage, error) {
	row := q.db.QueryRow(ctx, adminCreatePage,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.PublishedAt,
		arg.ActorUserID,
	)
	var i CmsPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteAnnouncement = `-- name: AdminDeleteAnnouncement :exec
DELETE FROM cms_announcements
WHERE id = $1
`

func (q *Queries) AdminDeleteAnnouncement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteAnnouncement, id)
	return err
}

const adminDeleteBanner = `-- name: AdminDeleteBanner :exec
DELETE FROM cms_banners
WHERE id = $1
`

func (q *Queries) AdminDeleteBanner(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteBanner, id)
	return err
}

const adminDeleteFaq = `-- name: AdminDeleteFaq :exec
DELETE FROM cms_faqs
WHERE id = $1
`

func (q *Queries) AdminDeleteFaq(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteFaq, id)
	return err
}

const adminDeletePage = `-- name: AdminDeletePage :exec
DELETE FROM cms_pages
WHERE id = $1
`

func (q *Queries) AdminDeletePage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeletePage, id)
	return err
}

const adminGetAnnouncementByID = `-- name: AdminGetAnnouncementByID :one
SELECT id, title, body, audience, status, starts_at, ends_at, created_at, updated_at
FROM cms_announcements
WHERE id = $1
`

func (q *Queries) AdminGetAnnouncementByID(ctx context.Context, id pgtype.UUID) (CmsAnnouncement, error) {
	row := q.db.QueryRow(ctx, adminGetAnnouncementByID, id)
	var i CmsAnnouncement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Audience,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetBannerByID = `-- name: AdminGetBannerByID :one
SELECT id, title, image_url, link_url, placement, sort_order, status, starts_at, ends_at, created_at, updated_at
FROM cms_banners
WHERE id = $1
`

func (q *Queries) AdminGetBannerByID(ctx context.Context, id pgtype.UUID) (CmsBanner, error) {
	row := q.db.QueryRow(ctx, adminGetBannerByID, id)
	var i CmsBanner
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.Placement,
		&i.SortOrder,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetFaqByID = `-- name: AdminGetFaqByID :one
SELECT id, question, answer, category, sort_order, status, created_at, updated_at
FROM cms_faqs
WHERE id = $1
`

func (q *Queries) AdminGetFaqByID(ctx context.Context, id pgtype.UUID) (CmsFaq, error) {
	row := q.db.QueryRow(ctx, adminGetFaqByID, id)
	var i CmsFaq
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.Category,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetPageByID = `-- name: AdminGetPageByID :one
SELECT id, slug, title, body, status, published_at, created_by, updated_by, created_at, updated_at
FROM cms_pages
WHERE id = $1
`

func (q *Queries) AdminGetPageByID(ctx context.Context, id pgtype.UUID) (CmsPage, error) {
	row := q.db.QueryRow(ctx, adminGetPageByID, id)
	var i CmsPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListAnnouncements = `-- name: AdminListAnnouncements :many
SELECT id, title, body, audience, status, starts_at, ends_at, created_at, updated_at
FROM cms_announcements
WHERE ($1::cms_status IS NULL OR status = $1::cms_status)
  AND ($2::text IS NULL OR audience = $2::text)
ORDER BY COALESCE(starts_at, created_at) DESC
LIMIT $4 OFFSET $3
`

type AdminListAnnouncementsParams struct {
	Status   interface{} `db:"status" json:"status"`
	Audience pgtype.Text `db:"audience" json:"audience"`
	Offset   int32       `db:"offset" json:"offset"`
	Limit    int32       `db:"limit" json:"limit"`
}

func (q *Queries) AdminListAnnouncements(ctx context.Context, arg AdminListAnnouncementsParams) ([]CmsAnnouncement, error) {
	rows, err := q.db.Query(ctx, adminListAnnouncements,
		arg.Status,
		arg.Audience,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CmsAnnouncement
	for rows.Next() {
		var i CmsAnnouncement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Audience,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListBanners = `-- name: AdminListBanners :many
SELECT id, title, image_url, link_url, placement, sort_order, status, starts_at, ends_at, created_at, updated_at
FROM cms_banners
WHERE ($1::cms_status IS NULL OR status = $1::cms_status)
  AND ($2::text IS NULL OR placement = $2::text)
ORDER BY placement ASC, sort_order ASC, updated_at DESC
LIMIT $4 OFFSET $3
`

type AdminListBannersParams struct {
	Status    interface{} `db:"status" json:"status"`
	Placement pgtype.Text `db:"placement" json:"placement"`
	Offset    int32       `db:"offset" json:"offset"`
	Limit     int32       `db:"limit" json:"limit"`
}

func (q *Queries) AdminListBanners(ctx context.Context, arg AdminListBannersParams) ([]CmsBanner, error) {
	rows, err := q.db.Query(ctx, adminListBanners,
		arg.Status,
		arg.Placement,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CmsBanner
	for rows.Next() {
		var i CmsBanner
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.Placement,
			&i.SortOrder,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListFaqs = `-- name: AdminListFaqs :many
SELECT id, question, answer, category, sort_order, status, created_at, updated_at
FROM cms_faqs
WHERE ($1::cms_status IS NULL OR status = $1::cms_status)
  AND ($2::text IS NULL OR category = $2::text)
ORDER BY COALESCE(category, '') ASC, sort_order ASC, updated_at DESC
LIMIT $4 OFFSET $3
`

type AdminListFaqsParams struct {
	Status   interface{} `db:"status" json:"status"`
	Category pgtype.Text `db:"category" json:"category"`
	Offset   int32       `db:"offset" json:"offset"`
	Limit    int32       `db:"limit" json:"limit"`
}

func (q *Queries) AdminListFaqs(ctx context.Context, arg AdminListFaqsParams) ([]CmsFaq, error) {
	rows, err := q.db.Query(ctx, adminListFaqs,
		arg.Status,
		arg.Category,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CmsFaq
	for rows.Next() {
		var i CmsFaq
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.Answer,
			&i.Category,
			&i.SortOrder,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPages = `-- name: AdminListPages :many
SELECT id, slug, title, body, status, published_at, created_by, updated_by, created_at, updated_at
FROM cms_pages
WHERE ($1::cms_status IS NULL OR status = $1::cms_status)
  AND ($2::text IS NULL OR slug ILIKE ('%' || $2::text || '%') OR title ILIKE ('%' || $2::text || '%'))
ORDER BY updated_at DESC
LIMIT $4 OFFSET $3
`

type AdminListPagesParams struct {
	Status interface{} `db:"status" json:"status"`
	Q      pgtype.Text `db:"q" json:"q"`
	Offset int32       `db:"offset" json:"offset"`
	Limit  int32       `db:"limit" json:"limit"`
}

func (q *Queries) AdminListPages(ctx context.Context, arg AdminListPagesParams) ([]CmsPage, error) {
	rows, err := q.db.Query(ctx, adminListPages,
		arg.Status,
		arg.Q,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CmsPage
	for rows.Next() {
		var i CmsPage
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateAnnouncement = `-- name: AdminUpdateAnnouncement :one
UPDATE cms_announcements
SET title = COALESCE($1::text, title),
    body = COALESCE($2::text, body),
    audience = COALESCE($3::text, audience),
    status = COALESCE($4::cms_status, status),
    starts_at = COALESCE($5::timestamptz, starts_at),
    ends_at = COALESCE($6::timestamptz, ends_at)
WHERE id = $7
RETURNING id, title, body, audience, status, starts_at, ends_at, created_at, updated_at
`

type AdminUpdateAnnouncementParams struct {
	Title    pgtype.Text        `db:"title" json:"title"`
	Body     pgtype.Text        `db:"body" json:"body"`
	Audience pgtype.Text        `db:"audience" json:"audience"`
	Status   interface{}        `db:"status" json:"status"`
	StartsAt pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt   pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	ID       pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) AdminUpdateAnnouncement(ctx context.Context, arg AdminUpdateAnnouncementParams) (CmsAnnouncement, error) {
	row := q.db.QueryRow(ctx, adminUpdateAnnouncement,
		arg.Title,
		arg.Body,
		arg.Audience,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	var i CmsAnnouncement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Audience,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpdateBanner = `-- name: AdminUpdateBanner :one
UPDATE cms_banners
SET title = COALESCE($1::text, title),
    image_url = COALESCE($2::text, image_url),
    link_url = COALESCE($3::text, link_url),
    placement = COALESCE($4::text, placement),
    sort_order = COALESCE($5::int, sort_order),
    status = COALESCE($6::cms_status, status),
    starts_at = COALESCE($7::timestamptz, starts_at),
    ends_at = COALESCE($8::timestamptz, ends_at)
WHERE id = $9
RETURNING id, title, image_url, link_url, placement, sort_order, status, starts_at, ends_at, created_at, updated_at
`

type AdminUpdateBannerParams struct {
	Title     pgtype.Text        `db:"title" json:"title"`
	ImageUrl  pgtype.Text        `db:"image_url" json:"image_url"`
	LinkUrl   pgtype.Text        `db:"link_url" json:"link_url"`
	Placement pgtype.Text        `db:"placement" json:"placement"`
	SortOrder pgtype.Int4        `db:"sort_order" json:"sort_order"`
	Status    interface{}        `db:"status" json:"status"`
	StartsAt  pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt    pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	ID        pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) AdminUpdateBanner(ctx context.Context, arg AdminUpdateBannerParams) (CmsBanner, error) {
	row := q.db.QueryRow(ctx, adminUpdateBanner,
		arg.Title,
		arg.ImageUrl,
		arg.LinkUrl,
		arg.Placement,
		arg.SortOrder,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	var i CmsBanner
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.Placement,
		&i.SortOrder,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpdateFaq = `-- name: AdminUpdateFaq :one
UPDATE cms_faqs
SET question = COALESCE($1::text, question),
    answer = COALESCE($2::text, answer),
    category = COALESCE($3::text, category),
    sort_order = COALESCE($4::int, sort_order),
    status = COALESCE($5::cms_status, status)
WHERE id = $6
RETURNING id, question, answer, category, sort_order, status, created_at, updated_at
`

type AdminUpdateFaqParams struct {
	Question  pgtype.Text `db:"question" json:"question"`
	Answer    pgtype.Text `db:"answer" json:"answer"`
	Category  pgtype.Text `db:"category" json:"category"`
	SortOrder pgtype.Int4 `db:"sort_order" json:"sort_order"`
	Status    interface{} `db:"status" json:"status"`
	ID        pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) AdminUpdateFaq(ctx context.Context, arg AdminUpdateFaqParams) (CmsFaq, error) {
	row := q.db.QueryRow(ctx, adminUpdateFaq,
		arg.Question,
		arg.Answer,
		arg.Category,
		arg.SortOrder,
		arg.Status,
		arg.ID,
	)
	var i CmsFaq
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.Category,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpdatePage = `-- name: AdminUpdatePage :one
UPDATE cms_pages
SET slug = COALESCE($1::text, slug),
    title = COALESCE($2::text, title),
    body = COALESCE($3::text, body),
    status = COALESCE($4::cms_status, status),
    published_at = COALESCE($5::timestamptz, published_at),
    updated_by = COALESCE($6::uuid, updated_by)
WHERE id = $7
RETURNING id, slug, title, body, status, published_at, created_by, updated_by, created_at, updated_at
`

type AdminUpdatePageParams struct {
	Slug        pgtype.Text        `db:"slug" json:"slug"`
	Title       pgtype.Text        `db:"title" json:"title"`
	Body        pgtype.Text        `db:"body" json:"body"`
	Status      interface{}        `db:"status" json:"status"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	ActorUserID pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	ID          pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) AdminUpdatePage(ctx context.Context, arg AdminUpdatePageParams) (CmsPage, error) {
	row := q.db.QueryRow(ctx, adminUpdatePage,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.PublishedAt,
		arg.ActorUserID,
		arg.ID,
	)
	var i CmsPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
