// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package rbacstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminAddPermissionToRole(ctx context.Context, arg AdminAddPermissionToRoleParams) error
	AdminClearPermissionsForRole(ctx context.Context, roleID pgtype.UUID) error
	AdminCreatePermission(ctx context.Context, arg AdminCreatePermissionParams) (Permission, error)
	AdminCreateRole(ctx context.Context, arg AdminCreateRoleParams) (Role, error)
	AdminDeletePermission(ctx context.Context, id pgtype.UUID) error
	AdminDeleteRole(ctx context.Context, id pgtype.UUID) error
	AdminListPermissions(ctx context.Context) ([]Permission, error)
	AdminListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error)
	AdminListRoles(ctx context.Context) ([]Role, error)
	AdminRemovePermissionFromRole(ctx context.Context, arg AdminRemovePermissionFromRoleParams) error
	AdminUpdatePermission(ctx context.Context, arg AdminUpdatePermissionParams) (Permission, error)
	AdminUpdateRole(ctx context.Context, arg AdminUpdateRoleParams) (Role, error)
	AssignUserRoleByRoleName(ctx context.Context, arg AssignUserRoleByRoleNameParams) error
	ClearUserRoles(ctx context.Context, userID pgtype.UUID) error
	ListCasbinRules(ctx context.Context) ([]CasbinRule, error)
	ListRoleNamesForUser(ctx context.Context, userID pgtype.UUID) ([]string, error)
	RemoveUserRoleByRoleName(ctx context.Context, arg RemoveUserRoleByRoleNameParams) error
}

var _ Querier = (*Queries)(nil)
