// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package rbacstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminAddPermissionToRole = `-- name: AdminAddPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AdminAddPermissionToRoleParams struct {
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
}

func (q *Queries) AdminAddPermissionToRole(ctx context.Context, arg AdminAddPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, adminAddPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const adminClearPermissionsForRole = `-- name: AdminClearPermissionsForRole :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) AdminClearPermissionsForRole(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminClearPermissionsForRole, roleID)
	return err
}

const adminCreatePermission = `-- name: AdminCreatePermission :one
INSERT INTO permissions (key, description)
VALUES ($1, $2)
RETURNING id, key, description, created_at
`

type AdminCreatePermissionParams struct {
	Key         string      `db:"key" json:"key"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) AdminCreatePermission(ctx context.Context, arg AdminCreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, adminCreatePermission, arg.Key, arg.Description)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const adminCreateRole = `-- name: AdminCreateRole :one
INSERT INTO roles (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at
`

type AdminCreateRoleParams struct {
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) AdminCreateRole(ctx context.Context, arg AdminCreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, adminCreateRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const adminDeletePermission = `-- name: AdminDeletePermission :exec
DELETE FROM permissions
WHERE id = $1
`

func (q *Queries) AdminDeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeletePermission, id)
	return err
}

const adminDeleteRole = `-- name: AdminDeleteRole :exec
DELETE FROM roles
WHERE id = $1
`

func (q *Queries) AdminDeleteRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteRole, id)
	return err
}

const adminListPermissions = `-- name: AdminListPermissions :many
SELECT id, key, description, created_at
FROM permissions
ORDER BY key ASC
`

func (q *Queries) AdminListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, adminListPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPermissionsForRole = `-- name: AdminListPermissionsForRole :many
SELECT p.id, p.key, p.description, p.created_at
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.key ASC
`

func (q *Queries) AdminListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, adminListPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRoles = `-- name: AdminListRoles :many
SELECT id, name, description, created_at
FROM roles
ORDER BY name ASC
`

func (q *Queries) AdminListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, adminListRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRemovePermissionFromRole = `-- name: AdminRemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1
  AND permission_id = $2
`

type AdminRemovePermissionFromRoleParams struct {
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
}

func (q *Queries) AdminRemovePermissionFromRole(ctx context.Context, arg AdminRemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, adminRemovePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const adminUpdatePermission = `-- name: AdminUpdatePermission :one
UPDATE permissions
SET key = COALESCE($1::text, key),
    description = COALESCE($2::text, description)
WHERE id = $3
RETURNING id, key, description, created_at
`

type AdminUpdatePermissionParams struct {
	Key         pgtype.Text `db:"key" json:"key"`
	Description pgtype.Text `db:"description" json:"description"`
	ID          pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) AdminUpdatePermission(ctx context.Context, arg AdminUpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, adminUpdatePermission, arg.Key, arg.Description, arg.ID)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const adminUpdateRole = `-- name: AdminUpdateRole :one
UPDATE roles
SET name = COALESCE($1::text, name),
    description = COALESCE($2::text, description)
WHERE id = $3
RETURNING id, name, description, created_at
`

type AdminUpdateRoleParams struct {
	Name        pgtype.Text `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	ID          pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) AdminUpdateRole(ctx context.Context, arg AdminUpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, adminUpdateRole, arg.Name, arg.Description, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const assignUserRoleByRoleName = `-- name: AssignUserRoleByRoleName :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, r.id
FROM roles r
WHERE r.name = $2
ON CONFLICT DO NOTHING
`

type AssignUserRoleByRoleNameParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	RoleName string      `db:"role_name" json:"role_name"`
}

func (q *Queries) AssignUserRoleByRoleName(ctx context.Context, arg AssignUserRoleByRoleNameParams) error {
	_, err := q.db.Exec(ctx, assignUserRoleByRoleName, arg.UserID, arg.RoleName)
	return err
}

const clearUserRoles = `-- name: ClearUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) ClearUserRoles(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearUserRoles, userID)
	return err
}

const listCasbinRules = `-- name: ListCasbinRules :many
SELECT id, ptype, v0, v1, v2, v3, v4, v5
FROM casbin_rule
ORDER BY id ASC
`

func (q *Queries) ListCasbinRules(ctx context.Context) ([]CasbinRule, error) {
	rows, err := q.db.Query(ctx, listCasbinRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CasbinRule
	for rows.Next() {
		var i CasbinRule
		if err := rows.Scan(
			&i.ID,
			&i.Ptype,
			&i.V0,
			&i.V1,
			&i.V2,
			&i.V3,
			&i.V4,
			&i.V5,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleNamesForUser = `-- name: ListRoleNamesForUser :many
SELECT r.name
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name ASC
`

func (q *Queries) ListRoleNamesForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleNamesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserRoleByRoleName = `-- name: RemoveUserRoleByRoleName :exec
DELETE FROM user_roles ur
USING roles r
WHERE ur.role_id = r.id
  AND ur.user_id = $1
  AND r.name = $2
`

type RemoveUserRoleByRoleNameParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	RoleName string      `db:"role_name" json:"role_name"`
}

func (q *Queries) RemoveUserRoleByRoleName(ctx context.Context, arg RemoveUserRoleByRoleNameParams) error {
	_, err := q.db.Exec(ctx, removeUserRoleByRoleName, arg.UserID, arg.RoleName)
	return err
}
