// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package userstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]User, error)
	AdminUpdateUserStatus(ctx context.Context, arg AdminUpdateUserStatusParams) (User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserDevice(ctx context.Context, arg CreateUserDeviceParams) (UserDevice, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserProfileByUserID(ctx context.Context, userID pgtype.UUID) (UserProfile, error)
	ListUserAddresses(ctx context.Context, userID pgtype.UUID) ([]UserAddress, error)
	ListUserDevicesForUser(ctx context.Context, userID pgtype.UUID) ([]UserDevice, error)
	RevokeUserDevice(ctx context.Context, arg RevokeUserDeviceParams) error
	SetUserEmailVerified(ctx context.Context, id pgtype.UUID) error
	SetUserPhoneVerified(ctx context.Context, id pgtype.UUID) error
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	UpdateUserContact(ctx context.Context, arg UpdateUserContactParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
