// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package userstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(1)::bigint
FROM users u
WHERE u.deleted_at IS NULL
  AND ($1::text IS NULL OR u.status = $1::text)
  AND ($2::text IS NULL OR u.email ILIKE ('%' || $2::text || '%'))
`

type AdminCountUsersParams struct {
	Status pgtype.Text `db:"status" json:"status"`
	Q      pgtype.Text `db:"q" json:"q"`
}

func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, arg.Status, arg.Q)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, email, phone, password_hash, status, email_verified, phone_verified, last_login_at, deleted_at, created_at, updated_at
FROM users u
WHERE u.deleted_at IS NULL
  AND ($1::text IS NULL OR u.status = $1::text)
  AND ($2::text IS NULL OR u.email ILIKE ('%' || $2::text || '%'))
ORDER BY u.created_at DESC
LIMIT $4 OFFSET $3
`

type AdminListUsersParams struct {
	Status pgtype.Text `db:"status" json:"status"`
	Q      pgtype.Text `db:"q" json:"q"`
	Offset int32       `db:"offset" json:"offset"`
	Limit  int32       `db:"limit" json:"limit"`
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Status,
		arg.Q,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Status,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.LastLoginAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateUserStatus = `-- name: AdminUpdateUserStatus :one
UPDATE users
SET status = $1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, email, phone, password_hash, status, email_verified, phone_verified, last_login_at, deleted_at, created_at, updated_at
`

type AdminUpdateUserStatusParams struct {
	Status interface{} `db:"status" json:"status"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) AdminUpdateUserStatus(ctx context.Context, arg AdminUpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, phone, password_hash, status)
VALUES ($1, $2, $3, COALESCE($4, 'active'))
RETURNING id, email, phone, password_hash, status, email_verified, phone_verified, last_login_at, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        pgtype.Text `db:"email" json:"email"`
	Phone        pgtype.Text `db:"phone" json:"phone"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
	Column4      interface{} `db:"column_4" json:"column_4"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Column4,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserDevice = `-- name: CreateUserDevice :one
INSERT INTO user_devices (user_id, device_id, platform, app_version, push_token, last_seen_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id, device_id) DO UPDATE
SET platform = EXCLUDED.platform,
    app_version = EXCLUDED.app_version,
    push_token = EXCLUDED.push_token,
    last_seen_at = now(),
    revoked_at = NULL
RETURNING id, user_id, device_id, platform, app_version, push_token, last_seen_at, revoked_at, created_at, updated_at
`

type CreateUserDeviceParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID   string      `db:"device_id" json:"device_id"`
	Platform   string      `db:"platform" json:"platform"`
	AppVersion pgtype.Text `db:"app_version" json:"app_version"`
	PushToken  pgtype.Text `db:"push_token" json:"push_token"`
}

func (q *Queries) CreateUserDevice(ctx context.Context, arg CreateUserDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, createUserDevice,
		arg.UserID,
		arg.DeviceID,
		arg.Platform,
		arg.AppVersion,
		arg.PushToken,
	)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.AppVersion,
		&i.PushToken,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, password_hash, status, email_verified, phone_verified, last_login_at, deleted_at, created_at, updated_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, password_hash, status, email_verified, phone_verified, last_login_at, deleted_at, created_at, updated_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT id, user_id, first_name, last_name, display_name, avatar_url, gender, birthdate, language, country_code, timezone, created_at, updated_at
FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Gender,
		&i.Birthdate,
		&i.Language,
		&i.CountryCode,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAddresses = `-- name: ListUserAddresses :many
SELECT id, user_id, full_name, phone, country, state, city, district, postal_code, address_line1, address_line2, latitude, longitude, is_default, deleted_at, created_at, updated_at
FROM user_addresses
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListUserAddresses(ctx context.Context, userID pgtype.UUID) ([]UserAddress, error) {
	rows, err := q.db.Query(ctx, listUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAddress
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Phone,
			&i.Country,
			&i.State,
			&i.City,
			&i.District,
			&i.PostalCode,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Latitude,
			&i.Longitude,
			&i.IsDefault,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDevicesForUser = `-- name: ListUserDevicesForUser :many
SELECT id, user_id, device_id, platform, app_version, push_token, last_seen_at, revoked_at, created_at, updated_at
FROM user_devices
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserDevicesForUser(ctx context.Context, userID pgtype.UUID) ([]UserDevice, error) {
	rows, err := q.db.Query(ctx, listUserDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Platform,
			&i.AppVersion,
			&i.PushToken,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserDevice = `-- name: RevokeUserDevice :exec
UPDATE user_devices
SET revoked_at = now()
WHERE user_id = $1
  AND device_id = $2
  AND revoked_at IS NULL
`

type RevokeUserDeviceParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID string      `db:"device_id" json:"device_id"`
}

func (q *Queries) RevokeUserDevice(ctx context.Context, arg RevokeUserDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeUserDevice, arg.UserID, arg.DeviceID)
	return err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users
SET email_verified = TRUE
WHERE id = $1
`

func (q *Queries) SetUserEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, id)
	return err
}

const setUserPhoneVerified = `-- name: SetUserPhoneVerified :exec
UPDATE users
SET phone_verified = TRUE
WHERE id = $1
`

func (q *Queries) SetUserPhoneVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setUserPhoneVerified, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now(),
    status = 'deleted'
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserContact = `-- name: UpdateUserContact :one
UPDATE users
SET email = COALESCE($1::citext, email),
    phone = COALESCE($2::text, phone),
    email_verified = CASE
      WHEN $1::citext IS NOT NULL AND $1::citext IS DISTINCT FROM email THEN FALSE
      ELSE email_verified
    END,
    phone_verified = CASE
      WHEN $2::text IS NOT NULL AND $2::text IS DISTINCT FROM phone THEN FALSE
      ELSE phone_verified
    END
WHERE id = $3
  AND deleted_at IS NULL
RETURNING id, email, phone, password_hash, status, email_verified, phone_verified, last_login_at, deleted_at, created_at, updated_at
`

type UpdateUserContactParams struct {
	Email pgtype.Text `db:"email" json:"email"`
	Phone pgtype.Text `db:"phone" json:"phone"`
	ID    pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateUserContact(ctx context.Context, arg UpdateUserContactParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserContact, arg.Email, arg.Phone, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordHashParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
INSERT INTO user_profiles (user_id, first_name, last_name, display_name, avatar_url, gender, birthdate, language, country_code, timezone)
VALUES ($1, $2, $3, $4, $5, $6, $7, COALESCE($8, 'en'), $9, $10)
ON CONFLICT (user_id) DO UPDATE
SET first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    gender = EXCLUDED.gender,
    birthdate = EXCLUDED.birthdate,
    language = EXCLUDED.language,
    country_code = EXCLUDED.country_code,
    timezone = EXCLUDED.timezone
RETURNING id, user_id, first_name, last_name, display_name, avatar_url, gender, birthdate, language, country_code, timezone, created_at, updated_at
`

type UpdateUserProfileParams struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	FirstName   pgtype.Text `db:"first_name" json:"first_name"`
	LastName    pgtype.Text `db:"last_name" json:"last_name"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
	Gender      pgtype.Text `db:"gender" json:"gender"`
	Birthdate   pgtype.Date `db:"birthdate" json:"birthdate"`
	Column8     interface{} `db:"column_8" json:"column_8"`
	CountryCode pgtype.Text `db:"country_code" json:"country_code"`
	Timezone    pgtype.Text `db:"timezone" json:"timezone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Gender,
		arg.Birthdate,
		arg.Column8,
		arg.CountryCode,
		arg.Timezone,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Gender,
		&i.Birthdate,
		&i.Language,
		&i.CountryCode,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
