// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notifystore

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminActivityLog struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	AdminUserID pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	Action      string             `db:"action" json:"action"`
	EntityType  pgtype.Text        `db:"entity_type" json:"entity_type"`
	EntityID    pgtype.UUID        `db:"entity_id" json:"entity_id"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent   pgtype.Text        `db:"user_agent" json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AdminMetricsDaily struct {
	MetricDate  pgtype.Date        `db:"metric_date" json:"metric_date"`
	EventName   string             `db:"event_name" json:"event_name"`
	TotalCount  int64              `db:"total_count" json:"total_count"`
	UniqueUsers int64              `db:"unique_users" json:"unique_users"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AnalyticsEventQueue struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	EventLogID  pgtype.UUID        `db:"event_log_id" json:"event_log_id"`
	Status      string             `db:"status" json:"status"`
	Attempts    int32              `db:"attempts" json:"attempts"`
	LastError   pgtype.Text        `db:"last_error" json:"last_error"`
	AvailableAt pgtype.Timestamptz `db:"available_at" json:"available_at"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuditLog struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ActorUserID pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	Action      string             `db:"action" json:"action"`
	EntityType  pgtype.Text        `db:"entity_type" json:"entity_type"`
	EntityID    pgtype.UUID        `db:"entity_id" json:"entity_id"`
	OldValues   []byte             `db:"old_values" json:"old_values"`
	NewValues   []byte             `db:"new_values" json:"new_values"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent   pgtype.Text        `db:"user_agent" json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Brand struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	LogoUrl   pgtype.Text        `db:"logo_url" json:"logo_url"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Cart struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	SessionID pgtype.Text        `db:"session_id" json:"session_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	VoucherID pgtype.UUID        `db:"voucher_id" json:"voucher_id"`
}

type CartItem struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CartID    pgtype.UUID        `db:"cart_id" json:"cart_id"`
	ProductID pgtype.UUID        `db:"product_id" json:"product_id"`
	VariantID pgtype.UUID        `db:"variant_id" json:"variant_id"`
	Quantity  int32              `db:"quantity" json:"quantity"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Selected  bool               `db:"selected" json:"selected"`
}

type CasbinRule struct {
	ID    int32       `db:"id" json:"id"`
	Ptype string      `db:"ptype" json:"ptype"`
	V0    pgtype.Text `db:"v0" json:"v0"`
	V1    pgtype.Text `db:"v1" json:"v1"`
	V2    pgtype.Text `db:"v2" json:"v2"`
	V3    pgtype.Text `db:"v3" json:"v3"`
	V4    pgtype.Text `db:"v4" json:"v4"`
	V5    pgtype.Text `db:"v5" json:"v5"`
}

type Category struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ParentID  pgtype.UUID        `db:"parent_id" json:"parent_id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	ImageUrl  pgtype.Text        `db:"image_url" json:"image_url"`
	SortOrder int32              `db:"sort_order" json:"sort_order"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ChatConversation struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	BuyerID       pgtype.UUID        `db:"buyer_id" json:"buyer_id"`
	SellerID      pgtype.UUID        `db:"seller_id" json:"seller_id"`
	LastMessageAt pgtype.Timestamptz `db:"last_message_at" json:"last_message_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ChatMessage struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Message        pgtype.Text        `db:"message" json:"message"`
	AttachmentUrl  pgtype.Text        `db:"attachment_url" json:"attachment_url"`
	ReadAt         pgtype.Timestamptz `db:"read_at" json:"read_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CheckoutSession struct {
	ID                     pgtype.UUID        `db:"id" json:"id"`
	UserID                 pgtype.UUID        `db:"user_id" json:"user_id"`
	CartID                 pgtype.UUID        `db:"cart_id" json:"cart_id"`
	Status                 string             `db:"status" json:"status"`
	Currency               string             `db:"currency" json:"currency"`
	SubtotalCents          int64              `db:"subtotal_cents" json:"subtotal_cents"`
	DiscountCents          int64              `db:"discount_cents" json:"discount_cents"`
	ShippingCents          int64              `db:"shipping_cents" json:"shipping_cents"`
	TaxCents               int64              `db:"tax_cents" json:"tax_cents"`
	TotalCents             int64              `db:"total_cents" json:"total_cents"`
	ShippingAddress        []byte             `db:"shipping_address" json:"shipping_address"`
	BillingAddress         []byte             `db:"billing_address" json:"billing_address"`
	PaymentMethod          pgtype.Text        `db:"payment_method" json:"payment_method"`
	SelectedShippingOption []byte             `db:"selected_shipping_option" json:"selected_shipping_option"`
	ExpiresAt              pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CompletedAt            pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	VoucherID              pgtype.UUID        `db:"voucher_id" json:"voucher_id"`
}

type CheckoutSessionItem struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	CheckoutSessionID pgtype.UUID        `db:"checkout_session_id" json:"checkout_session_id"`
	SellerID          pgtype.UUID        `db:"seller_id" json:"seller_id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	VariantID         pgtype.UUID        `db:"variant_id" json:"variant_id"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	UnitPriceCents    int64              `db:"unit_price_cents" json:"unit_price_cents"`
	TotalPriceCents   int64              `db:"total_price_cents" json:"total_price_cents"`
	Currency          string             `db:"currency" json:"currency"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CmsAnnouncement struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	Body      string             `db:"body" json:"body"`
	Audience  string             `db:"audience" json:"audience"`
	Status    interface{}        `db:"status" json:"status"`
	StartsAt  pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt    pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CmsBanner struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	ImageUrl  string             `db:"image_url" json:"image_url"`
	LinkUrl   pgtype.Text        `db:"link_url" json:"link_url"`
	Placement string             `db:"placement" json:"placement"`
	SortOrder int32              `db:"sort_order" json:"sort_order"`
	Status    interface{}        `db:"status" json:"status"`
	StartsAt  pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt    pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CmsFaq struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Question  string             `db:"question" json:"question"`
	Answer    string             `db:"answer" json:"answer"`
	Category  pgtype.Text        `db:"category" json:"category"`
	SortOrder int32              `db:"sort_order" json:"sort_order"`
	Status    interface{}        `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CmsPage struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	Title       string             `db:"title" json:"title"`
	Body        string             `db:"body" json:"body"`
	Status      interface{}        `db:"status" json:"status"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedBy   pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedBy   pgtype.UUID        `db:"updated_by" json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmailVerificationToken struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Email      string             `db:"email" json:"email"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EventLog struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	EventName  string             `db:"event_name" json:"event_name"`
	EntityType pgtype.Text        `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID        `db:"entity_id" json:"entity_id"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type FeatureFlag struct {
	Key         string             `db:"key" json:"key"`
	Description pgtype.Text        `db:"description" json:"description"`
	Enabled     bool               `db:"enabled" json:"enabled"`
	Rules       []byte             `db:"rules" json:"rules"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IdempotencyKey struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Key          string             `db:"key" json:"key"`
	ScopeHash    string             `db:"scope_hash" json:"scope_hash"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	RequestHash  pgtype.Text        `db:"request_hash" json:"request_hash"`
	ResponseBody []byte             `db:"response_body" json:"response_body"`
	StatusCode   pgtype.Int4        `db:"status_code" json:"status_code"`
	LockedUntil  pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type InventoryItem struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	VariantID         pgtype.UUID        `db:"variant_id" json:"variant_id"`
	QuantityAvailable int32              `db:"quantity_available" json:"quantity_available"`
	QuantityReserved  int32              `db:"quantity_reserved" json:"quantity_reserved"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type InventoryMovement struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	InventoryItemID pgtype.UUID        `db:"inventory_item_id" json:"inventory_item_id"`
	MovementType    interface{}        `db:"movement_type" json:"movement_type"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	Reason          pgtype.Text        `db:"reason" json:"reason"`
	ReferenceType   pgtype.Text        `db:"reference_type" json:"reference_type"`
	ReferenceID     pgtype.UUID        `db:"reference_id" json:"reference_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ActorUserID     pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	BeforeAvailable pgtype.Int4        `db:"before_available" json:"before_available"`
	AfterAvailable  pgtype.Int4        `db:"after_available" json:"after_available"`
	BeforeReserved  pgtype.Int4        `db:"before_reserved" json:"before_reserved"`
	AfterReserved   pgtype.Int4        `db:"after_reserved" json:"after_reserved"`
}

type InventoryReservation struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	InventoryItemID   pgtype.UUID        `db:"inventory_item_id" json:"inventory_item_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	CheckoutSessionID pgtype.UUID        `db:"checkout_session_id" json:"checkout_session_id"`
	OrderID           pgtype.UUID        `db:"order_id" json:"order_id"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ReleasedAt        pgtype.Timestamptz `db:"released_at" json:"released_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ManualWavePaymentApproval struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	PaymentID   pgtype.UUID        `db:"payment_id" json:"payment_id"`
	Reference   string             `db:"reference" json:"reference"`
	SenderPhone pgtype.Text        `db:"sender_phone" json:"sender_phone"`
	AmountCents int64              `db:"amount_cents" json:"amount_cents"`
	Currency    string             `db:"currency" json:"currency"`
	ApprovedBy  pgtype.UUID        `db:"approved_by" json:"approved_by"`
	ApprovedAt  pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	RejectedBy  pgtype.UUID        `db:"rejected_by" json:"rejected_by"`
	RejectedAt  pgtype.Timestamptz `db:"rejected_at" json:"rejected_at"`
	Note        pgtype.Text        `db:"note" json:"note"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MediaFile struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OwnerUserID pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	Url         string             `db:"url" json:"url"`
	Bucket      pgtype.Text        `db:"bucket" json:"bucket"`
	ObjectKey   pgtype.Text        `db:"object_key" json:"object_key"`
	MimeType    pgtype.Text        `db:"mime_type" json:"mime_type"`
	SizeBytes   pgtype.Int8        `db:"size_bytes" json:"size_bytes"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ModerationCase struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ReportID   pgtype.UUID        `db:"report_id" json:"report_id"`
	AssignedTo pgtype.UUID        `db:"assigned_to" json:"assigned_to"`
	Status     interface{}        `db:"status" json:"status"`
	Resolution pgtype.Text        `db:"resolution" json:"resolution"`
	ResolvedAt pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ModerationReport struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ReporterUserID pgtype.UUID        `db:"reporter_user_id" json:"reporter_user_id"`
	TargetType     string             `db:"target_type" json:"target_type"`
	TargetID       pgtype.UUID        `db:"target_id" json:"target_id"`
	Reason         string             `db:"reason" json:"reason"`
	Status         interface{}        `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Notification struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Type      string             `db:"type" json:"type"`
	Title     string             `db:"title" json:"title"`
	Body      pgtype.Text        `db:"body" json:"body"`
	Data      []byte             `db:"data" json:"data"`
	ReadAt    pgtype.Timestamptz `db:"read_at" json:"read_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type NotificationPreference struct {
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	EmailEnabled     bool               `db:"email_enabled" json:"email_enabled"`
	SmsEnabled       bool               `db:"sms_enabled" json:"sms_enabled"`
	PushEnabled      bool               `db:"push_enabled" json:"push_enabled"`
	MarketingEnabled bool               `db:"marketing_enabled" json:"marketing_enabled"`
	QuietHours       []byte             `db:"quiet_hours" json:"quiet_hours"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OauthIdentity struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	Provider       string             `db:"provider" json:"provider"`
	ProviderUserID string             `db:"provider_user_id" json:"provider_user_id"`
	Email          pgtype.Text        `db:"email" json:"email"`
	RawProfile     []byte             `db:"raw_profile" json:"raw_profile"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Order struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	OrderNumber       string             `db:"order_number" json:"order_number"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	CheckoutSessionID pgtype.UUID        `db:"checkout_session_id" json:"checkout_session_id"`
	Status            interface{}        `db:"status" json:"status"`
	SubtotalCents     int64              `db:"subtotal_cents" json:"subtotal_cents"`
	DiscountCents     int64              `db:"discount_cents" json:"discount_cents"`
	ShippingCents     int64              `db:"shipping_cents" json:"shipping_cents"`
	TaxCents          int64              `db:"tax_cents" json:"tax_cents"`
	TotalCents        int64              `db:"total_cents" json:"total_cents"`
	Currency          string             `db:"currency" json:"currency"`
	ShippingAddress   []byte             `db:"shipping_address" json:"shipping_address"`
	BillingAddress    []byte             `db:"billing_address" json:"billing_address"`
	PlacedAt          pgtype.Timestamptz `db:"placed_at" json:"placed_at"`
	PaidAt            pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	CancelledAt       pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrderInvoice struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	OrderID       pgtype.UUID        `db:"order_id" json:"order_id"`
	InvoiceNumber string             `db:"invoice_number" json:"invoice_number"`
	Status        string             `db:"status" json:"status"`
	Payload       []byte             `db:"payload" json:"payload"`
	GeneratedAt   pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OrderItem struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	OrderID         pgtype.UUID        `db:"order_id" json:"order_id"`
	SellerID        pgtype.UUID        `db:"seller_id" json:"seller_id"`
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	VariantID       pgtype.UUID        `db:"variant_id" json:"variant_id"`
	ProductName     string             `db:"product_name" json:"product_name"`
	VariantName     pgtype.Text        `db:"variant_name" json:"variant_name"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	UnitPriceCents  int64              `db:"unit_price_cents" json:"unit_price_cents"`
	TotalPriceCents int64              `db:"total_price_cents" json:"total_price_cents"`
	Currency        string             `db:"currency" json:"currency"`
	Status          interface{}        `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OrderStatusHistory struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	OrderID   pgtype.UUID        `db:"order_id" json:"order_id"`
	OldStatus interface{}        `db:"old_status" json:"old_status"`
	NewStatus interface{}        `db:"new_status" json:"new_status"`
	Note      pgtype.Text        `db:"note" json:"note"`
	CreatedBy pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PasswordResetToken struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Payment struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	OrderID           pgtype.UUID        `db:"order_id" json:"order_id"`
	PaymentMethodID   pgtype.UUID        `db:"payment_method_id" json:"payment_method_id"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderPaymentID pgtype.Text        `db:"provider_payment_id" json:"provider_payment_id"`
	Status            interface{}        `db:"status" json:"status"`
	AmountCents       int64              `db:"amount_cents" json:"amount_cents"`
	Currency          string             `db:"currency" json:"currency"`
	IdempotencyKey    pgtype.Text        `db:"idempotency_key" json:"idempotency_key"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	PaidAt            pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	FailedAt          pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PaymentMethod struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	Provider       string             `db:"provider" json:"provider"`
	Type           string             `db:"type" json:"type"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	TokenReference pgtype.Text        `db:"token_reference" json:"token_reference"`
	IsDefault      bool               `db:"is_default" json:"is_default"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PaymentWebhookEvent struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Provider    string             `db:"provider" json:"provider"`
	EventID     string             `db:"event_id" json:"event_id"`
	EventType   pgtype.Text        `db:"event_type" json:"event_type"`
	Payload     []byte             `db:"payload" json:"payload"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Permission struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Key         string             `db:"key" json:"key"`
	Description pgtype.Text        `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PhoneOtpAttempt struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Phone       string             `db:"phone" json:"phone"`
	OtpHash     string             `db:"otp_hash" json:"otp_hash"`
	Purpose     string             `db:"purpose" json:"purpose"`
	Attempts    int32              `db:"attempts" json:"attempts"`
	MaxAttempts int32              `db:"max_attempts" json:"max_attempts"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	VerifiedAt  pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PlatformSetting struct {
	Key         string             `db:"key" json:"key"`
	Value       []byte             `db:"value" json:"value"`
	Description pgtype.Text        `db:"description" json:"description"`
	IsPublic    bool               `db:"is_public" json:"is_public"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PodPaymentCapture struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	PaymentID   pgtype.UUID        `db:"payment_id" json:"payment_id"`
	CapturedBy  pgtype.UUID        `db:"captured_by" json:"captured_by"`
	AmountCents int64              `db:"amount_cents" json:"amount_cents"`
	Currency    string             `db:"currency" json:"currency"`
	CapturedAt  pgtype.Timestamptz `db:"captured_at" json:"captured_at"`
	Note        pgtype.Text        `db:"note" json:"note"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Product struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	SearchVector     interface{}        `db:"search_vector" json:"search_vector"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

type ProductImage struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ProductID pgtype.UUID        `db:"product_id" json:"product_id"`
	Url       string             `db:"url" json:"url"`
	AltText   pgtype.Text        `db:"alt_text" json:"alt_text"`
	SortOrder int32              `db:"sort_order" json:"sort_order"`
	IsPrimary bool               `db:"is_primary" json:"is_primary"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProductReview struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ProductID          pgtype.UUID        `db:"product_id" json:"product_id"`
	OrderItemID        pgtype.UUID        `db:"order_item_id" json:"order_item_id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Rating             int32              `db:"rating" json:"rating"`
	Title              pgtype.Text        `db:"title" json:"title"`
	Body               pgtype.Text        `db:"body" json:"body"`
	IsVerifiedPurchase bool               `db:"is_verified_purchase" json:"is_verified_purchase"`
	IsHidden           bool               `db:"is_hidden" json:"is_hidden"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SellerReply        pgtype.Text        `db:"seller_reply" json:"seller_reply"`
	SellerReplyAt      pgtype.Timestamptz `db:"seller_reply_at" json:"seller_reply_at"`
	SellerReplyBy      pgtype.UUID        `db:"seller_reply_by" json:"seller_reply_by"`
}

type ProductReviewImage struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	ReviewID  pgtype.UUID `db:"review_id" json:"review_id"`
	Url       string      `db:"url" json:"url"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
}

type ProductVariant struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	ProductID           pgtype.UUID        `db:"product_id" json:"product_id"`
	Sku                 string             `db:"sku" json:"sku"`
	Name                pgtype.Text        `db:"name" json:"name"`
	PriceCents          int64              `db:"price_cents" json:"price_cents"`
	CompareAtPriceCents pgtype.Int8        `db:"compare_at_price_cents" json:"compare_at_price_cents"`
	Currency            string             `db:"currency" json:"currency"`
	WeightGrams         pgtype.Int4        `db:"weight_grams" json:"weight_grams"`
	IsActive            bool               `db:"is_active" json:"is_active"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProductVariantOptionValue struct {
	VariantID     pgtype.UUID `db:"variant_id" json:"variant_id"`
	OptionValueID pgtype.UUID `db:"option_value_id" json:"option_value_id"`
}

type PushToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	Platform  string             `db:"platform" json:"platform"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SessionID pgtype.UUID        `db:"session_id" json:"session_id"`
}

type Refund struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OrderID     pgtype.UUID        `db:"order_id" json:"order_id"`
	PaymentID   pgtype.UUID        `db:"payment_id" json:"payment_id"`
	RequestedBy pgtype.UUID        `db:"requested_by" json:"requested_by"`
	Status      interface{}        `db:"status" json:"status"`
	Reason      pgtype.Text        `db:"reason" json:"reason"`
	AmountCents int64              `db:"amount_cents" json:"amount_cents"`
	Currency    string             `db:"currency" json:"currency"`
	ReviewedBy  pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt  pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ReturnRequest struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OrderID     pgtype.UUID        `db:"order_id" json:"order_id"`
	OrderItemID pgtype.UUID        `db:"order_item_id" json:"order_item_id"`
	RequestedBy pgtype.UUID        `db:"requested_by" json:"requested_by"`
	Status      interface{}        `db:"status" json:"status"`
	Reason      pgtype.Text        `db:"reason" json:"reason"`
	Quantity    int32              `db:"quantity" json:"quantity"`
	ReviewedBy  pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt  pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ReceivedAt  pgtype.Timestamptz `db:"received_at" json:"received_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ReviewReport struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ReviewID       pgtype.UUID        `db:"review_id" json:"review_id"`
	ReporterUserID pgtype.UUID        `db:"reporter_user_id" json:"reporter_user_id"`
	Reason         string             `db:"reason" json:"reason"`
	Status         interface{}        `db:"status" json:"status"`
	ResolvedBy     pgtype.UUID        `db:"resolved_by" json:"resolved_by"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ReviewVote struct {
	ReviewID  pgtype.UUID        `db:"review_id" json:"review_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Vote      int32              `db:"vote" json:"vote"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
}

type SearchClickEvent struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	SessionID pgtype.Text        `db:"session_id" json:"session_id"`
	Query     string             `db:"query" json:"query"`
	ProductID pgtype.UUID        `db:"product_id" json:"product_id"`
	Position  pgtype.Int4        `db:"position" json:"position"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SearchRecentQuery struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	SessionID pgtype.Text        `db:"session_id" json:"session_id"`
	Query     string             `db:"query" json:"query"`
	Filters   []byte             `db:"filters" json:"filters"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Seller struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	ApplicationID pgtype.UUID        `db:"application_id" json:"application_id"`
	ShopName      string             `db:"shop_name" json:"shop_name"`
	Slug          string             `db:"slug" json:"slug"`
	Description   pgtype.Text        `db:"description" json:"description"`
	LogoUrl       pgtype.Text        `db:"logo_url" json:"logo_url"`
	BannerUrl     pgtype.Text        `db:"banner_url" json:"banner_url"`
	Status        interface{}        `db:"status" json:"status"`
	Rating        pgtype.Numeric     `db:"rating" json:"rating"`
	TotalSales    int64              `db:"total_sales" json:"total_sales"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Settings      []byte             `db:"settings" json:"settings"`
}

type SellerApplication struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	ShopName        string             `db:"shop_name" json:"shop_name"`
	Slug            string             `db:"slug" json:"slug"`
	BusinessType    pgtype.Text        `db:"business_type" json:"business_type"`
	Country         pgtype.Text        `db:"country" json:"country"`
	Currency        string             `db:"currency" json:"currency"`
	Status          interface{}        `db:"status" json:"status"`
	SubmittedAt     pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	ReviewedBy      pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	RejectionReason pgtype.Text        `db:"rejection_reason" json:"rejection_reason"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SellerBankAccount struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SellerID            pgtype.UUID        `db:"seller_id" json:"seller_id"`
	BankName            string             `db:"bank_name" json:"bank_name"`
	AccountName         string             `db:"account_name" json:"account_name"`
	AccountNumberMasked string             `db:"account_number_masked" json:"account_number_masked"`
	Country             pgtype.Text        `db:"country" json:"country"`
	Currency            string             `db:"currency" json:"currency"`
	IsDefault           bool               `db:"is_default" json:"is_default"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SellerDocument struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SellerApplicationID pgtype.UUID        `db:"seller_application_id" json:"seller_application_id"`
	SellerID            pgtype.UUID        `db:"seller_id" json:"seller_id"`
	DocumentType        string             `db:"document_type" json:"document_type"`
	FileUrl             string             `db:"file_url" json:"file_url"`
	Status              string             `db:"status" json:"status"`
	ReviewedBy          pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt          pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	RejectionReason     pgtype.Text        `db:"rejection_reason" json:"rejection_reason"`
	Metadata            []byte             `db:"metadata" json:"metadata"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SellerPayout struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	AmountCents      int64              `db:"amount_cents" json:"amount_cents"`
	Currency         string             `db:"currency" json:"currency"`
	Status           string             `db:"status" json:"status"`
	Provider         pgtype.Text        `db:"provider" json:"provider"`
	ProviderPayoutID pgtype.Text        `db:"provider_payout_id" json:"provider_payout_id"`
	RequestedAt      pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ProcessedAt      pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type SellerWallet struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SellerID            pgtype.UUID        `db:"seller_id" json:"seller_id"`
	BalanceCents        int64              `db:"balance_cents" json:"balance_cents"`
	PendingBalanceCents int64              `db:"pending_balance_cents" json:"pending_balance_cents"`
	Currency            string             `db:"currency" json:"currency"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SellerWalletTransaction struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	SellerWalletID     pgtype.UUID        `db:"seller_wallet_id" json:"seller_wallet_id"`
	Type               interface{}        `db:"type" json:"type"`
	AmountCents        int64              `db:"amount_cents" json:"amount_cents"`
	BalanceBeforeCents int64              `db:"balance_before_cents" json:"balance_before_cents"`
	BalanceAfterCents  int64              `db:"balance_after_cents" json:"balance_after_cents"`
	ReferenceType      pgtype.Text        `db:"reference_type" json:"reference_type"`
	ReferenceID        pgtype.UUID        `db:"reference_id" json:"reference_id"`
	Description        pgtype.Text        `db:"description" json:"description"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Shipment struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	OrderID          pgtype.UUID        `db:"order_id" json:"order_id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	ProviderID       pgtype.UUID        `db:"provider_id" json:"provider_id"`
	TrackingNumber   pgtype.Text        `db:"tracking_number" json:"tracking_number"`
	LabelUrl         pgtype.Text        `db:"label_url" json:"label_url"`
	ProviderMetadata []byte             `db:"provider_metadata" json:"provider_metadata"`
	Status           interface{}        `db:"status" json:"status"`
	ShippedAt        pgtype.Timestamptz `db:"shipped_at" json:"shipped_at"`
	DeliveredAt      pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ShipmentLabel struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ShipmentID  pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	LabelUrl    string             `db:"label_url" json:"label_url"`
	Format      string             `db:"format" json:"format"`
	GeneratedAt pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
}

type ShipmentTrackingEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ShipmentID pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	Status     string             `db:"status" json:"status"`
	Location   pgtype.Text        `db:"location" json:"location"`
	Message    pgtype.Text        `db:"message" json:"message"`
	EventTime  pgtype.Timestamptz `db:"event_time" json:"event_time"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ShippingProvider struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Code      string             `db:"code" json:"code"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Email         pgtype.Text        `db:"email" json:"email"`
	Phone         pgtype.Text        `db:"phone" json:"phone"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"password_hash"`
	Status        interface{}        `db:"status" json:"status"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified bool               `db:"phone_verified" json:"phone_verified"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserAddress struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	FullName     string             `db:"full_name" json:"full_name"`
	Phone        string             `db:"phone" json:"phone"`
	Country      string             `db:"country" json:"country"`
	State        pgtype.Text        `db:"state" json:"state"`
	City         pgtype.Text        `db:"city" json:"city"`
	District     pgtype.Text        `db:"district" json:"district"`
	PostalCode   pgtype.Text        `db:"postal_code" json:"postal_code"`
	AddressLine1 string             `db:"address_line1" json:"address_line1"`
	AddressLine2 pgtype.Text        `db:"address_line2" json:"address_line2"`
	Latitude     pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude    pgtype.Numeric     `db:"longitude" json:"longitude"`
	IsDefault    bool               `db:"is_default" json:"is_default"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserDevice struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	DeviceID   string             `db:"device_id" json:"device_id"`
	Platform   string             `db:"platform" json:"platform"`
	AppVersion pgtype.Text        `db:"app_version" json:"app_version"`
	PushToken  pgtype.Text        `db:"push_token" json:"push_token"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserProfile struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	FirstName   pgtype.Text        `db:"first_name" json:"first_name"`
	LastName    pgtype.Text        `db:"last_name" json:"last_name"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Gender      pgtype.Text        `db:"gender" json:"gender"`
	Birthdate   pgtype.Date        `db:"birthdate" json:"birthdate"`
	Language    string             `db:"language" json:"language"`
	CountryCode pgtype.Text        `db:"country_code" json:"country_code"`
	Timezone    pgtype.Text        `db:"timezone" json:"timezone"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserRole struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	RoleID pgtype.UUID `db:"role_id" json:"role_id"`
}

type UserSession struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	DeviceID   pgtype.Text        `db:"device_id" json:"device_id"`
	UserAgent  pgtype.Text        `db:"user_agent" json:"user_agent"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	Platform   pgtype.Text        `db:"platform" json:"platform"`
	PushToken  pgtype.Text        `db:"push_token" json:"push_token"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VariantOption struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	Name      string      `db:"name" json:"name"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
}

type VariantOptionValue struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	OptionID  pgtype.UUID `db:"option_id" json:"option_id"`
	Value     string      `db:"value" json:"value"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
}

type Voucher struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	Code             string             `db:"code" json:"code"`
	Title            string             `db:"title" json:"title"`
	Description      pgtype.Text        `db:"description" json:"description"`
	DiscountType     string             `db:"discount_type" json:"discount_type"`
	DiscountValue    int64              `db:"discount_value" json:"discount_value"`
	MinOrderCents    int64              `db:"min_order_cents" json:"min_order_cents"`
	MaxDiscountCents pgtype.Int8        `db:"max_discount_cents" json:"max_discount_cents"`
	UsageLimit       pgtype.Int4        `db:"usage_limit" json:"usage_limit"`
	UsageCount       int32              `db:"usage_count" json:"usage_count"`
	StartsAt         pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt           pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
}

type VoucherRedemption struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	VoucherID     pgtype.UUID        `db:"voucher_id" json:"voucher_id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	OrderID       pgtype.UUID        `db:"order_id" json:"order_id"`
	DiscountCents int64              `db:"discount_cents" json:"discount_cents"`
	RedeemedAt    pgtype.Timestamptz `db:"redeemed_at" json:"redeemed_at"`
}

type Wishlist struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WishlistItem struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	WishlistID pgtype.UUID        `db:"wishlist_id" json:"wishlist_id"`
	ProductID  pgtype.UUID        `db:"product_id" json:"product_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WorkerJobExecution struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	JobRunID   pgtype.UUID        `db:"job_run_id" json:"job_run_id"`
	MessageID  string             `db:"message_id" json:"message_id"`
	Attempt    int32              `db:"attempt" json:"attempt"`
	Status     string             `db:"status" json:"status"`
	Error      pgtype.Text        `db:"error" json:"error"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WorkerJobRun struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	JobType     string             `db:"job_type" json:"job_type"`
	DedupeKey   string             `db:"dedupe_key" json:"dedupe_key"`
	Status      string             `db:"status" json:"status"`
	Attempts    int32              `db:"attempts" json:"attempts"`
	LastError   pgtype.Text        `db:"last_error" json:"last_error"`
	Payload     []byte             `db:"payload" json:"payload"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
