// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package notifystore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT count(*)::bigint
FROM notifications
WHERE user_id = $1
`

func (q *Queries) CountNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::bigint
FROM notifications
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInAppNotification = `-- name: CreateInAppNotification :one
INSERT INTO notifications (user_id, type, title, body, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, data, read_at, created_at
`

type CreateInAppNotificationParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Type   string      `db:"type" json:"type"`
	Title  string      `db:"title" json:"title"`
	Body   pgtype.Text `db:"body" json:"body"`
	Data   []byte      `db:"data" json:"data"`
}

func (q *Queries) CreateInAppNotification(ctx context.Context, arg CreateInAppNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createInAppNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPushToken = `-- name: CreatePushToken :one
INSERT INTO push_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token)
DO UPDATE SET user_id = EXCLUDED.user_id,
              platform = EXCLUDED.platform
RETURNING id, user_id, token, platform, created_at
`

type CreatePushTokenParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Token    string      `db:"token" json:"token"`
	Platform string      `db:"platform" json:"platform"`
}

func (q *Queries) CreatePushToken(ctx context.Context, arg CreatePushTokenParams) (PushToken, error) {
	row := q.db.QueryRow(ctx, createPushToken, arg.UserID, arg.Token, arg.Platform)
	var i PushToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens
WHERE user_id = $1
  AND token = $2
`

type DeletePushTokenParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Token  string      `db:"token" json:"token"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.Exec(ctx, deletePushToken, arg.UserID, arg.Token)
	return err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, email_enabled, sms_enabled, push_enabled, marketing_enabled, quiet_hours, created_at, updated_at
FROM notification_preferences
WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.SmsEnabled,
		&i.PushEnabled,
		&i.MarketingEnabled,
		&i.QuietHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, data, read_at, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushTokens = `-- name: ListPushTokens :many
SELECT id, user_id, token, platform, created_at
FROM push_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPushTokensParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListPushTokens(ctx context.Context, arg ListPushTokensParams) ([]PushToken, error) {
	rows, err := q.db.Query(ctx, listPushTokens, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushToken
	for rows.Next() {
		var i PushToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = now()
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = COALESCE(read_at, now())
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, title, body, data, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (user_id, email_enabled, sms_enabled, push_enabled, marketing_enabled, quiet_hours)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id)
DO UPDATE SET email_enabled = EXCLUDED.email_enabled,
              sms_enabled = EXCLUDED.sms_enabled,
              push_enabled = EXCLUDED.push_enabled,
              marketing_enabled = EXCLUDED.marketing_enabled,
              quiet_hours = EXCLUDED.quiet_hours
RETURNING user_id, email_enabled, sms_enabled, push_enabled, marketing_enabled, quiet_hours, created_at, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID           pgtype.UUID `db:"user_id" json:"user_id"`
	EmailEnabled     bool        `db:"email_enabled" json:"email_enabled"`
	SmsEnabled       bool        `db:"sms_enabled" json:"sms_enabled"`
	PushEnabled      bool        `db:"push_enabled" json:"push_enabled"`
	MarketingEnabled bool        `db:"marketing_enabled" json:"marketing_enabled"`
	QuietHours       []byte      `db:"quiet_hours" json:"quiet_hours"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.EmailEnabled,
		arg.SmsEnabled,
		arg.PushEnabled,
		arg.MarketingEnabled,
		arg.QuietHours,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.SmsEnabled,
		&i.PushEnabled,
		&i.MarketingEnabled,
		&i.QuietHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
