// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notifystore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateInAppNotification(ctx context.Context, arg CreateInAppNotificationParams) (Notification, error)
	CreatePushToken(ctx context.Context, arg CreatePushTokenParams) (PushToken, error)
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error
	GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPushTokens(ctx context.Context, arg ListPushTokensParams) ([]PushToken, error)
	MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error)
}

var _ Querier = (*Queries)(nil)
