// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublicProducts = `-- name: CountPublicProducts :one
SELECT count(*)::bigint
FROM products p
JOIN sellers s ON s.id = p.seller_id
WHERE p.deleted_at IS NULL
  AND p.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
  AND ($1::uuid IS NULL OR p.category_id = $1::uuid)
  AND ($2::uuid IS NULL OR p.brand_id = $2::uuid)
  AND ($3::uuid IS NULL OR p.seller_id = $3::uuid)
  AND ($4::bigint IS NULL OR p.min_price_cents >= $4::bigint)
  AND ($5::bigint IS NULL OR p.max_price_cents <= $5::bigint)
  AND (
    $6::text IS NULL
    OR $6::text = ''
    OR p.search_vector @@ plainto_tsquery('simple', $6::text)
    OR p.name ILIKE '%' || $6::text || '%'
  )
`

type CountPublicProductsParams struct {
	CategoryID    pgtype.UUID `db:"category_id" json:"category_id"`
	BrandID       pgtype.UUID `db:"brand_id" json:"brand_id"`
	SellerID      pgtype.UUID `db:"seller_id" json:"seller_id"`
	MinPriceCents pgtype.Int8 `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents pgtype.Int8 `db:"max_price_cents" json:"max_price_cents"`
	Query         pgtype.Text `db:"query" json:"query"`
}

func (q *Queries) CountPublicProducts(ctx context.Context, arg CountPublicProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicProducts,
		arg.CategoryID,
		arg.BrandID,
		arg.SellerID,
		arg.MinPriceCents,
		arg.MaxPriceCents,
		arg.Query,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMediaFile = `-- name: CreateMediaFile :one
INSERT INTO media_files (owner_user_id, url, bucket, object_key, mime_type, size_bytes, metadata)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, '{}'::jsonb))
RETURNING id, owner_user_id, url, bucket, object_key, mime_type, size_bytes, metadata, created_at
`

type CreateMediaFileParams struct {
	OwnerUserID pgtype.UUID `db:"owner_user_id" json:"owner_user_id"`
	Url         string      `db:"url" json:"url"`
	Bucket      pgtype.Text `db:"bucket" json:"bucket"`
	ObjectKey   pgtype.Text `db:"object_key" json:"object_key"`
	MimeType    pgtype.Text `db:"mime_type" json:"mime_type"`
	SizeBytes   pgtype.Int8 `db:"size_bytes" json:"size_bytes"`
	Metadata    interface{} `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, createMediaFile,
		arg.OwnerUserID,
		arg.Url,
		arg.Bucket,
		arg.ObjectKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.Metadata,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Url,
		&i.Bucket,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files
WHERE id = $1
  AND owner_user_id = $2
`

type DeleteMediaFileParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	OwnerUserID pgtype.UUID `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) DeleteMediaFile(ctx context.Context, arg DeleteMediaFileParams) error {
	_, err := q.db.Exec(ctx, deleteMediaFile, arg.ID, arg.OwnerUserID)
	return err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, slug, logo_url, is_active, deleted_at, created_at, updated_at
FROM brands
WHERE id = $1
  AND deleted_at IS NULL
  AND is_active = TRUE
`

func (q *Queries) GetBrandByID(ctx context.Context, id pgtype.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, parent_id, name, slug, image_url, sort_order, is_active, deleted_at, created_at, updated_at
FROM categories
WHERE id = $1
  AND deleted_at IS NULL
  AND is_active = TRUE
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaFileByID = `-- name: GetMediaFileByID :one
SELECT id, owner_user_id, url, bucket, object_key, mime_type, size_bytes, metadata, created_at
FROM media_files
WHERE id = $1
`

func (q *Queries) GetMediaFileByID(ctx context.Context, id pgtype.UUID) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFileByID, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Url,
		&i.Bucket,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT p.id, p.seller_id, p.category_id, p.brand_id, p.name, p.slug, p.description, p.status, p.min_price_cents, p.max_price_cents, p.currency, p.total_sold, p.rating, p.review_count, p.published_at, p.deleted_at, p.created_at, p.updated_at
FROM products p
JOIN sellers s ON s.id = p.seller_id
WHERE p.id = $1
  AND p.deleted_at IS NULL
  AND p.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
`

type GetProductByIDRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	SellerID      pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID       pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name          string             `db:"name" json:"name"`
	Slug          string             `db:"slug" json:"slug"`
	Description   pgtype.Text        `db:"description" json:"description"`
	Status        interface{}        `db:"status" json:"status"`
	MinPriceCents int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency      string             `db:"currency" json:"currency"`
	TotalSold     int64              `db:"total_sold" json:"total_sold"`
	Rating        pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount   int64              `db:"review_count" json:"review_count"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.seller_id, p.category_id, p.brand_id, p.name, p.slug, p.description, p.status, p.min_price_cents, p.max_price_cents, p.currency, p.total_sold, p.rating, p.review_count, p.published_at, p.deleted_at, p.created_at, p.updated_at
FROM products p
JOIN sellers s ON s.id = p.seller_id
WHERE p.slug = $1
  AND p.deleted_at IS NULL
  AND p.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
`

type GetProductBySlugRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	SellerID      pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID       pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name          string             `db:"name" json:"name"`
	Slug          string             `db:"slug" json:"slug"`
	Description   pgtype.Text        `db:"description" json:"description"`
	Status        interface{}        `db:"status" json:"status"`
	MinPriceCents int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency      string             `db:"currency" json:"currency"`
	TotalSold     int64              `db:"total_sold" json:"total_sold"`
	Rating        pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount   int64              `db:"review_count" json:"review_count"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicSellerByID = `-- name: GetPublicSellerByID :one
SELECT id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at
FROM sellers
WHERE id = $1
  AND deleted_at IS NULL
  AND status = 'active'
`

type GetPublicSellerByIDRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	ApplicationID pgtype.UUID        `db:"application_id" json:"application_id"`
	ShopName      string             `db:"shop_name" json:"shop_name"`
	Slug          string             `db:"slug" json:"slug"`
	Description   pgtype.Text        `db:"description" json:"description"`
	LogoUrl       pgtype.Text        `db:"logo_url" json:"logo_url"`
	BannerUrl     pgtype.Text        `db:"banner_url" json:"banner_url"`
	Status        interface{}        `db:"status" json:"status"`
	Rating        pgtype.Numeric     `db:"rating" json:"rating"`
	TotalSales    int64              `db:"total_sales" json:"total_sales"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPublicSellerByID(ctx context.Context, id pgtype.UUID) (GetPublicSellerByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublicSellerByID, id)
	var i GetPublicSellerByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicSellerBySlug = `-- name: GetPublicSellerBySlug :one
SELECT id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at
FROM sellers
WHERE slug = $1
  AND deleted_at IS NULL
  AND status = 'active'
`

type GetPublicSellerBySlugRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	ApplicationID pgtype.UUID        `db:"application_id" json:"application_id"`
	ShopName      string             `db:"shop_name" json:"shop_name"`
	Slug          string             `db:"slug" json:"slug"`
	Description   pgtype.Text        `db:"description" json:"description"`
	LogoUrl       pgtype.Text        `db:"logo_url" json:"logo_url"`
	BannerUrl     pgtype.Text        `db:"banner_url" json:"banner_url"`
	Status        interface{}        `db:"status" json:"status"`
	Rating        pgtype.Numeric     `db:"rating" json:"rating"`
	TotalSales    int64              `db:"total_sales" json:"total_sales"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPublicSellerBySlug(ctx context.Context, slug string) (GetPublicSellerBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicSellerBySlug, slug)
	var i GetPublicSellerBySlugRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBanners = `-- name: ListActiveBanners :many
SELECT id, title, image_url, link_url, placement, sort_order, status, starts_at, ends_at, created_at, updated_at
FROM cms_banners
WHERE status = 'published'
  AND placement = COALESCE($1::text, placement)
  AND (starts_at IS NULL OR starts_at <= now())
  AND (ends_at IS NULL OR ends_at > now())
ORDER BY sort_order ASC, created_at DESC
LIMIT $3 OFFSET $2
`

type ListActiveBannersParams struct {
	Placement pgtype.Text `db:"placement" json:"placement"`
	Offset    int32       `db:"offset" json:"offset"`
	Limit     int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListActiveBanners(ctx context.Context, arg ListActiveBannersParams) ([]CmsBanner, error) {
	rows, err := q.db.Query(ctx, listActiveBanners, arg.Placement, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CmsBanner
	for rows.Next() {
		var i CmsBanner
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.Placement,
			&i.SortOrder,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, slug, logo_url, is_active, deleted_at, created_at, updated_at
FROM brands
WHERE deleted_at IS NULL
  AND is_active = TRUE
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListBrandsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListBrands(ctx context.Context, arg ListBrandsParams) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, parent_id, name, slug, image_url, sort_order, is_active, deleted_at, created_at, updated_at
FROM categories
WHERE deleted_at IS NULL
  AND is_active = TRUE
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeSections = `-- name: ListHomeSections :many
SELECT key, value, description, is_public, created_at, updated_at
FROM platform_settings
WHERE is_public = TRUE
  AND key LIKE 'home.%'
ORDER BY key ASC
`

func (q *Queries) ListHomeSections(ctx context.Context) ([]PlatformSetting, error) {
	rows, err := q.db.Query(ctx, listHomeSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformSetting
	for rows.Next() {
		var i PlatformSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFiles = `-- name: ListMediaFiles :many
SELECT id, owner_user_id, url, bucket, object_key, mime_type, size_bytes, metadata, created_at
FROM media_files
WHERE owner_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMediaFilesParams struct {
	OwnerUserID pgtype.UUID `db:"owner_user_id" json:"owner_user_id"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListMediaFiles(ctx context.Context, arg ListMediaFilesParams) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, listMediaFiles, arg.OwnerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Url,
			&i.Bucket,
			&i.ObjectKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, url, alt_text, sort_order, is_primary, created_at
FROM product_images
WHERE product_id = $1
ORDER BY is_primary DESC, sort_order ASC, created_at ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID pgtype.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.AltText,
			&i.SortOrder,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductReviews = `-- name: ListProductReviews :many
SELECT pr.id, pr.product_id, pr.order_item_id, pr.user_id, pr.rating, pr.title, pr.body, pr.is_verified_purchase, pr.is_hidden, pr.deleted_at, pr.created_at, pr.updated_at,
       pr.seller_reply, pr.seller_reply_at
FROM product_reviews pr
JOIN products p ON p.id = pr.product_id
JOIN sellers s ON s.id = p.seller_id
WHERE pr.product_id = $1
  AND pr.deleted_at IS NULL
  AND pr.is_hidden = FALSE
  AND p.deleted_at IS NULL
  AND p.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
ORDER BY pr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductReviewsParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

type ListProductReviewsRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ProductID          pgtype.UUID        `db:"product_id" json:"product_id"`
	OrderItemID        pgtype.UUID        `db:"order_item_id" json:"order_item_id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Rating             int32              `db:"rating" json:"rating"`
	Title              pgtype.Text        `db:"title" json:"title"`
	Body               pgtype.Text        `db:"body" json:"body"`
	IsVerifiedPurchase bool               `db:"is_verified_purchase" json:"is_verified_purchase"`
	IsHidden           bool               `db:"is_hidden" json:"is_hidden"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SellerReply        pgtype.Text        `db:"seller_reply" json:"seller_reply"`
	SellerReplyAt      pgtype.Timestamptz `db:"seller_reply_at" json:"seller_reply_at"`
}

func (q *Queries) ListProductReviews(ctx context.Context, arg ListProductReviewsParams) ([]ListProductReviewsRow, error) {
	rows, err := q.db.Query(ctx, listProductReviews, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductReviewsRow
	for rows.Next() {
		var i ListProductReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OrderItemID,
			&i.UserID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.IsVerifiedPurchase,
			&i.IsHidden,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerReply,
			&i.SellerReplyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT id, product_id, sku, name, price_cents, compare_at_price_cents, currency, weight_grams, is_active, deleted_at, created_at, updated_at
FROM product_variants
WHERE product_id = $1
  AND deleted_at IS NULL
  AND is_active = TRUE
ORDER BY price_cents ASC, created_at ASC
`

func (q *Queries) ListProductVariants(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.PriceCents,
			&i.CompareAtPriceCents,
			&i.Currency,
			&i.WeightGrams,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.seller_id, p.category_id, p.brand_id, p.name, p.slug, p.description, p.status, p.min_price_cents, p.max_price_cents, p.currency, p.total_sold, p.rating, p.review_count, p.published_at, p.deleted_at, p.created_at, p.updated_at,
       pi.url AS primary_image_url
FROM products p
JOIN sellers s ON s.id = p.seller_id
LEFT JOIN LATERAL (
  SELECT url
  FROM product_images
  WHERE product_id = p.id
  ORDER BY is_primary DESC, sort_order ASC, created_at ASC
  LIMIT 1
) pi ON TRUE
WHERE p.deleted_at IS NULL
  AND p.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
  AND ($1::uuid IS NULL OR p.category_id = $1::uuid)
  AND ($2::uuid IS NULL OR p.brand_id = $2::uuid)
  AND ($3::uuid IS NULL OR p.seller_id = $3::uuid)
  AND ($4::bigint IS NULL OR p.min_price_cents >= $4::bigint)
  AND ($5::bigint IS NULL OR p.max_price_cents <= $5::bigint)
  AND (
    $6::text IS NULL
    OR $6::text = ''
    OR p.search_vector @@ plainto_tsquery('simple', $6::text)
    OR p.name ILIKE '%' || $6::text || '%'
  )
ORDER BY
  CASE WHEN $7::text = 'price_asc' THEN p.min_price_cents END ASC,
  CASE WHEN $7::text = 'price_desc' THEN p.min_price_cents END DESC,
  CASE WHEN $7::text = 'popular' THEN p.total_sold END DESC,
  CASE WHEN $7::text = 'rating' THEN p.rating END DESC,
  CASE WHEN $7::text = 'newest' THEN p.published_at END DESC NULLS LAST,
  p.created_at DESC
LIMIT $9 OFFSET $8
`

type ListProductsParams struct {
	CategoryID    pgtype.UUID `db:"category_id" json:"category_id"`
	BrandID       pgtype.UUID `db:"brand_id" json:"brand_id"`
	SellerID      pgtype.UUID `db:"seller_id" json:"seller_id"`
	MinPriceCents pgtype.Int8 `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents pgtype.Int8 `db:"max_price_cents" json:"max_price_cents"`
	Query         pgtype.Text `db:"query" json:"query"`
	Sort          string      `db:"sort" json:"sort"`
	Offset        int32       `db:"offset" json:"offset"`
	Limit         int32       `db:"limit" json:"limit"`
}

type ListProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SellerID        pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID         pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Status          interface{}        `db:"status" json:"status"`
	MinPriceCents   int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents   int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency        string             `db:"currency" json:"currency"`
	TotalSold       int64              `db:"total_sold" json:"total_sold"`
	Rating          pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount     int64              `db:"review_count" json:"review_count"`
	PublishedAt     pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PrimaryImageUrl pgtype.Text        `db:"primary_image_url" json:"primary_image_url"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.CategoryID,
		arg.BrandID,
		arg.SellerID,
		arg.MinPriceCents,
		arg.MaxPriceCents,
		arg.Query,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.Currency,
			&i.TotalSold,
			&i.Rating,
			&i.ReviewCount,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedProducts = `-- name: ListRelatedProducts :many
SELECT p.id, p.seller_id, p.category_id, p.brand_id, p.name, p.slug, p.description, p.status, p.min_price_cents, p.max_price_cents, p.currency, p.total_sold, p.rating, p.review_count, p.published_at, p.deleted_at, p.created_at, p.updated_at,
       pi.url AS primary_image_url
FROM products p
JOIN products base ON base.id = $1
JOIN sellers s ON s.id = p.seller_id
JOIN sellers base_seller ON base_seller.id = base.seller_id
LEFT JOIN LATERAL (
  SELECT url
  FROM product_images
  WHERE product_id = p.id
  ORDER BY is_primary DESC, sort_order ASC, created_at ASC
  LIMIT 1
) pi ON TRUE
WHERE p.deleted_at IS NULL
  AND p.status = 'active'
  AND base.deleted_at IS NULL
  AND base.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
  AND base_seller.deleted_at IS NULL
  AND base_seller.status = 'active'
  AND p.id <> base.id
  AND (
    (base.category_id IS NOT NULL AND p.category_id = base.category_id)
    OR (base.brand_id IS NOT NULL AND p.brand_id = base.brand_id)
    OR p.seller_id = base.seller_id
  )
ORDER BY p.rating DESC, p.total_sold DESC, p.created_at DESC
LIMIT $2
`

type ListRelatedProductsParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	Limit     int32       `db:"limit" json:"limit"`
}

type ListRelatedProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SellerID        pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID         pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Status          interface{}        `db:"status" json:"status"`
	MinPriceCents   int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents   int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency        string             `db:"currency" json:"currency"`
	TotalSold       int64              `db:"total_sold" json:"total_sold"`
	Rating          pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount     int64              `db:"review_count" json:"review_count"`
	PublishedAt     pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PrimaryImageUrl pgtype.Text        `db:"primary_image_url" json:"primary_image_url"`
}

func (q *Queries) ListRelatedProducts(ctx context.Context, arg ListRelatedProductsParams) ([]ListRelatedProductsRow, error) {
	rows, err := q.db.Query(ctx, listRelatedProducts, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedProductsRow
	for rows.Next() {
		var i ListRelatedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.Currency,
			&i.TotalSold,
			&i.Rating,
			&i.ReviewCount,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerReviews = `-- name: ListSellerReviews :many
SELECT pr.id, pr.product_id, pr.order_item_id, pr.user_id, pr.rating, pr.title, pr.body, pr.is_verified_purchase, pr.is_hidden, pr.deleted_at, pr.created_at, pr.updated_at,
       pr.seller_reply, pr.seller_reply_at
FROM product_reviews pr
JOIN products p ON p.id = pr.product_id
JOIN sellers s ON s.id = p.seller_id
WHERE p.seller_id = $1
  AND pr.deleted_at IS NULL
  AND pr.is_hidden = FALSE
  AND p.deleted_at IS NULL
  AND p.status = 'active'
  AND s.deleted_at IS NULL
  AND s.status = 'active'
ORDER BY pr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSellerReviewsParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type ListSellerReviewsRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ProductID          pgtype.UUID        `db:"product_id" json:"product_id"`
	OrderItemID        pgtype.UUID        `db:"order_item_id" json:"order_item_id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Rating             int32              `db:"rating" json:"rating"`
	Title              pgtype.Text        `db:"title" json:"title"`
	Body               pgtype.Text        `db:"body" json:"body"`
	IsVerifiedPurchase bool               `db:"is_verified_purchase" json:"is_verified_purchase"`
	IsHidden           bool               `db:"is_hidden" json:"is_hidden"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SellerReply        pgtype.Text        `db:"seller_reply" json:"seller_reply"`
	SellerReplyAt      pgtype.Timestamptz `db:"seller_reply_at" json:"seller_reply_at"`
}

func (q *Queries) ListSellerReviews(ctx context.Context, arg ListSellerReviewsParams) ([]ListSellerReviewsRow, error) {
	rows, err := q.db.Query(ctx, listSellerReviews, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellerReviewsRow
	for rows.Next() {
		var i ListSellerReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OrderItemID,
			&i.UserID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.IsVerifiedPurchase,
			&i.IsHidden,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerReply,
			&i.SellerReplyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at
FROM products
WHERE deleted_at IS NULL
  AND status = 'active'
  AND (
    $1::text = ''
    OR search_vector @@ plainto_tsquery('simple', $1)
    OR name ILIKE '%' || $1 || '%'
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchProductsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type SearchProductsRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	SellerID      pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID       pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name          string             `db:"name" json:"name"`
	Slug          string             `db:"slug" json:"slug"`
	Description   pgtype.Text        `db:"description" json:"description"`
	Status        interface{}        `db:"status" json:"status"`
	MinPriceCents int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency      string             `db:"currency" json:"currency"`
	TotalSold     int64              `db:"total_sold" json:"total_sold"`
	Rating        pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount   int64              `db:"review_count" json:"review_count"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.Currency,
			&i.TotalSold,
			&i.Rating,
			&i.ReviewCount,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackSearchClick = `-- name: TrackSearchClick :one
INSERT INTO search_click_events (user_id, session_id, query, product_id, position, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, session_id, query, product_id, position, metadata, created_at
`

type TrackSearchClickParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	SessionID pgtype.Text `db:"session_id" json:"session_id"`
	Query     string      `db:"query" json:"query"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	Position  pgtype.Int4 `db:"position" json:"position"`
	Metadata  []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) TrackSearchClick(ctx context.Context, arg TrackSearchClickParams) (SearchClickEvent, error) {
	row := q.db.QueryRow(ctx, trackSearchClick,
		arg.UserID,
		arg.SessionID,
		arg.Query,
		arg.ProductID,
		arg.Position,
		arg.Metadata,
	)
	var i SearchClickEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Query,
		&i.ProductID,
		&i.Position,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const trackSearchQuery = `-- name: TrackSearchQuery :one
INSERT INTO search_recent_queries (user_id, session_id, query, filters)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, session_id, query, filters, created_at
`

type TrackSearchQueryParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	SessionID pgtype.Text `db:"session_id" json:"session_id"`
	Query     string      `db:"query" json:"query"`
	Filters   []byte      `db:"filters" json:"filters"`
}

func (q *Queries) TrackSearchQuery(ctx context.Context, arg TrackSearchQueryParams) (SearchRecentQuery, error) {
	row := q.db.QueryRow(ctx, trackSearchQuery,
		arg.UserID,
		arg.SessionID,
		arg.Query,
		arg.Filters,
	)
	var i SearchRecentQuery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Query,
		&i.Filters,
		&i.CreatedAt,
	)
	return i, err
}

const updateMediaFileMetadata = `-- name: UpdateMediaFileMetadata :one
UPDATE media_files
SET url = $2,
    mime_type = $3,
    size_bytes = $4,
    metadata = $5
WHERE id = $1
  AND owner_user_id = $6
RETURNING id, owner_user_id, url, bucket, object_key, mime_type, size_bytes, metadata, created_at
`

type UpdateMediaFileMetadataParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Url         string      `db:"url" json:"url"`
	MimeType    pgtype.Text `db:"mime_type" json:"mime_type"`
	SizeBytes   pgtype.Int8 `db:"size_bytes" json:"size_bytes"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
	OwnerUserID pgtype.UUID `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) UpdateMediaFileMetadata(ctx context.Context, arg UpdateMediaFileMetadataParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, updateMediaFileMetadata,
		arg.ID,
		arg.Url,
		arg.MimeType,
		arg.SizeBytes,
		arg.Metadata,
		arg.OwnerUserID,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Url,
		&i.Bucket,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
