// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sellerstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignSellerRole(ctx context.Context, userID pgtype.UUID) error
	CountSellerProducts(ctx context.Context, sellerID pgtype.UUID) (int64, error)
	CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateSellerApplication(ctx context.Context, arg CreateSellerApplicationParams) (SellerApplication, error)
	CreateSellerDocument(ctx context.Context, arg CreateSellerDocumentParams) (SellerDocument, error)
	CreateSellerFromApplication(ctx context.Context, id pgtype.UUID) (Seller, error)
	CreateSellerProduct(ctx context.Context, arg CreateSellerProductParams) (CreateSellerProductRow, error)
	CreateVariantOption(ctx context.Context, arg CreateVariantOptionParams) (VariantOption, error)
	CreateVariantOptionValue(ctx context.Context, arg CreateVariantOptionValueParams) (VariantOptionValue, error)
	DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) error
	DeleteProductVariant(ctx context.Context, arg DeleteProductVariantParams) error
	DeleteSellerDocument(ctx context.Context, arg DeleteSellerDocumentParams) error
	DeleteVariantOption(ctx context.Context, arg DeleteVariantOptionParams) error
	DuplicateSellerProduct(ctx context.Context, arg DuplicateSellerProductParams) (DuplicateSellerProductRow, error)
	GetInventoryItemForSeller(ctx context.Context, arg GetInventoryItemForSellerParams) (InventoryItem, error)
	GetSellerApplicationByUserID(ctx context.Context, userID pgtype.UUID) (SellerApplication, error)
	GetSellerByID(ctx context.Context, id pgtype.UUID) (Seller, error)
	GetSellerByUserID(ctx context.Context, userID pgtype.UUID) (Seller, error)
	GetSellerProduct(ctx context.Context, arg GetSellerProductParams) (GetSellerProductRow, error)
	ListInventoryForSeller(ctx context.Context, arg ListInventoryForSellerParams) ([]InventoryItem, error)
	ListInventoryMovementsForSeller(ctx context.Context, arg ListInventoryMovementsForSellerParams) ([]InventoryMovement, error)
	ListLowStockForSeller(ctx context.Context, arg ListLowStockForSellerParams) ([]InventoryItem, error)
	ListProductImagesForSeller(ctx context.Context, arg ListProductImagesForSellerParams) ([]ProductImage, error)
	ListProductVariantsForSeller(ctx context.Context, arg ListProductVariantsForSellerParams) ([]ProductVariant, error)
	ListSellerApplicationsForAdmin(ctx context.Context, arg ListSellerApplicationsForAdminParams) ([]SellerApplication, error)
	ListSellerDocuments(ctx context.Context, arg ListSellerDocumentsParams) ([]SellerDocument, error)
	ListSellerProducts(ctx context.Context, arg ListSellerProductsParams) ([]ListSellerProductsRow, error)
	ListVariantOptionValues(ctx context.Context, optionID pgtype.UUID) ([]VariantOptionValue, error)
	ListVariantOptionsForSeller(ctx context.Context, arg ListVariantOptionsForSellerParams) ([]VariantOption, error)
	LockInventoryItemForSeller(ctx context.Context, arg LockInventoryItemForSellerParams) (InventoryItem, error)
	ModerateProductForAdmin(ctx context.Context, arg ModerateProductForAdminParams) (ModerateProductForAdminRow, error)
	PublishSellerProduct(ctx context.Context, arg PublishSellerProductParams) (PublishSellerProductRow, error)
	ReviewSellerApplication(ctx context.Context, arg ReviewSellerApplicationParams) (SellerApplication, error)
	SellerDashboardStats(ctx context.Context, sellerID pgtype.UUID) (SellerDashboardStatsRow, error)
	SellerRecentOrders(ctx context.Context, arg SellerRecentOrdersParams) ([]Order, error)
	SellerSalesChart(ctx context.Context, arg SellerSalesChartParams) ([]SellerSalesChartRow, error)
	SellerTopProducts(ctx context.Context, arg SellerTopProductsParams) ([]SellerTopProductsRow, error)
	SoftDeleteSellerProduct(ctx context.Context, arg SoftDeleteSellerProductParams) error
	SubmitSellerApplication(ctx context.Context, arg SubmitSellerApplicationParams) (SellerApplication, error)
	SuspendSellerForAdmin(ctx context.Context, arg SuspendSellerForAdminParams) (Seller, error)
	UnpublishSellerProduct(ctx context.Context, arg UnpublishSellerProductParams) (UnpublishSellerProductRow, error)
	UpdateInventoryQuantities(ctx context.Context, arg UpdateInventoryQuantitiesParams) (InventoryItem, error)
	UpdateProductImageOrder(ctx context.Context, arg UpdateProductImageOrderParams) (ProductImage, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateSellerApplication(ctx context.Context, arg UpdateSellerApplicationParams) (SellerApplication, error)
	UpdateSellerMedia(ctx context.Context, arg UpdateSellerMediaParams) (Seller, error)
	UpdateSellerProduct(ctx context.Context, arg UpdateSellerProductParams) (UpdateSellerProductRow, error)
	UpdateSellerProfile(ctx context.Context, arg UpdateSellerProfileParams) (Seller, error)
	UpdateSellerSettings(ctx context.Context, arg UpdateSellerSettingsParams) (Seller, error)
	UpsertInventoryItem(ctx context.Context, arg UpsertInventoryItemParams) (InventoryItem, error)
}

var _ Querier = (*Queries)(nil)
