// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sellers.sql

package sellerstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSellerRole = `-- name: AssignSellerRole :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, id FROM roles WHERE name = 'seller'
ON CONFLICT DO NOTHING
`

func (q *Queries) AssignSellerRole(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, assignSellerRole, userID)
	return err
}

const countSellerProducts = `-- name: CountSellerProducts :one
SELECT count(*)::bigint
FROM products
WHERE seller_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountSellerProducts(ctx context.Context, sellerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerProducts, sellerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements (inventory_item_id, movement_type, quantity, reason, reference_type, reference_id, actor_user_id, before_available, after_available, before_reserved, after_reserved)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, inventory_item_id, movement_type, quantity, reason, reference_type, reference_id, created_at, actor_user_id, before_available, after_available, before_reserved, after_reserved
`

type CreateInventoryMovementParams struct {
	InventoryItemID pgtype.UUID `db:"inventory_item_id" json:"inventory_item_id"`
	MovementType    interface{} `db:"movement_type" json:"movement_type"`
	Quantity        int32       `db:"quantity" json:"quantity"`
	Reason          pgtype.Text `db:"reason" json:"reason"`
	ReferenceType   pgtype.Text `db:"reference_type" json:"reference_type"`
	ReferenceID     pgtype.UUID `db:"reference_id" json:"reference_id"`
	ActorUserID     pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	BeforeAvailable pgtype.Int4 `db:"before_available" json:"before_available"`
	AfterAvailable  pgtype.Int4 `db:"after_available" json:"after_available"`
	BeforeReserved  pgtype.Int4 `db:"before_reserved" json:"before_reserved"`
	AfterReserved   pgtype.Int4 `db:"after_reserved" json:"after_reserved"`
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, createInventoryMovement,
		arg.InventoryItemID,
		arg.MovementType,
		arg.Quantity,
		arg.Reason,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ActorUserID,
		arg.BeforeAvailable,
		arg.AfterAvailable,
		arg.BeforeReserved,
		arg.AfterReserved,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.MovementType,
		&i.Quantity,
		&i.Reason,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.ActorUserID,
		&i.BeforeAvailable,
		&i.AfterAvailable,
		&i.BeforeReserved,
		&i.AfterReserved,
	)
	return i, err
}

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, url, alt_text, sort_order, is_primary)
VALUES ($1, $2, $3, $4, COALESCE($5, FALSE))
RETURNING id, product_id, url, alt_text, sort_order, is_primary, created_at
`

type CreateProductImageParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	Url       string      `db:"url" json:"url"`
	AltText   pgtype.Text `db:"alt_text" json:"alt_text"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
	Column5   interface{} `db:"column_5" json:"column_5"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.Url,
		arg.AltText,
		arg.SortOrder,
		arg.Column5,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (product_id, sku, name, price_cents, compare_at_price_cents, currency, weight_grams, is_active)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, 'USD'), $7, COALESCE($8, TRUE))
RETURNING id, product_id, sku, name, price_cents, compare_at_price_cents, currency, weight_grams, is_active, deleted_at, created_at, updated_at
`

type CreateProductVariantParams struct {
	ProductID           pgtype.UUID `db:"product_id" json:"product_id"`
	Sku                 string      `db:"sku" json:"sku"`
	Name                pgtype.Text `db:"name" json:"name"`
	PriceCents          int64       `db:"price_cents" json:"price_cents"`
	CompareAtPriceCents pgtype.Int8 `db:"compare_at_price_cents" json:"compare_at_price_cents"`
	Column6             interface{} `db:"column_6" json:"column_6"`
	WeightGrams         pgtype.Int4 `db:"weight_grams" json:"weight_grams"`
	Column8             interface{} `db:"column_8" json:"column_8"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.PriceCents,
		arg.CompareAtPriceCents,
		arg.Column6,
		arg.WeightGrams,
		arg.Column8,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.Currency,
		&i.WeightGrams,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSellerApplication = `-- name: CreateSellerApplication :one
INSERT INTO seller_applications (user_id, shop_name, slug, business_type, country, currency, status, metadata)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, 'USD'), 'draft', COALESCE($7, '{}'::jsonb))
RETURNING id, user_id, shop_name, slug, business_type, country, currency, status, submitted_at, reviewed_by, reviewed_at, rejection_reason, metadata, created_at, updated_at
`

type CreateSellerApplicationParams struct {
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	ShopName     string      `db:"shop_name" json:"shop_name"`
	Slug         string      `db:"slug" json:"slug"`
	BusinessType pgtype.Text `db:"business_type" json:"business_type"`
	Country      pgtype.Text `db:"country" json:"country"`
	Column6      interface{} `db:"column_6" json:"column_6"`
	Column7      interface{} `db:"column_7" json:"column_7"`
}

func (q *Queries) CreateSellerApplication(ctx context.Context, arg CreateSellerApplicationParams) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, createSellerApplication,
		arg.UserID,
		arg.ShopName,
		arg.Slug,
		arg.BusinessType,
		arg.Country,
		arg.Column6,
		arg.Column7,
	)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopName,
		&i.Slug,
		&i.BusinessType,
		&i.Country,
		&i.Currency,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSellerDocument = `-- name: CreateSellerDocument :one
INSERT INTO seller_documents (seller_application_id, seller_id, document_type, file_url, metadata)
VALUES ($1, $2, $3, $4, COALESCE($5, '{}'::jsonb))
RETURNING id, seller_application_id, seller_id, document_type, file_url, status, reviewed_by, reviewed_at, rejection_reason, metadata, created_at
`

type CreateSellerDocumentParams struct {
	SellerApplicationID pgtype.UUID `db:"seller_application_id" json:"seller_application_id"`
	SellerID            pgtype.UUID `db:"seller_id" json:"seller_id"`
	DocumentType        string      `db:"document_type" json:"document_type"`
	FileUrl             string      `db:"file_url" json:"file_url"`
	Metadata            interface{} `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateSellerDocument(ctx context.Context, arg CreateSellerDocumentParams) (SellerDocument, error) {
	row := q.db.QueryRow(ctx, createSellerDocument,
		arg.SellerApplicationID,
		arg.SellerID,
		arg.DocumentType,
		arg.FileUrl,
		arg.Metadata,
	)
	var i SellerDocument
	err := row.Scan(
		&i.ID,
		&i.SellerApplicationID,
		&i.SellerID,
		&i.DocumentType,
		&i.FileUrl,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createSellerFromApplication = `-- name: CreateSellerFromApplication :one
INSERT INTO sellers (user_id, application_id, shop_name, slug, status)
SELECT sa.user_id, sa.id, sa.shop_name, sa.slug, 'active'
FROM seller_applications sa
WHERE sa.id = $1
  AND sa.status = 'approved'
ON CONFLICT (user_id) DO UPDATE
SET application_id = EXCLUDED.application_id,
    shop_name = EXCLUDED.shop_name,
    slug = EXCLUDED.slug,
    status = 'active',
    deleted_at = NULL
RETURNING id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at, settings
`

func (q *Queries) CreateSellerFromApplication(ctx context.Context, id pgtype.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, createSellerFromApplication, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const createSellerProduct = `-- name: CreateSellerProduct :one
INSERT INTO products (seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, moderation_status)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, 'draft'), $8, $9, COALESCE($10, 'USD'), 'approved')
RETURNING id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at, moderation_status, moderation_reason, moderated_by, moderated_at
`

type CreateSellerProductParams struct {
	SellerID      pgtype.UUID `db:"seller_id" json:"seller_id"`
	CategoryID    pgtype.UUID `db:"category_id" json:"category_id"`
	BrandID       pgtype.UUID `db:"brand_id" json:"brand_id"`
	Name          string      `db:"name" json:"name"`
	Slug          string      `db:"slug" json:"slug"`
	Description   pgtype.Text `db:"description" json:"description"`
	Status        interface{} `db:"status" json:"status"`
	MinPriceCents int64       `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents int64       `db:"max_price_cents" json:"max_price_cents"`
	Currency      interface{} `db:"currency" json:"currency"`
}

type CreateSellerProductRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) CreateSellerProduct(ctx context.Context, arg CreateSellerProductParams) (CreateSellerProductRow, error) {
	row := q.db.QueryRow(ctx, createSellerProduct,
		arg.SellerID,
		arg.CategoryID,
		arg.BrandID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Status,
		arg.MinPriceCents,
		arg.MaxPriceCents,
		arg.Currency,
	)
	var i CreateSellerProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const createVariantOption = `-- name: CreateVariantOption :one
INSERT INTO variant_options (product_id, name, sort_order)
VALUES ($1, $2, COALESCE($3, 0))
RETURNING id, product_id, name, sort_order
`

type CreateVariantOptionParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	Name      string      `db:"name" json:"name"`
	Column3   interface{} `db:"column_3" json:"column_3"`
}

func (q *Queries) CreateVariantOption(ctx context.Context, arg CreateVariantOptionParams) (VariantOption, error) {
	row := q.db.QueryRow(ctx, createVariantOption, arg.ProductID, arg.Name, arg.Column3)
	var i VariantOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const createVariantOptionValue = `-- name: CreateVariantOptionValue :one
INSERT INTO variant_option_values (option_id, value, sort_order)
SELECT vo.id, $1::text, COALESCE($2::int, 0)
FROM variant_options vo
JOIN products p ON p.id = vo.product_id
WHERE vo.id = $3
  AND p.seller_id = $4
RETURNING id, option_id, value, sort_order
`

type CreateVariantOptionValueParams struct {
	Value     string      `db:"value" json:"value"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
	OptionID  pgtype.UUID `db:"option_id" json:"option_id"`
	SellerID  pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) CreateVariantOptionValue(ctx context.Context, arg CreateVariantOptionValueParams) (VariantOptionValue, error) {
	row := q.db.QueryRow(ctx, createVariantOptionValue,
		arg.Value,
		arg.SortOrder,
		arg.OptionID,
		arg.SellerID,
	)
	var i VariantOptionValue
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.Value,
		&i.SortOrder,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images pi
USING products p
WHERE pi.id = $1
  AND pi.product_id = p.id
  AND p.seller_id = $2
`

type DeleteProductImageParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) error {
	_, err := q.db.Exec(ctx, deleteProductImage, arg.ID, arg.SellerID)
	return err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
UPDATE product_variants pv
SET deleted_at = now(),
    is_active = FALSE
FROM products p
WHERE pv.id = $1
  AND pv.product_id = p.id
  AND p.seller_id = $2
  AND pv.deleted_at IS NULL
`

type DeleteProductVariantParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) DeleteProductVariant(ctx context.Context, arg DeleteProductVariantParams) error {
	_, err := q.db.Exec(ctx, deleteProductVariant, arg.ID, arg.SellerID)
	return err
}

const deleteSellerDocument = `-- name: DeleteSellerDocument :exec
DELETE FROM seller_documents
WHERE seller_documents.id = $1
  AND (
    seller_documents.seller_application_id IN (SELECT sa.id FROM seller_applications sa WHERE sa.user_id = $2)
    OR seller_documents.seller_id IN (SELECT s.id FROM sellers s WHERE s.user_id = $2)
  )
`

type DeleteSellerDocumentParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteSellerDocument(ctx context.Context, arg DeleteSellerDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteSellerDocument, arg.ID, arg.UserID)
	return err
}

const deleteVariantOption = `-- name: DeleteVariantOption :exec
DELETE FROM variant_options vo
USING products p
WHERE vo.id = $1
  AND vo.product_id = p.id
  AND p.seller_id = $2
`

type DeleteVariantOptionParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) DeleteVariantOption(ctx context.Context, arg DeleteVariantOptionParams) error {
	_, err := q.db.Exec(ctx, deleteVariantOption, arg.ID, arg.SellerID)
	return err
}

const duplicateSellerProduct = `-- name: DuplicateSellerProduct :one
INSERT INTO products (seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, moderation_status)
SELECT p.seller_id, p.category_id, p.brand_id, $1, $2, p.description, 'draft', p.min_price_cents, p.max_price_cents, p.currency, 'approved'
FROM products p
WHERE p.id = $3
  AND p.seller_id = $4
  AND p.deleted_at IS NULL
RETURNING id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at, moderation_status, moderation_reason, moderated_by, moderated_at
`

type DuplicateSellerProductParams struct {
	Name            string      `db:"name" json:"name"`
	Slug            string      `db:"slug" json:"slug"`
	SourceProductID pgtype.UUID `db:"source_product_id" json:"source_product_id"`
	SellerID        pgtype.UUID `db:"seller_id" json:"seller_id"`
}

type DuplicateSellerProductRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) DuplicateSellerProduct(ctx context.Context, arg DuplicateSellerProductParams) (DuplicateSellerProductRow, error) {
	row := q.db.QueryRow(ctx, duplicateSellerProduct,
		arg.Name,
		arg.Slug,
		arg.SourceProductID,
		arg.SellerID,
	)
	var i DuplicateSellerProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const getInventoryItemForSeller = `-- name: GetInventoryItemForSeller :one
SELECT ii.id, ii.product_id, ii.variant_id, ii.quantity_available, ii.quantity_reserved, ii.low_stock_threshold, ii.created_at, ii.updated_at
FROM inventory_items ii
JOIN products p ON p.id = ii.product_id
WHERE ii.id = $1
  AND p.seller_id = $2
`

type GetInventoryItemForSellerParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) GetInventoryItemForSeller(ctx context.Context, arg GetInventoryItemForSellerParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItemForSeller, arg.ID, arg.SellerID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.QuantityAvailable,
		&i.QuantityReserved,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerApplicationByUserID = `-- name: GetSellerApplicationByUserID :one
SELECT id, user_id, shop_name, slug, business_type, country, currency, status, submitted_at, reviewed_by, reviewed_at, rejection_reason, metadata, created_at, updated_at
FROM seller_applications
WHERE user_id = $1
  AND status <> 'cancelled'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSellerApplicationByUserID(ctx context.Context, userID pgtype.UUID) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, getSellerApplicationByUserID, userID)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopName,
		&i.Slug,
		&i.BusinessType,
		&i.Country,
		&i.Currency,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerByID = `-- name: GetSellerByID :one
SELECT id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at, settings
FROM sellers
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetSellerByID(ctx context.Context, id pgtype.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByID, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const getSellerByUserID = `-- name: GetSellerByUserID :one
SELECT id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at, settings
FROM sellers
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetSellerByUserID(ctx context.Context, userID pgtype.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByUserID, userID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const getSellerProduct = `-- name: GetSellerProduct :one
SELECT id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at, moderation_status, moderation_reason, moderated_by, moderated_at
FROM products
WHERE id = $1
  AND seller_id = $2
  AND deleted_at IS NULL
`

type GetSellerProductParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

type GetSellerProductRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) GetSellerProduct(ctx context.Context, arg GetSellerProductParams) (GetSellerProductRow, error) {
	row := q.db.QueryRow(ctx, getSellerProduct, arg.ID, arg.SellerID)
	var i GetSellerProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const listInventoryForSeller = `-- name: ListInventoryForSeller :many
SELECT ii.id, ii.product_id, ii.variant_id, ii.quantity_available, ii.quantity_reserved, ii.low_stock_threshold, ii.created_at, ii.updated_at
FROM inventory_items ii
JOIN products p ON p.id = ii.product_id
WHERE p.seller_id = $1
ORDER BY ii.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListInventoryForSellerParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListInventoryForSeller(ctx context.Context, arg ListInventoryForSellerParams) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listInventoryForSeller, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VariantID,
			&i.QuantityAvailable,
			&i.QuantityReserved,
			&i.LowStockThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryMovementsForSeller = `-- name: ListInventoryMovementsForSeller :many
SELECT im.id, im.inventory_item_id, im.movement_type, im.quantity, im.reason, im.reference_type, im.reference_id, im.created_at, im.actor_user_id, im.before_available, im.after_available, im.before_reserved, im.after_reserved
FROM inventory_movements im
JOIN inventory_items ii ON ii.id = im.inventory_item_id
JOIN products p ON p.id = ii.product_id
WHERE im.inventory_item_id = $1
  AND p.seller_id = $2
ORDER BY im.created_at DESC
LIMIT $3 OFFSET $4
`

type ListInventoryMovementsForSellerParams struct {
	InventoryItemID pgtype.UUID `db:"inventory_item_id" json:"inventory_item_id"`
	SellerID        pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit           int32       `db:"limit" json:"limit"`
	Offset          int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListInventoryMovementsForSeller(ctx context.Context, arg ListInventoryMovementsForSellerParams) ([]InventoryMovement, error) {
	rows, err := q.db.Query(ctx, listInventoryMovementsForSeller,
		arg.InventoryItemID,
		arg.SellerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMovement
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.MovementType,
			&i.Quantity,
			&i.Reason,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
			&i.ActorUserID,
			&i.BeforeAvailable,
			&i.AfterAvailable,
			&i.BeforeReserved,
			&i.AfterReserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockForSeller = `-- name: ListLowStockForSeller :many
SELECT ii.id, ii.product_id, ii.variant_id, ii.quantity_available, ii.quantity_reserved, ii.low_stock_threshold, ii.created_at, ii.updated_at
FROM inventory_items ii
JOIN products p ON p.id = ii.product_id
WHERE p.seller_id = $1
  AND ii.quantity_available <= ii.low_stock_threshold
ORDER BY ii.quantity_available ASC, ii.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListLowStockForSellerParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListLowStockForSeller(ctx context.Context, arg ListLowStockForSellerParams) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listLowStockForSeller, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VariantID,
			&i.QuantityAvailable,
			&i.QuantityReserved,
			&i.LowStockThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImagesForSeller = `-- name: ListProductImagesForSeller :many
SELECT pi.id, pi.product_id, pi.url, pi.alt_text, pi.sort_order, pi.is_primary, pi.created_at
FROM product_images pi
JOIN products p ON p.id = pi.product_id
WHERE pi.product_id = $1
  AND p.seller_id = $2
ORDER BY pi.sort_order ASC, pi.created_at ASC
`

type ListProductImagesForSellerParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	SellerID  pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) ListProductImagesForSeller(ctx context.Context, arg ListProductImagesForSellerParams) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImagesForSeller, arg.ProductID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.AltText,
			&i.SortOrder,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsForSeller = `-- name: ListProductVariantsForSeller :many
SELECT pv.id, pv.product_id, pv.sku, pv.name, pv.price_cents, pv.compare_at_price_cents, pv.currency, pv.weight_grams, pv.is_active, pv.deleted_at, pv.created_at, pv.updated_at
FROM product_variants pv
JOIN products p ON p.id = pv.product_id
WHERE pv.product_id = $1
  AND p.seller_id = $2
  AND pv.deleted_at IS NULL
ORDER BY pv.created_at ASC
`

type ListProductVariantsForSellerParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	SellerID  pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) ListProductVariantsForSeller(ctx context.Context, arg ListProductVariantsForSellerParams) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listProductVariantsForSeller, arg.ProductID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.PriceCents,
			&i.CompareAtPriceCents,
			&i.Currency,
			&i.WeightGrams,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerApplicationsForAdmin = `-- name: ListSellerApplicationsForAdmin :many
SELECT id, user_id, shop_name, slug, business_type, country, currency, status, submitted_at, reviewed_by, reviewed_at, rejection_reason, metadata, created_at, updated_at
FROM seller_applications
WHERE status = COALESCE($1::seller_application_status, status)
ORDER BY submitted_at DESC NULLS LAST, created_at DESC
LIMIT $3 OFFSET $2
`

type ListSellerApplicationsForAdminParams struct {
	Status interface{} `db:"status" json:"status"`
	Offset int32       `db:"offset" json:"offset"`
	Limit  int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListSellerApplicationsForAdmin(ctx context.Context, arg ListSellerApplicationsForAdminParams) ([]SellerApplication, error) {
	rows, err := q.db.Query(ctx, listSellerApplicationsForAdmin, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerApplication
	for rows.Next() {
		var i SellerApplication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShopName,
			&i.Slug,
			&i.BusinessType,
			&i.Country,
			&i.Currency,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerDocuments = `-- name: ListSellerDocuments :many
SELECT id, seller_application_id, seller_id, document_type, file_url, status, reviewed_by, reviewed_at, rejection_reason, metadata, created_at
FROM seller_documents
WHERE (seller_application_id = $1::uuid OR seller_id = $2::uuid)
ORDER BY created_at DESC
`

type ListSellerDocumentsParams struct {
	SellerApplicationID pgtype.UUID `db:"seller_application_id" json:"seller_application_id"`
	SellerID            pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) ListSellerDocuments(ctx context.Context, arg ListSellerDocumentsParams) ([]SellerDocument, error) {
	rows, err := q.db.Query(ctx, listSellerDocuments, arg.SellerApplicationID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerDocument
	for rows.Next() {
		var i SellerDocument
		if err := rows.Scan(
			&i.ID,
			&i.SellerApplicationID,
			&i.SellerID,
			&i.DocumentType,
			&i.FileUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerProducts = `-- name: ListSellerProducts :many
SELECT id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at, moderation_status, moderation_reason, moderated_by, moderated_at
FROM products
WHERE seller_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSellerProductsParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type ListSellerProductsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) ListSellerProducts(ctx context.Context, arg ListSellerProductsParams) ([]ListSellerProductsRow, error) {
	rows, err := q.db.Query(ctx, listSellerProducts, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellerProductsRow
	for rows.Next() {
		var i ListSellerProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.Currency,
			&i.TotalSold,
			&i.Rating,
			&i.ReviewCount,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationStatus,
			&i.ModerationReason,
			&i.ModeratedBy,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantOptionValues = `-- name: ListVariantOptionValues :many
SELECT id, option_id, value, sort_order
FROM variant_option_values
WHERE option_id = $1
ORDER BY sort_order ASC, value ASC
`

func (q *Queries) ListVariantOptionValues(ctx context.Context, optionID pgtype.UUID) ([]VariantOptionValue, error) {
	rows, err := q.db.Query(ctx, listVariantOptionValues, optionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariantOptionValue
	for rows.Next() {
		var i VariantOptionValue
		if err := rows.Scan(
			&i.ID,
			&i.OptionID,
			&i.Value,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantOptionsForSeller = `-- name: ListVariantOptionsForSeller :many
SELECT vo.id, vo.product_id, vo.name, vo.sort_order
FROM variant_options vo
JOIN products p ON p.id = vo.product_id
WHERE vo.product_id = $1
  AND p.seller_id = $2
ORDER BY vo.sort_order ASC, vo.name ASC
`

type ListVariantOptionsForSellerParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	SellerID  pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) ListVariantOptionsForSeller(ctx context.Context, arg ListVariantOptionsForSellerParams) ([]VariantOption, error) {
	rows, err := q.db.Query(ctx, listVariantOptionsForSeller, arg.ProductID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariantOption
	for rows.Next() {
		var i VariantOption
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInventoryItemForSeller = `-- name: LockInventoryItemForSeller :one
SELECT ii.id, ii.product_id, ii.variant_id, ii.quantity_available, ii.quantity_reserved, ii.low_stock_threshold, ii.created_at, ii.updated_at
FROM inventory_items ii
JOIN products p ON p.id = ii.product_id
WHERE ii.id = $1
  AND p.seller_id = $2
FOR UPDATE
`

type LockInventoryItemForSellerParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) LockInventoryItemForSeller(ctx context.Context, arg LockInventoryItemForSellerParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, lockInventoryItemForSeller, arg.ID, arg.SellerID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.QuantityAvailable,
		&i.QuantityReserved,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moderateProductForAdmin = `-- name: ModerateProductForAdmin :one
UPDATE products
SET moderation_status = $1::text,
    moderation_reason = $2::text,
    moderated_by = $3,
    moderated_at = now(),
    status = CASE WHEN $1::text = 'rejected' THEN 'inactive'::product_status ELSE status END
WHERE id = $4
  AND deleted_at IS NULL
RETURNING id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at, moderation_status, moderation_reason, moderated_by, moderated_at
`

type ModerateProductForAdminParams struct {
	ModerationStatus string      `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID `db:"moderated_by" json:"moderated_by"`
	ID               pgtype.UUID `db:"id" json:"id"`
}

type ModerateProductForAdminRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) ModerateProductForAdmin(ctx context.Context, arg ModerateProductForAdminParams) (ModerateProductForAdminRow, error) {
	row := q.db.QueryRow(ctx, moderateProductForAdmin,
		arg.ModerationStatus,
		arg.ModerationReason,
		arg.ModeratedBy,
		arg.ID,
	)
	var i ModerateProductForAdminRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const publishSellerProduct = `-- name: PublishSellerProduct :one
UPDATE products
SET status = 'active',
    published_at = COALESCE(published_at, now())
WHERE id = $1
  AND seller_id = $2
  AND deleted_at IS NULL
  AND status IN ('draft', 'inactive')
  AND moderation_status = 'approved'
RETURNING id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at, moderation_status, moderation_reason, moderated_by, moderated_at
`

type PublishSellerProductParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

type PublishSellerProductRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) PublishSellerProduct(ctx context.Context, arg PublishSellerProductParams) (PublishSellerProductRow, error) {
	row := q.db.QueryRow(ctx, publishSellerProduct, arg.ID, arg.SellerID)
	var i PublishSellerProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const reviewSellerApplication = `-- name: ReviewSellerApplication :one
UPDATE seller_applications
SET status = $1::seller_application_status,
    reviewed_by = $2,
    reviewed_at = now(),
    rejection_reason = $3::text
WHERE id = $4
  AND status IN ('submitted', 'in_review')
RETURNING id, user_id, shop_name, slug, business_type, country, currency, status, submitted_at, reviewed_by, reviewed_at, rejection_reason, metadata, created_at, updated_at
`

type ReviewSellerApplicationParams struct {
	Status          interface{} `db:"status" json:"status"`
	ReviewedBy      pgtype.UUID `db:"reviewed_by" json:"reviewed_by"`
	RejectionReason pgtype.Text `db:"rejection_reason" json:"rejection_reason"`
	ID              pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ReviewSellerApplication(ctx context.Context, arg ReviewSellerApplicationParams) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, reviewSellerApplication,
		arg.Status,
		arg.ReviewedBy,
		arg.RejectionReason,
		arg.ID,
	)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopName,
		&i.Slug,
		&i.BusinessType,
		&i.Country,
		&i.Currency,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellerDashboardStats = `-- name: SellerDashboardStats :one
SELECT
  (SELECT count(*)::bigint FROM products p WHERE p.seller_id = $1 AND p.deleted_at IS NULL) AS product_count,
  (SELECT count(*)::bigint FROM products p WHERE p.seller_id = $1 AND p.status = 'active' AND p.deleted_at IS NULL) AS active_product_count,
  (SELECT count(*)::bigint FROM inventory_items ii JOIN products p ON p.id = ii.product_id WHERE p.seller_id = $1 AND ii.quantity_available <= ii.low_stock_threshold) AS low_stock_count,
  (SELECT COALESCE(sum(oi.total_price_cents), 0)::bigint FROM order_items oi WHERE oi.seller_id = $1) AS gross_sales_cents,
  (SELECT count(DISTINCT oi.order_id)::bigint FROM order_items oi WHERE oi.seller_id = $1) AS order_count
`

type SellerDashboardStatsRow struct {
	ProductCount       int64 `db:"product_count" json:"product_count"`
	ActiveProductCount int64 `db:"active_product_count" json:"active_product_count"`
	LowStockCount      int64 `db:"low_stock_count" json:"low_stock_count"`
	GrossSalesCents    int64 `db:"gross_sales_cents" json:"gross_sales_cents"`
	OrderCount         int64 `db:"order_count" json:"order_count"`
}

func (q *Queries) SellerDashboardStats(ctx context.Context, sellerID pgtype.UUID) (SellerDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, sellerDashboardStats, sellerID)
	var i SellerDashboardStatsRow
	err := row.Scan(
		&i.ProductCount,
		&i.ActiveProductCount,
		&i.LowStockCount,
		&i.GrossSalesCents,
		&i.OrderCount,
	)
	return i, err
}

const sellerRecentOrders = `-- name: SellerRecentOrders :many
SELECT o.id, o.order_number, o.user_id, o.checkout_session_id, o.status, o.subtotal_cents, o.discount_cents, o.shipping_cents, o.tax_cents, o.total_cents, o.currency, o.shipping_address, o.billing_address, o.placed_at, o.paid_at, o.cancelled_at, o.completed_at, o.created_at, o.updated_at
FROM orders o
WHERE EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id AND oi.seller_id = $1)
ORDER BY o.placed_at DESC
LIMIT $2
`

type SellerRecentOrdersParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit    int32       `db:"limit" json:"limit"`
}

func (q *Queries) SellerRecentOrders(ctx context.Context, arg SellerRecentOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, sellerRecentOrders, arg.SellerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.CheckoutSessionID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Currency,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerSalesChart = `-- name: SellerSalesChart :many
SELECT date_trunc('day', o.placed_at)::date AS day,
       COALESCE(sum(oi.total_price_cents), 0)::bigint AS sales_cents,
       count(DISTINCT oi.order_id)::bigint AS order_count
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.seller_id = $1
  AND o.placed_at >= now() - ($2::int * interval '1 day')
GROUP BY day
ORDER BY day ASC
`

type SellerSalesChartParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Days     int32       `db:"days" json:"days"`
}

type SellerSalesChartRow struct {
	Day        pgtype.Date `db:"day" json:"day"`
	SalesCents int64       `db:"sales_cents" json:"sales_cents"`
	OrderCount int64       `db:"order_count" json:"order_count"`
}

func (q *Queries) SellerSalesChart(ctx context.Context, arg SellerSalesChartParams) ([]SellerSalesChartRow, error) {
	rows, err := q.db.Query(ctx, sellerSalesChart, arg.SellerID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerSalesChartRow
	for rows.Next() {
		var i SellerSalesChartRow
		if err := rows.Scan(&i.Day, &i.SalesCents, &i.OrderCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerTopProducts = `-- name: SellerTopProducts :many
SELECT p.id, p.seller_id, p.category_id, p.brand_id, p.name, p.slug, p.description, p.status, p.min_price_cents, p.max_price_cents, p.currency, p.total_sold, p.rating, p.review_count, p.published_at, p.deleted_at, p.created_at, p.updated_at, p.moderation_status, p.moderation_reason, p.moderated_by, p.moderated_at
FROM products p
WHERE p.seller_id = $1
  AND p.deleted_at IS NULL
ORDER BY p.total_sold DESC, p.rating DESC, p.created_at DESC
LIMIT $2
`

type SellerTopProductsParams struct {
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
	Limit    int32       `db:"limit" json:"limit"`
}

type SellerTopProductsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) SellerTopProducts(ctx context.Context, arg SellerTopProductsParams) ([]SellerTopProductsRow, error) {
	rows, err := q.db.Query(ctx, sellerTopProducts, arg.SellerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerTopProductsRow
	for rows.Next() {
		var i SellerTopProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.Currency,
			&i.TotalSold,
			&i.Rating,
			&i.ReviewCount,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationStatus,
			&i.ModerationReason,
			&i.ModeratedBy,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSellerProduct = `-- name: SoftDeleteSellerProduct :exec
UPDATE products
SET status = 'deleted',
    deleted_at = now()
WHERE id = $1
  AND seller_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteSellerProductParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) SoftDeleteSellerProduct(ctx context.Context, arg SoftDeleteSellerProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteSellerProduct, arg.ID, arg.SellerID)
	return err
}

const submitSellerApplication = `-- name: SubmitSellerApplication :one
UPDATE seller_applications
SET status = 'submitted',
    submitted_at = now()
WHERE id = $1
  AND user_id = $2
  AND status IN ('draft', 'rejected')
RETURNING id, user_id, shop_name, slug, business_type, country, currency, status, submitted_at, reviewed_by, reviewed_at, rejection_reason, metadata, created_at, updated_at
`

type SubmitSellerApplicationParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) SubmitSellerApplication(ctx context.Context, arg SubmitSellerApplicationParams) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, submitSellerApplication, arg.ID, arg.UserID)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopName,
		&i.Slug,
		&i.BusinessType,
		&i.Country,
		&i.Currency,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const suspendSellerForAdmin = `-- name: SuspendSellerForAdmin :one
UPDATE sellers
SET status = $1::seller_status
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at, settings
`

type SuspendSellerForAdminParams struct {
	Status interface{} `db:"status" json:"status"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SuspendSellerForAdmin(ctx context.Context, arg SuspendSellerForAdminParams) (Seller, error) {
	row := q.db.QueryRow(ctx, suspendSellerForAdmin, arg.Status, arg.ID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const unpublishSellerProduct = `-- name: UnpublishSellerProduct :one
UPDATE products
SET status = 'inactive'
WHERE id = $1
  AND seller_id = $2
  AND deleted_at IS NULL
  AND status = 'active'
RETURNING id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at, moderation_status, moderation_reason, moderated_by, moderated_at
`

type UnpublishSellerProductParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SellerID pgtype.UUID `db:"seller_id" json:"seller_id"`
}

type UnpublishSellerProductRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) UnpublishSellerProduct(ctx context.Context, arg UnpublishSellerProductParams) (UnpublishSellerProductRow, error) {
	row := q.db.QueryRow(ctx, unpublishSellerProduct, arg.ID, arg.SellerID)
	var i UnpublishSellerProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const updateInventoryQuantities = `-- name: UpdateInventoryQuantities :one
UPDATE inventory_items
SET quantity_available = $2,
    quantity_reserved = $3,
    low_stock_threshold = COALESCE($4, low_stock_threshold)
WHERE id = $1
RETURNING id, product_id, variant_id, quantity_available, quantity_reserved, low_stock_threshold, created_at, updated_at
`

type UpdateInventoryQuantitiesParams struct {
	ID                pgtype.UUID `db:"id" json:"id"`
	QuantityAvailable int32       `db:"quantity_available" json:"quantity_available"`
	QuantityReserved  int32       `db:"quantity_reserved" json:"quantity_reserved"`
	LowStockThreshold int32       `db:"low_stock_threshold" json:"low_stock_threshold"`
}

func (q *Queries) UpdateInventoryQuantities(ctx context.Context, arg UpdateInventoryQuantitiesParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, updateInventoryQuantities,
		arg.ID,
		arg.QuantityAvailable,
		arg.QuantityReserved,
		arg.LowStockThreshold,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.QuantityAvailable,
		&i.QuantityReserved,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductImageOrder = `-- name: UpdateProductImageOrder :one
UPDATE product_images pi
SET sort_order = $3,
    is_primary = $4
FROM products p
WHERE pi.id = $1
  AND pi.product_id = p.id
  AND p.seller_id = $2
RETURNING pi.id, pi.product_id, pi.url, pi.alt_text, pi.sort_order, pi.is_primary, pi.created_at
`

type UpdateProductImageOrderParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	SellerID  pgtype.UUID `db:"seller_id" json:"seller_id"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
	IsPrimary bool        `db:"is_primary" json:"is_primary"`
}

func (q *Queries) UpdateProductImageOrder(ctx context.Context, arg UpdateProductImageOrderParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, updateProductImageOrder,
		arg.ID,
		arg.SellerID,
		arg.SortOrder,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variants pv
SET sku = COALESCE($1::text, sku),
    name = COALESCE($2::text, name),
    price_cents = COALESCE($3::bigint, price_cents),
    compare_at_price_cents = $4::bigint,
    currency = COALESCE($5::text, currency),
    weight_grams = $6::int,
    is_active = COALESCE($7::boolean, is_active)
FROM products p
WHERE pv.id = $8
  AND pv.product_id = p.id
  AND p.seller_id = $9
  AND pv.deleted_at IS NULL
RETURNING pv.id, pv.product_id, pv.sku, pv.name, pv.price_cents, pv.compare_at_price_cents, pv.currency, pv.weight_grams, pv.is_active, pv.deleted_at, pv.created_at, pv.updated_at
`

type UpdateProductVariantParams struct {
	Sku                 pgtype.Text `db:"sku" json:"sku"`
	Name                pgtype.Text `db:"name" json:"name"`
	PriceCents          pgtype.Int8 `db:"price_cents" json:"price_cents"`
	CompareAtPriceCents pgtype.Int8 `db:"compare_at_price_cents" json:"compare_at_price_cents"`
	Currency            pgtype.Text `db:"currency" json:"currency"`
	WeightGrams         pgtype.Int4 `db:"weight_grams" json:"weight_grams"`
	IsActive            pgtype.Bool `db:"is_active" json:"is_active"`
	ID                  pgtype.UUID `db:"id" json:"id"`
	SellerID            pgtype.UUID `db:"seller_id" json:"seller_id"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateProductVariant,
		arg.Sku,
		arg.Name,
		arg.PriceCents,
		arg.CompareAtPriceCents,
		arg.Currency,
		arg.WeightGrams,
		arg.IsActive,
		arg.ID,
		arg.SellerID,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.Currency,
		&i.WeightGrams,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSellerApplication = `-- name: UpdateSellerApplication :one
UPDATE seller_applications
SET shop_name = COALESCE($1::text, shop_name),
    slug = COALESCE($2::text, slug),
    business_type = COALESCE($3::text, business_type),
    country = COALESCE($4::text, country),
    currency = COALESCE($5::text, currency),
    metadata = COALESCE($6::jsonb, metadata)
WHERE id = $7
  AND user_id = $8
  AND status IN ('draft', 'rejected')
RETURNING id, user_id, shop_name, slug, business_type, country, currency, status, submitted_at, reviewed_by, reviewed_at, rejection_reason, metadata, created_at, updated_at
`

type UpdateSellerApplicationParams struct {
	ShopName     pgtype.Text `db:"shop_name" json:"shop_name"`
	Slug         pgtype.Text `db:"slug" json:"slug"`
	BusinessType pgtype.Text `db:"business_type" json:"business_type"`
	Country      pgtype.Text `db:"country" json:"country"`
	Currency     pgtype.Text `db:"currency" json:"currency"`
	Metadata     []byte      `db:"metadata" json:"metadata"`
	ID           pgtype.UUID `db:"id" json:"id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateSellerApplication(ctx context.Context, arg UpdateSellerApplicationParams) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, updateSellerApplication,
		arg.ShopName,
		arg.Slug,
		arg.BusinessType,
		arg.Country,
		arg.Currency,
		arg.Metadata,
		arg.ID,
		arg.UserID,
	)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopName,
		&i.Slug,
		&i.BusinessType,
		&i.Country,
		&i.Currency,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSellerMedia = `-- name: UpdateSellerMedia :one
UPDATE sellers
SET logo_url = COALESCE($1::text, logo_url),
    banner_url = COALESCE($2::text, banner_url)
WHERE id = $3
  AND user_id = $4
  AND deleted_at IS NULL
RETURNING id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at, settings
`

type UpdateSellerMediaParams struct {
	LogoUrl   pgtype.Text `db:"logo_url" json:"logo_url"`
	BannerUrl pgtype.Text `db:"banner_url" json:"banner_url"`
	ID        pgtype.UUID `db:"id" json:"id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateSellerMedia(ctx context.Context, arg UpdateSellerMediaParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSellerMedia,
		arg.LogoUrl,
		arg.BannerUrl,
		arg.ID,
		arg.UserID,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const updateSellerProduct = `-- name: UpdateSellerProduct :one
UPDATE products
SET category_id = COALESCE($1::uuid, category_id),
    brand_id = COALESCE($2::uuid, brand_id),
    name = COALESCE($3::text, name),
    slug = COALESCE($4::text, slug),
    description = COALESCE($5::text, description),
    min_price_cents = COALESCE($6::bigint, min_price_cents),
    max_price_cents = COALESCE($7::bigint, max_price_cents),
    currency = COALESCE($8::text, currency),
    moderation_status = 'pending'
WHERE id = $9
  AND seller_id = $10
  AND deleted_at IS NULL
  AND status <> 'deleted'
RETURNING id, seller_id, category_id, brand_id, name, slug, description, status, min_price_cents, max_price_cents, currency, total_sold, rating, review_count, published_at, deleted_at, created_at, updated_at, moderation_status, moderation_reason, moderated_by, moderated_at
`

type UpdateSellerProductParams struct {
	CategoryID    pgtype.UUID `db:"category_id" json:"category_id"`
	BrandID       pgtype.UUID `db:"brand_id" json:"brand_id"`
	Name          pgtype.Text `db:"name" json:"name"`
	Slug          pgtype.Text `db:"slug" json:"slug"`
	Description   pgtype.Text `db:"description" json:"description"`
	MinPriceCents pgtype.Int8 `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents pgtype.Int8 `db:"max_price_cents" json:"max_price_cents"`
	Currency      pgtype.Text `db:"currency" json:"currency"`
	ID            pgtype.UUID `db:"id" json:"id"`
	SellerID      pgtype.UUID `db:"seller_id" json:"seller_id"`
}

type UpdateSellerProductRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SellerID         pgtype.UUID        `db:"seller_id" json:"seller_id"`
	CategoryID       pgtype.UUID        `db:"category_id" json:"category_id"`
	BrandID          pgtype.UUID        `db:"brand_id" json:"brand_id"`
	Name             string             `db:"name" json:"name"`
	Slug             string             `db:"slug" json:"slug"`
	Description      pgtype.Text        `db:"description" json:"description"`
	Status           interface{}        `db:"status" json:"status"`
	MinPriceCents    int64              `db:"min_price_cents" json:"min_price_cents"`
	MaxPriceCents    int64              `db:"max_price_cents" json:"max_price_cents"`
	Currency         string             `db:"currency" json:"currency"`
	TotalSold        int64              `db:"total_sold" json:"total_sold"`
	Rating           pgtype.Numeric     `db:"rating" json:"rating"`
	ReviewCount      int64              `db:"review_count" json:"review_count"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	ModerationReason pgtype.Text        `db:"moderation_reason" json:"moderation_reason"`
	ModeratedBy      pgtype.UUID        `db:"moderated_by" json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `db:"moderated_at" json:"moderated_at"`
}

func (q *Queries) UpdateSellerProduct(ctx context.Context, arg UpdateSellerProductParams) (UpdateSellerProductRow, error) {
	row := q.db.QueryRow(ctx, updateSellerProduct,
		arg.CategoryID,
		arg.BrandID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.MinPriceCents,
		arg.MaxPriceCents,
		arg.Currency,
		arg.ID,
		arg.SellerID,
	)
	var i UpdateSellerProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.Currency,
		&i.TotalSold,
		&i.Rating,
		&i.ReviewCount,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationStatus,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const updateSellerProfile = `-- name: UpdateSellerProfile :one
UPDATE sellers
SET shop_name = COALESCE($1::text, shop_name),
    slug = COALESCE($2::text, slug),
    description = COALESCE($3::text, description)
WHERE id = $4
  AND user_id = $5
  AND deleted_at IS NULL
RETURNING id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at, settings
`

type UpdateSellerProfileParams struct {
	ShopName    pgtype.Text `db:"shop_name" json:"shop_name"`
	Slug        pgtype.Text `db:"slug" json:"slug"`
	Description pgtype.Text `db:"description" json:"description"`
	ID          pgtype.UUID `db:"id" json:"id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateSellerProfile(ctx context.Context, arg UpdateSellerProfileParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSellerProfile,
		arg.ShopName,
		arg.Slug,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const updateSellerSettings = `-- name: UpdateSellerSettings :one
UPDATE sellers
SET settings = COALESCE($1::jsonb, '{}'::jsonb)
WHERE id = $2
  AND user_id = $3
  AND deleted_at IS NULL
RETURNING id, user_id, application_id, shop_name, slug, description, logo_url, banner_url, status, rating, total_sales, deleted_at, created_at, updated_at, settings
`

type UpdateSellerSettingsParams struct {
	Settings []byte      `db:"settings" json:"settings"`
	ID       pgtype.UUID `db:"id" json:"id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateSellerSettings(ctx context.Context, arg UpdateSellerSettingsParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSellerSettings, arg.Settings, arg.ID, arg.UserID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ShopName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Status,
		&i.Rating,
		&i.TotalSales,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const upsertInventoryItem = `-- name: UpsertInventoryItem :one
INSERT INTO inventory_items (product_id, variant_id, quantity_available, quantity_reserved, low_stock_threshold)
VALUES ($1, $2, $3, 0, COALESCE($4, 5))
ON CONFLICT (variant_id) DO UPDATE
SET quantity_available = EXCLUDED.quantity_available,
    low_stock_threshold = EXCLUDED.low_stock_threshold
RETURNING id, product_id, variant_id, quantity_available, quantity_reserved, low_stock_threshold, created_at, updated_at
`

type UpsertInventoryItemParams struct {
	ProductID         pgtype.UUID `db:"product_id" json:"product_id"`
	VariantID         pgtype.UUID `db:"variant_id" json:"variant_id"`
	QuantityAvailable int32       `db:"quantity_available" json:"quantity_available"`
	Column4           interface{} `db:"column_4" json:"column_4"`
}

func (q *Queries) UpsertInventoryItem(ctx context.Context, arg UpsertInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, upsertInventoryItem,
		arg.ProductID,
		arg.VariantID,
		arg.QuantityAvailable,
		arg.Column4,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.QuantityAvailable,
		&i.QuantityReserved,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
